### ISSUE TITLE
ERRORs when adding SNVs using SE RNA-Seq data

### ISSUE THREAD

**Issue by iranmdl** [adamewing/bamsurgeon#101]
Hi!
I will be very grateful if someone could guide me a bit.
I'm trying to add SNVs to a RNA-Seq BAM file aligned using STAR mapper.
Here is the command I run 1 week ago:
`INFO	2017-11-07 11:22:05.779179	starting /storage/003-Third_party_tools/src/bamsurgeon/bin/addsnv.py called with args: /storage/003-Third_party_tools/src/bamsurgeon/bin/addsnv.py -v ../../bamsurgeon_DREAMlike/cosmic/cosmic_covered_SNV_BS.txt -f ../STAR/SRR653897_STAR_Aligned.sorted.bam -r ../../../001-pipelines/data/hs37d5.fa -o mutbam.bam -p 10 --picardjar /storage/003-Third_party_tools/src/picard/picard.jar --mindepth 3 --minmutreads 1 --tagreads --aligner STAR --alignopts STARrefdir:/storage/001-pipelines/data/STAR_index -s 0.1 --ignorepileup --single`

BamSurgeon has been running since `2017-11-07` and it has just finished now with a lot of errors, all of them of the same format:
```
ERROR	2017-11-07 11:22:05.881453	encountered error in mutation spikein: ['1_2938383_2938383_0.178_T']
ERROR	2017-11-07 11:22:05.894334	encountered error in mutation spikein: ['1_2939014_2939014_0.528_A']
ERROR	2017-11-07 11:22:05.894668	encountered error in mutation spikein: ['1_3328295_3328295_0.01_G']
...
...
```

The following lines show the last lines printed out in the prompt:

```
INFO	2017-11-20 10:18:42.301486	haplo_6_30672553_30672553	aligning ['addsnv.tmp/haplo_6_30672553_30672553.tmpbam.92626778-76f5-4187-89d2-7de4b89d3cc5.fastq'] with STAR

************************************************************
ERROR	2017-11-20 10:18:42.316819	encountered error in mutation spikein: ['6_30672553_30672553_0.811_G']
Traceback (most recent call last):
  File "/storage/003-Third_party_tools/src/bamsurgeon/bin/addsnv.py", line 275, in makemut
    aligners.remap_bam(args.aligner, tmpoutbamname, args.refFasta, alignopts, mutid=hapstr, paired=(not args.single), picardjar=args.picardjar)
  File "build/bdist.linux-x86_64/egg/bamsurgeon/aligners.py", line 79, in remap_bam
    remap_STAR_bam(bamfn, threads, fastaref, picardjar, options['STARrefdir'], mutid=mutid, paired=paired)
  File "build/bdist.linux-x86_64/egg/bamsurgeon/aligners.py", line 446, in remap_STAR_bam
    p = subprocess.call(sam_cmd)
  File "/usr/lib/python2.7/subprocess.py", line 523, in call
    return Popen(*popenargs, **kwargs).wait()
  File "/usr/lib/python2.7/subprocess.py", line 711, in __init__
    errread, errwrite)
  File "/usr/lib/python2.7/subprocess.py", line 1343, in _execute_child
    raise child_exception
OSError: [Errno 2] No such file or directory
************************************************************
INFO	2017-11-20 10:18:42.318507	no succesful mutations
```

I will appreciate any help or clue or a way to check what is going on, and hopefully, be able to follow the analysis without restarting from the beginning.

Thank you very much in advance,
Cheers.

**Comment by adamewing** [comment]
Hi,

To get started, can you verify that the STAR executable is in your $PATH?

For STAR I'd recommend testing on just one or two sites with decent coverage initially and doing the larger set of mutations only once that's working as it's quite slow (sorry).

Best,
Adam

**Comment by iranmdl** [comment]
Omg...
newbie mistake... I think that `STAR` is not on my $PATH .. Is it possible to re-run the command from that step instead of restarting it from the beginning?

Thank you again,

**Comment by adamewing** [comment]
Ah, hope that sorts it then. As I said I'd recommend testing on a few sites to ensure you're getting the results you want before scaling up. Unfortunately the step you're at (running STAR) is the time-consuming one so there's not really any checkpoint to start from that would save time. If there's anything you can do to further parallelise the run that might help with runtime.

**Comment by adamewing** [comment]
Closing, feel free to reopen if there are still unresolved issues.

**Comment by iranmdl** [comment]
Hi again! The previous issue was fixed. However... I'm having weird problems now. I have tried to run `addsnv.py` script with a small subset of 20 variants. This was the command:

`INFO	2017-12-06 20:51:35.791862	starting /storage/src/bamsurgeon/bin/addsnv.py called with args: /storage/src/bamsurgeon/bin/addsnv.py -v subset.txt -f SRR653897_STAR_Aligned.sorted.bam -r /storage/data/GRCh37/hs37d5.fa -o mutbam.bam -p 12 --picardjar /storage/src/picard/picard.jar --mindepth 3 --minmutreads 1 --aligner STAR --alignopts STARrefdir:/storage/data/GRCh37/STAR_index -s 0.1 --ignorepileup --single`

And I got this message at the end:

```
INFO	2017-12-07 05:38:35.145757	haplo_14_23549554_23549554	writing addsnv.tmp/haplo_14_23549554_23549554.tmpbam.1f186046-95da-4878-8862-8afea55b0385.bamAligned.out.sam to BAM...
INFO	2017-12-07 05:38:35.149284	haplo_14_23549554_23549554	deleting SAM: addsnv.tmp/haplo_14_23549554_23549554.tmpbam.1f186046-95da-4878-8862-8afea55b0385.bamAligned.out.sam
INFO	2017-12-07 05:38:35.149408	haplo_14_23549554_23549554	sorting output: samtools sort -@ 1 -m 10000000000 -T addsnv.tmp/haplo_14_23549554_23549554.tmpbam.1f186046-95da-4878-8862-8afea55b0385.bam.realign.sorted.bam -o addsnv.tmp/haplo_14_23549554_23549554.tmpbam.1f186046-95da-4878-8862-8afea55b0385.bam.realign.sorted.bam addsnv.tmp/haplo_14_23549554_23549554.tmpbam.1f186046-95da-4878-8862-8afea55b0385.bam
INFO	2017-12-07 05:38:35.153404	haplo_14_23549554_23549554	remove original bam:addsnv.tmp/haplo_14_23549554_23549554.tmpbam.1f186046-95da-4878-8862-8afea55b0385.bam
INFO	2017-12-07 05:38:35.153500	haplo_14_23549554_23549554	rename sorted bam: addsnv.tmp/haplo_14_23549554_23549554.tmpbam.1f186046-95da-4878-8862-8afea55b0385.bam.realign.sorted.bam to original name: addsnv.tmp/haplo_14_23549554_23549554.tmpbam.1f186046-95da-4878-8862-8afea55b0385.bam
INFO	2017-12-07 05:38:35.153569	haplo_14_23549554_23549554	indexing: samtools index addsnv.tmp/haplo_14_23549554_23549554.tmpbam.1f186046-95da-4878-8862-8afea55b0385.bam
INFO	2017-12-07 05:38:35.156889	haplo_14_23549554_23549554	removing addsnv.tmp/haplo_14_23549554_23549554.tmpbam.1f186046-95da-4878-8862-8afea55b0385.fastq
INFO	2017-12-07 05:38:35.345197	haplo_14_23549554_23549554	avgincover: 46.0 avgoutcover: 42.3333333333
```

However, here comes the weird part, I re-run the very same command in the following day, and this time I got the following message:
```
INFO	2017-12-08 18:43:53.553393	done making mutations, merging mutations into ../NeoXpress_out/STAR/SRR653897_STAR_Aligned.sorted.bam --> mutbam.bam
loading donor reads into dictionary...
secondary reads count:0
supplementary reads count:0
loaded 1812 reads, (0 excluded, 0 null or secondary or supplementary--> ignored)
replaced 1812 reads (0 excluded )
kept 0 secondary reads.
kept 0 supplementary reads.
```
**Yay!Succes!** Do you have any clue about the possible issue here? If the server where I'm running the analyses is busy.. can be this the source of the problem? I would like to simulate ~300 variants.. and I would like to know if I should use the full server resources only for this task, or if the problem is coming from other way.
Thank you again,
:)
