### ISSUE TITLE
best contig too short to make mutation

### ISSUE THREAD

**Issue by Eric4Wu** [adamewing/bamsurgeon#103]
Hi guys, I have some issue here.

I successfully install BAMSurgeon by conda and install other Prerequisites by conda or pip

test_sv.sh successfully generate the SV_simulation.bam to my desired folder.

but no matter how i change the only one SV (only DUP) range in my sv_list.txt, it just keep popping out:

best contig too short to make mutation! 

and then no succesful mutations message .

i did change the SV site from 1000bp ~ 100000bp and also the location of SV but nothing  has changed.

my sequencing platform is Agilent Sureselect WES (based on illumina short read + the target site they choosed)

Is it able to process WES bam file?

**Comment by Eric4Wu** [comment]
I use debug command: --debug

![bamsurgeon](https://user-images.githubusercontent.com/32456931/33608640-18c13780-da00-11e7-833d-33a2e4e7efc9.jpg)

I can see these mutation reads did generate but just can,t put into simulation.bam

I guess this is due to WES bam ? it only contain exon region, these read can not meet the region I 

propose, so these read are conclude as "too short".

However, addindel only has insertion & deletion, insertion has to insert the seq, but is there any option 

just like DUP? the only purpose I want just increase the reads/coverage of mutation target region and 

then i can exam the WES CNV caller.

**Comment by adamewing** [comment]
I think you've identified the issue correctly. WES means contigs will usually be shorter than addsv needs because the capture regions aren't big. You could maybe try decreasing the parameter -l/--maxlibsize to something like 100 to allow smaller contigs but I haven't tested this with WES CNV callers.

**Comment by Eric4Wu** [comment]
Hi adamewing,

thanks for reply, I will keep trying the simulation.

so in general, BAMSurgeon is create for WGS simulation based on empirical tumor model?

would your group trying on target sequencing simulation: like NEAT & TargetSim

just curious about how was the trend in simulation feild.

Many thanks!

**Comment by Eric4Wu** [comment]
Hi adamewing,

I have one question, how do I force simulator keep contig even it is too short?

I have already use "-l 1" to specify that the max library size be 1bp. So, its criteria should be every contig 

bigger than 3bp should be view as mutation and be simulated into simulated bam.

However, i still see wgsim pop out this message:

[wgsim core]: the contig length is shorted than 510, will be ignored.

How does this happen even in the maxlibsize is 1bp?

my limitation is i have to simulated the read in exon target region, these region often short and not 

concatenative, if I use whole gene loci to simulate, I found only some exon will be involved in the 

mutation simulation process, take TP53 as an example:

TP53 (hg19 assembly , Agilent SureSelect XT2 human all exon V6 platform) , chr17:7572906-7580759

![2017_12_11_5th_simulation_chr17-7572906-7580759_igv_plot](https://user-images.githubusercontent.com/32456931/33870315-3330be68-df48-11e7-9205-0f71b54ab53b.jpg)

You can notice that only around 7,577,000 bp is deleted, other distribution still not change.

What I want is that every target exon region is DEL 0.2 

Which parameter should I use to force wgsim core take every contig into simulation?

Many Thanks!!!

**Comment by Eric4Wu** [comment]
Hi, adamewing,

the wgsim_core  message is like this : 

[wgsim] seed = 1513056176
[wgsim_core] calculating the total length of the reference sequence...
[wgsim_core] 1 sequences, total length: 170
[wgsim_core] skip sequence 'target' as it is shorter than 510!

I hope no sequence will be skip!!

Many Thanks!!!!

**Comment by adamewing** [comment]
I suspect you're not going to wrangle BAMSurgeon into generating a realistic simulation of large deletions from exome data - that's unfortunately kind of out of scope for the assembly-based design of the program currently. Since any assembly will have gaps corresponding to the introns, modifying the entire region of the gene in one go won't be possible. Maybe have a look a tHapMix: https://github.com/Illumina/tHapMix

**Comment by Eric4Wu** [comment]
yeap, I found even I change --ismean & --issd will that BAMSurgeon stock in making mutation. 

so I can't use BAMSurgeon to increase/decrease the reads in target  exon region in normal bam file?

I will try tHapMix , thanks for reply! so BAMSurgeon is design for whole genome sequencing BAM file?

sorry for using WGS simulator for WES simulating use!
