### ISSUE TITLE
addsnv RNASeq BAM file issue

### ISSUE THREAD

**Issue by iranmdl** [adamewing/bamsurgeon#105]
Hi again!  I'm having weird situation trying to run addsnv with STAR aligned RNASeq BAM file. I have tried to run `addsnv.py` script with a small subset of 20 variants. This was the command:

`INFO	2017-12-06 20:51:35.791862	starting /storage/src/bamsurgeon/bin/addsnv.py called with args: /storage/src/bamsurgeon/bin/addsnv.py -v subset.txt -f SRR653897_STAR_Aligned.sorted.bam -r /storage/data/GRCh37/hs37d5.fa -o mutbam.bam -p 12 --picardjar /storage/src/picard/picard.jar --mindepth 3 --minmutreads 1 --aligner STAR --alignopts STARrefdir:/storage/data/GRCh37/STAR_index -s 0.1 --ignorepileup --single`

And I got this message at the end:

```
INFO	2017-12-07 05:38:35.145757	haplo_14_23549554_23549554	writing addsnv.tmp/haplo_14_23549554_23549554.tmpbam.1f186046-95da-4878-8862-8afea55b0385.bamAligned.out.sam to BAM...
INFO	2017-12-07 05:38:35.149284	haplo_14_23549554_23549554	deleting SAM: addsnv.tmp/haplo_14_23549554_23549554.tmpbam.1f186046-95da-4878-8862-8afea55b0385.bamAligned.out.sam
INFO	2017-12-07 05:38:35.149408	haplo_14_23549554_23549554	sorting output: samtools sort -@ 1 -m 10000000000 -T addsnv.tmp/haplo_14_23549554_23549554.tmpbam.1f186046-95da-4878-8862-8afea55b0385.bam.realign.sorted.bam -o addsnv.tmp/haplo_14_23549554_23549554.tmpbam.1f186046-95da-4878-8862-8afea55b0385.bam.realign.sorted.bam addsnv.tmp/haplo_14_23549554_23549554.tmpbam.1f186046-95da-4878-8862-8afea55b0385.bam
INFO	2017-12-07 05:38:35.153404	haplo_14_23549554_23549554	remove original bam:addsnv.tmp/haplo_14_23549554_23549554.tmpbam.1f186046-95da-4878-8862-8afea55b0385.bam
INFO	2017-12-07 05:38:35.153500	haplo_14_23549554_23549554	rename sorted bam: addsnv.tmp/haplo_14_23549554_23549554.tmpbam.1f186046-95da-4878-8862-8afea55b0385.bam.realign.sorted.bam to original name: addsnv.tmp/haplo_14_23549554_23549554.tmpbam.1f186046-95da-4878-8862-8afea55b0385.bam
INFO	2017-12-07 05:38:35.153569	haplo_14_23549554_23549554	indexing: samtools index addsnv.tmp/haplo_14_23549554_23549554.tmpbam.1f186046-95da-4878-8862-8afea55b0385.bam
INFO	2017-12-07 05:38:35.156889	haplo_14_23549554_23549554	removing addsnv.tmp/haplo_14_23549554_23549554.tmpbam.1f186046-95da-4878-8862-8afea55b0385.fastq
INFO	2017-12-07 05:38:35.345197	haplo_14_23549554_23549554	avgincover: 46.0 avgoutcover: 42.3333333333
```

However, here comes the weird part, I re-run the very same command in the following day, and this time I got the following message:
```
INFO	2017-12-08 18:43:53.553393	done making mutations, merging mutations into ../NeoXpress_out/STAR/SRR653897_STAR_Aligned.sorted.bam --> mutbam.bam
loading donor reads into dictionary...
secondary reads count:0
supplementary reads count:0
loaded 1812 reads, (0 excluded, 0 null or secondary or supplementary--> ignored)
replaced 1812 reads (0 excluded )
kept 0 secondary reads.
kept 0 supplementary reads.
```
**Yay!Succes!** Do you have any clue about the possible issue here? If the server where I'm running the analyses is busy.. can be this the source of the problem? I would like to simulate ~300 variants.. and I would like to know if I should use the full server resources only for this task, or if the problem is coming from other way.
Thank you again,
:)

**Comment by adamewing** [comment]
Hi, Are those the full outputs of your run on both days? It looks like those are from different stages of the program's execution so it's hard to compare. If you're comparing between runs I'd also use the --seed parameter.

It should be fine on a shared system so long as nothing is interfering with the the temporary directory (--tmpdir).

**Comment by adamewing** [comment]
Close due to inactivity
