### ISSUE TITLE
empty bam file while generating snp spike-in

### ISSUE THREAD

**Issue by douym** [adamewing/bamsurgeon#106]
Hi adam,

I tried adding snps to a bam file but failed, and the error is as follows:

python bamsurgeon/bin/addsnv.py -v test.input.pos -f test.sorted.bam -r human_g1k_v37_decoy.fasta -o test.edited.bam --seed 123 --ignoreref --force
INFO    2018-01-01 18:00:05.922178      starting bamsurgeon/bin/addsnv.py called with args: bamsurgeon/bin/addsnv.py -v test.input.pos -f test.sorted.bam -r /home/yd65/tools/MosaicHunter/resources/human_g1k_v37_decoy.fasta -o test.edited.bam --seed 123 --ignoreref --force

Debug, haploclusters:[[{'start': 909419, 'end': 909419, 'chrom': '1', 'altbase': 'C', 'vaf': 0.98}]]
INFO    2018-01-01 18:00:06.042761      haplo_1_909419_909419   creating tmp bam:  addsnv.tmp/haplo_1_909419_909419.tmpbam.39fdc5c9-9d9c-4ca8-9cd5-f4cad85daf27.bam
INFO    2018-01-01 18:00:38.403750      haplo_1_909419_909419   len(readlist): 117
INFO    2018-01-01 18:00:38.403986      haplo_1_909419_909419   selected VAF: 0.98

INFO    2018-01-01 18:00:38.404323      haplo_1_909419_909419   picked: 114
INFO    2018-01-01 18:00:38.428961      haplo_1_909419_909419   wrote:  243 mutated: 114
INFO    2018-01-01 18:00:38.434362      haplo_1_909419_909419   mapping 1st end, cmd: bwa aln -q 5 -l 32 -k 3 -t 1 -o 1 -f addsnv.tmp/haplo_1_909419_909419.tmpbam.39fdc5c9-9d9c-4ca8-9cd5-f4cad85daf27.bam.1.sai -b1 /home/yd65/tools/MosaicHunter/resources/human_g1k_v37_decoy.fasta addsnv.tmp/haplo_1_909419_909419.tmpbam.39fdc5c9-9d9c-4ca8-9cd5-f4cad85daf27.bam
************************************************************
ERROR   2018-01-01 18:00:38.460260      encountered error in mutation spikein: ['1_909419_909419_0.98_C']
Traceback (most recent call last):
  File "bamsurgeon/bin/addsnv.py", line 275, in makemut
    aligners.remap_bam(args.aligner, tmpoutbamname, args.refFasta, alignopts, mutid=hapstr, paired=(not args.single), picardjar=args.picardjar)
  File "build/bdist.linux-x86_64/egg/bamsurgeon/aligners.py", line 64, in remap_bam
    remap_backtrack_bam(bamfn, threads, fastaref, mutid=mutid, paired=paired)
  File "build/bdist.linux-x86_64/egg/bamsurgeon/aligners.py", line 103, in remap_backtrack_bam
    subprocess.call(sai1args)
  File "/n/data1/hms/dbmi/park/yanmei/tools/anaconda3/envs/python2/lib/python2.7/subprocess.py", line 168, in call
    return Popen(*popenargs, **kwargs).wait()
  File "/n/data1/hms/dbmi/park/yanmei/tools/anaconda3/envs/python2/lib/python2.7/subprocess.py", line 390, in __init__
    errread, errwrite)
  File "/n/data1/hms/dbmi/park/yanmei/tools/anaconda3/envs/python2/lib/python2.7/subprocess.py", line 1025, in _execute_child
    raise child_exception
OSError: [Errno 2] No such file or directory
************************************************************
INFO    2018-01-01 18:00:38.471609      no succesful mutations

Would you please help figure out what could be the problem? Thanks very much!

Best wishes

**Comment by adamewing** [comment]
Hi there, from the error output it looks like `bwa` might not be installed or present in your `$PATH` - I'd recommend double-checking all the prerequisite software packages are installed and running `test_snv.sh` from within the `/test` directory before proceeding with your own data. Let me know if this doesn't help or you run into further difficulties.

**Comment by douym** [comment]
Hi, thanks very much @adamewing ! I loaded bwa and re-run the test_snv.sh, and it works well. 
However, when I slightly changed the code or input file, there would be errors:
# original code (which works well):
## addsnv.py -v ../test_data/random_snvs.txt -f ../test_data/testregion_realign.bam -r ../test_data/Homo_sapiens_chr22_assembly19.fasta -o test.edited.bam -n 1 -p 1 --ignoresnps --ignorepileup --seed 1234
# new code 1 (align with mem):
## addsnv.py -v ../test_data/random_snvs.txt -f ../test_data/testregion_realign.bam -r ../test_data/Homo_sapiens_chr22_assembly19.fasta -o test.edited.bam -n 1 -p 1 --ignoresnps --ignorepileup --seed 1234 --aligner mem --picardjar picard.jar
## error:
Debug, haploclusters:[[{'start': 34166720, 'end': 34166721, 'chrom': '22', 'altbase': None, 'vaf': 1.0}]]
INFO    2018-01-02 10:04:02.786432      haplo_22_34166721_34166721      creating tmp bam:  addsnv.tmp/haplo_22_34166721_34166721.tmpbam.23c0e9bc-3f03-4af1-884c-4fbc1a4deef2.bam
INFO    2018-01-02 10:04:08.047860      haplo_22_34166721_34166721      len(readlist): 58
INFO    2018-01-02 10:04:08.047981      haplo_22_34166721_34166721      selected VAF: 1.0

INFO    2018-01-02 10:04:08.048175      haplo_22_34166721_34166721      picked: 58
INFO    2018-01-02 10:04:08.050818      haplo_22_34166721_34166721      wrote:  58 mutated: 58
INFO    2018-01-02 10:04:08.090864      haplo_22_34166721_34166721      converting addsnv.tmp/haplo_22_34166721_34166721.tmpbam.23c0e9bc-3f03-4af1-884c-4fbc1a4deef2.bam to fastq

INFO    2018-01-02 10:04:08.091148      converting BAM addsnv.tmp/haplo_22_34166721_34166721.tmpbam.23c0e9bc-3f03-4af1-884c-4fbc1a4deef2.bam to FASTQ
INFO    2018-01-02 10:04:09.534768      haplo_22_34166721_34166721      aligning addsnv.tmp/haplo_22_34166721_34166721.tmpbam.23c0e9bc-3f03-4af1-884c-4fbc1a4deef2.fastq with bwa mem

INFO    2018-01-02 10:04:28.155349      haplo_22_34166721_34166721      writing addsnv.tmp/haplo_22_34166721_34166721.tmpbam.23c0e9bc-3f03-4af1-884c-4fbc1a4deef2.bam.realign.sam to BAM...
INFO    2018-01-02 10:04:28.328534      haplo_22_34166721_34166721      deleting SAM: addsnv.tmp/haplo_22_34166721_34166721.tmpbam.23c0e9bc-3f03-4af1-884c-4fbc1a4deef2.bam.realign.sam
INFO    2018-01-02 10:04:28.410807      haplo_22_34166721_34166721      sorting output: samtools sort -@ 1 -m 10000000000 -T addsnv.tmp/haplo_22_34166721_34166721.tmpbam.23c0e9bc-3f03-4af1-884c-4fbc1a4deef2.bam.realign.sorted.bam -o addsnv.tmp/haplo_22_34166721_34166721.tmpbam.23c0e9bc-3f03-4af1-884c-4fbc1a4deef2.bam.realign.sorted.bam addsnv.tmp/haplo_22_34166721_34166721.tmpbam.23c0e9bc-3f03-4af1-884c-4fbc1a4deef2.bam
INFO    2018-01-02 10:04:28.499481      haplo_22_34166721_34166721      remove original bam:addsnv.tmp/haplo_22_34166721_34166721.tmpbam.23c0e9bc-3f03-4af1-884c-4fbc1a4deef2.bam
INFO    2018-01-02 10:04:28.514261      haplo_22_34166721_34166721      rename sorted bam: addsnv.tmp/haplo_22_34166721_34166721.tmpbam.23c0e9bc-3f03-4af1-884c-4fbc1a4deef2.bam.realign.sorted.bam to original name: addsnv.tmp/haplo_22_34166721_34166721.tmpbam.23c0e9bc-3f03-4af1-884c-4fbc1a4deef2.bam
INFO    2018-01-02 10:04:28.524795      haplo_22_34166721_34166721      indexing: samtools index addsnv.tmp/haplo_22_34166721_34166721.tmpbam.23c0e9bc-3f03-4af1-884c-4fbc1a4deef2.bam
INFO    2018-01-02 10:04:28.587822      haplo_22_34166721_34166721      removing addsnv.tmp/haplo_22_34166721_34166721.tmpbam.23c0e9bc-3f03-4af1-884c-4fbc1a4deef2.fastq
INFO    2018-01-02 10:04:28.611939      haplo_22_34166721_34166721      avgincover: 57.3333333333 avgoutcover: 32.6666666667
WARN    2018-01-02 10:04:28.659895      haplo_22_34166721_34166721      dropped for outcover/incover < 0.9
INFO    2018-01-02 10:04:28.695385      no succesful mutations

# new code 2 (change the input file):
## addsnv.py -v test.input.pos -f test.sorted.bam -r human_g1k_v37_decoy.fasta -o test.edited.bam -n 1 -p 1 --ignoreref --ignoresnps --ignorepileup --seed 1234
## 
[test.input.pos.txt](https://github.com/adamewing/bamsurgeon/files/1597933/test.input.pos.txt)
[test.sorted.bam.bai.gz](https://github.com/adamewing/bamsurgeon/files/1597937/test.sorted.bam.bai.gz)
[test.sorted.bam.gz](https://github.com/adamewing/bamsurgeon/files/1597938/test.sorted.bam.gz)

error:
[bwa_aln] 17bp reads: max_diff = 2
[bwa_aln] 38bp reads: max_diff = 3
[bwa_aln] 64bp reads: max_diff = 4
[bwa_aln] 93bp reads: max_diff = 5
[bwa_aln] 124bp reads: max_diff = 6
[bwa_aln] 157bp reads: max_diff = 7
[bwa_aln] 190bp reads: max_diff = 8
[bwa_aln] 225bp reads: max_diff = 9
[bwa_read_seq] 0.0% bases are trimmed.
[bwa_aln_core] calculate SA coordinate... 0.09 sec
[bwa_aln_core] write to the disk... 0.00 sec
[bwa_aln_core] 238 sequences have been processed.
[main] Version: 0.7.8-r455
[main] CMD: bwa aln -q 5 -l 32 -k 3 -t 1 -o 1 -f addsnv.tmp/haplo_1_909419_909419.tmpbam.12fbad49-c7ea-4f77-863d-888acffb46cf.bam.1.sai -b1 /home/yd65/tools/MosaicHunter/resources/human_g1k_v37_decoy.fast
a addsnv.tmp/haplo_1_909419_909419.tmpbam.12fbad49-c7ea-4f77-863d-888acffb46cf.bam
[main] Real time: 10.813 sec; CPU: 10.731 sec
[bwa_aln] 17bp reads: max_diff = 2
[bwa_aln] 38bp reads: max_diff = 3
[bwa_aln] 64bp reads: max_diff = 4
[bwa_aln] 93bp reads: max_diff = 5
[bwa_aln] 124bp reads: max_diff = 6
[bwa_aln] 157bp reads: max_diff = 7
[bwa_aln] 190bp reads: max_diff = 8
[bwa_aln] 225bp reads: max_diff = 9
[bwa_read_seq] 0.0% bases are trimmed.
[bwa_aln_core] calculate SA coordinate... 0.14 sec
[bwa_aln_core] write to the disk... 0.00 sec
[bwa_aln_core] 238 sequences have been processed.
[main] Version: 0.7.8-r455
[main] CMD: bwa aln -q 5 -l 32 -k 3 -t 1 -o 1 -f addsnv.tmp/haplo_1_909419_909419.tmpbam.12fbad49-c7ea-4f77-863d-888acffb46cf.bam.2.sai -b2 /home/yd65/tools/MosaicHunter/resources/human_g1k_v37_decoy.fast
a addsnv.tmp/haplo_1_909419_909419.tmpbam.12fbad49-c7ea-4f77-863d-888acffb46cf.bam
[main] Real time: 9.812 sec; CPU: 9.625 sec
[bwa_read_seq] 0.0% bases are trimmed.
[bwa_read_seq] 0.0% bases are trimmed.
[bwa_sai2sam_pe_core] convert to sequence coordinate...
[infer_isize] fail to infer insert size: too few good pairs
[bwa_sai2sam_pe_core] time elapses: 0.00 sec
[bwa_sai2sam_pe_core] changing coordinates of 0 alignments.
[bwa_sai2sam_pe_core] align unmapped mate...
[bwa_sai2sam_pe_core] time elapses: 0.00 sec
[bwa_sai2sam_pe_core] refine gapped alignments... 0.00 sec
[bwa_sai2sam_pe_core] print alignments... 0.00 sec
[bwa_sai2sam_pe_core] 238 sequences have been processed.
[main] Version: 0.7.8-r455
[main] CMD: bwa sampe -P -f addsnv.tmp/haplo_1_909419_909419.tmpbam.12fbad49-c7ea-4f77-863d-888acffb46cf.bam.sam /home/yd65/tools/MosaicHunter/resources/human_g1k_v37_decoy.fasta addsnv.tmp/haplo_1_909419
_909419.tmpbam.12fbad49-c7ea-4f77-863d-888acffb46cf.bam.1.sai addsnv.tmp/haplo_1_909419_909419.tmpbam.12fbad49-c7ea-4f77-863d-888acffb46cf.bam.2.sai addsnv.tmp/haplo_1_909419_909419.tmpbam.12fbad49-c7ea-4
addsnv.tmp/haplo_1_909419_909419.tmpbam.12fbad49-c7ea-4f77-863d-888acffb46cf.bam addsnv.tmp/haplo_1_909419_909419.tmpbam.12fbad49-c7ea-4f77-863d-888acffb46cf.bam
[main] Real time: 20.276 sec; CPU: 20.130 sec
[W::sam_parse1] mapped mate cannot have zero coordinate; treated as unmapped
[W::sam_parse1] mapped query cannot have zero coordinate; treated as unmapped
[W::sam_parse1] mapped query cannot have zero coordinate; treated as unmapped
[W::sam_parse1] mapped mate cannot have zero coordinate; treated as unmapped
[W::sam_parse1] mapped query cannot have zero coordinate; treated as unmapped
[W::sam_parse1] mapped mate cannot have zero coordinate; treated as unmapped
[W::sam_parse1] mapped query cannot have zero coordinate; treated as unmapped
[W::sam_parse1] mapped mate cannot have zero coordinate; treated as unmapped
[W::sam_parse1] mapped mate cannot have zero coordinate; treated as unmapped
[W::sam_parse1] mapped query cannot have zero coordinate; treated as unmapped
[W::sam_parse1] mapped query cannot have zero coordinate; treated as unmapped
[W::sam_parse1] mapped mate cannot have zero coordinate; treated as unmapped
[W::sam_parse1] mapped mate cannot have zero coordinate; treated as unmapped
[W::sam_parse1] mapped query cannot have zero coordinate; treated as unmapped
[W::sam_parse1] mapped mate cannot have zero coordinate; treated as unmapped
[W::sam_parse1] mapped query cannot have zero coordinate; treated as unmapped
[W::sam_parse1] mapped query cannot have zero coordinate; treated as unmapped
[W::sam_parse1] mapped query cannot have zero coordinate; treated as unmapped
[W::sam_parse1] mapped query cannot have zero coordinate; treated as unmapped
[W::sam_parse1] mapped mate cannot have zero coordinate; treated as unmapped
[W::sam_parse1] mapped query cannot have zero coordinate; treated as unmapped
[W::sam_parse1] mapped mate cannot have zero coordinate; treated as unmapped
[W::sam_parse1] mapped query cannot have zero coordinate; treated as unmapped
[W::sam_parse1] mapped mate cannot have zero coordinate; treated as unmapped
[W::sam_parse1] mapped mate cannot have zero coordinate; treated as unmapped
[W::sam_parse1] mapped query cannot have zero coordinate; treated as unmapped
[W::sam_parse1] mapped query cannot have zero coordinate; treated as unmapped
[W::sam_parse1] mapped mate cannot have zero coordinate; treated as unmapped
[W::sam_parse1] mapped query cannot have zero coordinate; treated as unmapped
[W::sam_parse1] mapped mate cannot have zero coordinate; treated as unmapped
[W::sam_parse1] mapped query cannot have zero coordinate; treated as unmapped
[W::sam_parse1] mapped mate cannot have zero coordinate; treated as unmapped
[W::sam_parse1] mapped query cannot have zero coordinate; treated as unmapped

Would you please help me figure out how to fix them? Thanks very much for your help!

**Comment by douym** [comment]
Hi @adamewing , it seems the read pairs were mapped to different chromosomes. I added parameter "--force" and fixed the second problem. Thanks!

**Comment by adamewing** [comment]
Hi again, regarding the first problem, there is a test in `test/test_snv_bwamem.sh` which tests whether `bwa mem` spike-ins are working properly. Could you let me know if this runs properly?

Regarding issue #2, I'd need to know more about `test.sorted.bam` and `test.input.pos` to guess at what's going on - my initial suspicion is a malformed .bam file. Will your input .bam validate via the `ValidateSamFile` tool included in picard?

**Comment by adamewing** [comment]
closed due to inactivity
