### ISSUE TITLE
is there a way to not align reads but only edit reads?

### ISSUE THREAD

**Issue by douym** [adamewing/bamsurgeon#107]
Hi @adamewing , very sorry to bother you.
# The original bam file at the aim position looks like this:
![image](https://user-images.githubusercontent.com/8002850/34530632-ca09f642-f07d-11e7-918a-5fb312d5fccb.png)
# During the editing process, there is a tmp bam file, which seems correctly edited:
![image](https://user-images.githubusercontent.com/8002850/34530709-022b3216-f07e-11e7-964b-75c2aceb30c6.png)
# However, after the editing process is finished, the edited file seems unchanged:
![image](https://user-images.githubusercontent.com/8002850/34530761-22192e2a-f07e-11e7-8683-9074a8470f25.png)
# and using bwa-aln or bwa-mem both have the problem.
# the log file of bam-surgeon using bwa-mem:
![image](https://user-images.githubusercontent.com/8002850/34530855-675f8650-f07e-11e7-9a08-665c2e9b14c8.png)

# the error file of bam-surgeon using bwa-mem:
![image](https://user-images.githubusercontent.com/8002850/34531014-de3fd2ca-f07e-11e7-9295-ab72b426f5e0.png)

It seems something goes wrong during the realignment process. Just wonder if we can separately edit bam file and doing alignment? Thanks!

**Comment by adamewing** [comment]
From your error log it appears there is a bam indexing issue (see line starting with [E::hts_idx_push] Region 1482519629..) which suggests there is something unusual about the input BAM file... If you run the ValidateSamFile tool from picard on the input BAM, do you see any errors?

Also, I suggested this on the other open issue (#106) but could you let me know if the test in test/test_snv_bwamem.sh runs properly?

**Comment by adamewing** [comment]
close due to inactivity
