### ISSUE TITLE
skipped site: 22 34067772 34067773 due to N base: ERROR 2018-01-11 13:07:54.390773

### ISSUE THREAD

**Issue by jackyen2000** [adamewing/bamsurgeon#108]
Hi,

I'm trying to introduce some mutation on chr 22 of my BAM file. I modified the "random_snvs.txt" from the test_data folder and use it as the "mutation bed" files but I'm getting some error that I don't understand. Could anyone help me to shed a light? Thanks 

"WARN    2018-01-11 13:08:00.406791      22_34241340_34241341_1.0_T      skipped site: 22 34241340 34241341 due to N base: ERROR 2018-01-11 13:08:00.406747      base passed to mut():  not one of (A,T,C,G)

WARN    2018-01-11 13:08:00.911763      22_34258105_34258106_0.2_G      skipped site: 22 34258105 34258106 due to N base: ERROR 2018-01-11 13:08:00.911728      base passed to mut():  not one of (A,T,C,G)

WARN    2018-01-11 13:08:01.417256      22_34259680_34259681_0.5_T      skipped site: 22 34259680 34259681 due to N base: ERROR 2018-01-11 13:08:01.417231      base passed to mut():  not one of (A,T,C,G)

WARN    2018-01-11 13:08:01.878454      22_34261347_34261348_0.01_G     skipped site: 22 34261347 34261348 due to N base: ERROR 2018-01-11 13:08:01.878413      base passed to mut():  not one of (A,T,C,G)

WARN    2018-01-11 13:08:02.386873      22_34264774_34264775_0.25_T     skipped site: 22 34264774 34264775 due to N base: ERROR 2018-01-11 13:08:02.386848      base passed to mut():  not one of (A,T,C,G)

WARN    2018-01-11 13:08:02.843150      22_34273828_34273829_0.5_C      skipped site: 22 34273828 34273829 due to N base: ERROR 2018-01-11 13:08:02.843107      base passed to mut():  not one of (A,T,C,G)

WARN    2018-01-11 13:08:03.378270      22_34282823_34282824_0.2_T      skipped site: 22 34282823 34282824 due to N base: ERROR 2018-01-11 13:08:03.378229      base passed to mut():  not one of (A,T,C,G)

WARN    2018-01-11 13:08:03.866073      22_34283962_34283963_0.75_C     skipped site: 22 34283962 34283963 due to N base: ERROR 2018-01-11 13:08:03.866028      base passed to mut():  not one of (A,T,C,G)

WARN    2018-01-11 13:08:04.240913      22_34294754_34294755_0.15_A     skipped site: 22 34294754 34294755 due to N base: ERROR 2018-01-11 13:08:04.240888      base passed to mut():  not one of (A,T,C,G)

WARN    2018-01-11 13:08:04.563095      22_34297498_34297499_0.01_T     skipped site: 22 34297498 34297499 due to N base: ERROR 2018-01-11 13:08:04.563050      base passed to mut():  not one of (A,T,C,G)

WARN    2018-01-11 13:08:05.050120      22_34314307_34314308_0.15_G     skipped site: 22 34314307 34314308 due to N base: ERROR 2018-01-11 13:08:05.050075      base passed to mut():  not one of (A,T,C,G)

WARN    2018-01-11 13:08:05.406329      22_34322818_34322819_0.25_C     skipped site: 22 34322818 34322819 due to N base: ERROR 2018-01-11 13:08:05.406291      base passed to mut():  not one of (A,T,C,G)

..."

**Comment by adamewing** [comment]
Hi, What does your mutation input file look like? (paste the first few lines if you're able)

**Comment by adamewing** [comment]
close due to inactivity
