### ISSUE TITLE
Indexing 

### ISSUE THREAD

**Issue by charliecurnin** [adamewing/bamsurgeon#109]
Hi, 

I'm a little confused on the requirements for the fasta file I submit through `python addindel.py -r ...`. 

The help page shows 
```  
            -r REFFASTA, --reference REFFASTA
                        reference genome, fasta indexed with bwa index -a
                        stdsw _and_ samtools faidx
```

But for my `bwa index`, the only options for `-a` are `bwtsw, is or rb2 [auto]`. Trying `bwa index -a stdsw` just gives `[bwa_index] unknown algorithm: 'stdsw'.`

I'm using BWA `Version: 0.7.17-r1188`. Thanks for your help.

**Comment by adamewing** [comment]
Hi,

Apologies for that - the instructions were based on an older version of `bwa`. You can just use `bwa index your_reference.fa`.

Best,
Adam

**Comment by adamewing** [comment]
Updated in b82d384
