### ISSUE TITLE
Adding Indels: addindel.py vs. addsv.py

### ISSUE THREAD

**Issue by charliecurnin** [adamewing/bamsurgeon#110]
Hi Adam,

I have a few related questions about trying to add indels of different sizes and different allele fractions to my bam. 

**A**) I read in the manual that 
>In general, we recommend that short insertions and deletions (those shorter than one read length) be created with addindel.py instead of addsv.py as addindel.py does not require reconstruction of the region through sequence assembly and is thus less error-prone.

Does that mean that, in fact, when the indel is *longer* than one read length, `addsv.py` should be used? 

**B**) `addindel.py` has the `-m MUTFRAC` option and a column for VAF in the `-v` file, but `addsv.py` has neither. (My basic is understanding is that a VAF of `.5` would—assuming normal copy-number—simulate a heterozygous insertion/deletion, and a VAF of `1` would simulate a homozygous one?) 

If I choose to use `addsv.py`, how can I set the VAF/zygosity I want?

**C**) About the `-d COVERDIFF` option for `addindel.py`: The value that's specified here is the portion of the depth of the original bam that the depth in the output bam can vary by, at any particular site, right? So the default value of `.1` means that the output bam can have from .9 to 1.1x the coverage of the original bam? If I'm simulating homozygous indels, for which the coverage could drop close to zero or rise to near double the original coverage, what should I set this too?

Thanks for your help,
Charlie

**Comment by adamewing** [comment]
Hi Charlie,

A) Yes.

B) addsv.py will accept the VAF as the last column in the variant input (1.0 for homozygous, 0.5 for heterozygous, etc.) I think this needs to be updated in the manual.

C) You should be fine with the defaults as it's counting the number of reads spanning the mutation pre and post mutation. Reads with indels will still span the variant so indels won't affect the coverage. You can verify that it's not skipping mutations due to this by monitoring the output for "dropped for outcover/incover" messages.

Best,
Adam

**Comment by charliecurnin** [comment]
Thank you!

**Comment by charliecurnin** [comment]
Wanted to follow up on **C** quickly. I tried to add a single mutation to my BAM file. 
```
python addindel.py -v indels.txt -f $bam -p 8 -r $fasta -o $indelBam
```

`indels.txt`:
```
22      23737863        23737993        1       INS     ATCTGGGGTGACTGGTGGGAGGGAGAGAAATGGCGTAGCGACGGATGGTGTGGGACACCTATAGCTCCTTAGCTCTCTCCACGCTCGTCTGGGTTAGTATGAAGTACCTGGCGCCAGATCGGCGAGTCTC
```

This indel is 130 bp long; most reads in my BAM file, according to `samtools view $bam | cut -f 10 | awk '{print length($0)}' ` are 151 bp. 

The log file says 
```
WARN    2018-03-29 10:32:45.553045      22_23737863_23737993_1.0:INS:ATCTGGGGTGACTGGTGGGAGGGAGAGAAATGGCGTAGCGACGGATGGTGTGGGACACCTATAGCTCCTTAGCTCTCTCCACGCTCGTCTGGGTTAGTATGAAGTACCTGGCGCCAGATCGGCGAGTCTC dropped for outcover/incover < 0.1
INFO    2018-03-29 10:32:45.555137      no succesful mutations
```

I can share with you more of the log file if that's helpful, but there are no other error messages, except one `[infer_isize] fail to infer insert size: too few good pairs`. What's happening here? Why is the coverage changing? 

Thanks, 
Charlie

**Comment by adamewing** [comment]
My guess is the large indel causes enough of your reads to become unmapped or mapped elsewhere that it triggers the coverage cutoff. You could try changing `--coverdiff` to something higher (e.g. 1.0) and have a look at the resulting indel in IGV to assess whether it looks reasonable. The `[infer_isize]` message is from `bwa` and isn't really relevant here (it has to do with estimating the paired-end read insert size during alignment).

**Comment by charliecurnin** [comment]
Thanks for the quick response. I'm a bit confused though. 

Wouldn't I want to set `--coverdiff` to something _lower_, like 0? Isn't the problem that `outcover/incover` is _<_ than 0.1. If I want to see the mutation made, doesn't the ratio need to be greater than the `--coverdiff` value?

**Comment by charliecurnin** [comment]
I set `--coverdiff 0` and the mutation. I've opened it in IGV—the mutated BAM is on top, original on bottom. I really don't have much experience looking at variants there so your expertise would be very welcome. 

<img width="1113" alt="screen shot 2018-03-29 at 7 16 34 pm" src="https://user-images.githubusercontent.com/11037337/38121749-12614c56-3386-11e8-953c-5c7ba76fee67.png">

**Comment by adamewing** [comment]
Sorry, yes `--coverdiff 0` is correct. It looks reads (presumably those with the indel) aren't being aligned to this position following the mutation. If you scroll down a bit in the top panel do you see at least a few reads with a consistent variant indicating an indel?

What I suspect might help is not using the default aligner (it defaults to `bwa aln`) and instead see if you get better results using `bwa mem`. This can be accomplished by adding `--aligner mem` and `--picardjar /path/to/picard.jar` to the `addindel.py` commandline. You'll need a copy of `picard.jar` from [Picard tools](https://broadinstitute.github.io/picard/) to get this working.

**Comment by charliecurnin** [comment]
I tried `python addindel.py -v indels.txt -f $bam -p 8 -d 0 -r $fasta --picardjar $picard --aligner mem -o $indelBam`—it's added on the bottom. 

<img width="1092" alt="screen shot 2018-03-29 at 10 48 59 pm" src="https://user-images.githubusercontent.com/11037337/38126191-cfaf90f2-33a3-11e8-877f-e4efc0748994.png">

It doesn't look there are any reads with the variant (it would be represented as a purple line, right?) in either mutated BAM. 

Here's more of this BAM produced with `--aligner mem`. As you can see, it looks like there is at least one read that the insertion should fall in the middle of—but nothing. 

<img width="1098" alt="screen shot 2018-03-29 at 10 55 21 pm" src="https://user-images.githubusercontent.com/11037337/38126282-7695ed4e-33a4-11e8-958c-373dc28e4fbf.png">

**Comment by adamewing** [comment]
It looks like the left junction of the inserted sequence is there (see the sharp 'cliff' in coverage at the indel site) but the right junction is missing... I'll need to try this on my end. Can you double check that the reads in this BAM are 151bp?

**Comment by charliecurnin** [comment]
Thanks for your help. Yeah, when I hover over any of them, in the yellow box IGV says, `Read length = 151bp`.

**Comment by charliecurnin** [comment]
For what it's worth, I tried to insert the same indel with `addsv.py`. The middle track is with the default aligner; the bottom is with `--aligner mem`. (The top is from before, `addindel.py --aligner mem`.)

<img width="965" alt="screen shot 2018-03-30 at 10 58 17 am" src="https://user-images.githubusercontent.com/11037337/38148021-886a3b64-3409-11e8-901b-f2855a6fe7d0.png">

I'm not quite sure how to interpret the result. I know `addsv.py` isn't recommended when the indel is shorter than the read length, so let me know if I should just ignore this.

**Comment by charliecurnin** [comment]
I turned on "Show soft-clipped bases" in IGV and thought I would share this picture for a side-by-side comparison of the four things I've tried so far. 

<img width="2380" alt="screen shot 2018-03-30 at 1 29 33 pm" src="https://user-images.githubusercontent.com/11037337/38153304-da28e376-3420-11e8-8d07-cd3393484c12.png">

From top to bottom: 

1. `python addindel.py -v indels.txt -f $bam -p 8 -d 0 -r $fasta -o $indelBam`
2. `python addindel.py -v indels.txt -f $bam -p 8 -d 0 -r $fasta --picardjar $picard --aligner mem -o $indelBam`
3. `python addsv.py -v indels.asSV.txt -f $bam -r $fasta -p 8 -o $indelBam`
4. `python addsv.py -v indels.asSV.txt -f $bam -r $fasta -p 8 --aligner mem -o $indelBam`
5. the original `$bam`

`indels.txt`:
```
22      23737863        23737993        1       INS     ATCTGGGGTGACTGGTGGGAGGGAGAGAAATGGCGTAGCGACGGATGGTGTGGGACACCTATAGCTCCTTAGCTCTCTCCACGCTCGTCTGGGTTAGTATGAAGTACCTGGCGCCAGATCGGCGAGTCTC
```

`indels.asSV.txt`:
```
22      23737863        23737993        INS     ATCTGGGGTGACTGGTGGGAGGGAGAGAAATGGCGTAGCGACGGATGGTGTGGGACACCTATAGCTCCTTAGCTCTCTCCACGCTCGTCTGGGTTAGTATGAAGTACCTGGCGCCAGATCGGCGAGTCTC  0      -1      1
```
_(I set the sixth column to `-1` and added an if-statement to `addsv.py` to keep the `ins_motif` equal to `None` and still specify a VAF. `addsv.py`:_
```
if action == 'INS':
      ...
      if len(a) > 3:

                #added to allow specifying VAF without changing default ins_motif
                if a[3] != '-1':
                    ins_motif = a[3]
                    assert '^' in ins_motif, 'insertion motif specification requires cut site defined by ^'
                else:
                    print("-1 specified for ins_motif; remains {}".format(ins_motif))
```
_)_

----------------
A few obvious thoughts: 
- It makes sense to me that there's soft-clipping in both directions, which is why I like BAMs 3 and 4, produced with `addsv.py`—but the soft-clipping doesn't start/end at 23737863 (or even 23737993).
- None of these BAMs have any reads that span the insertion, even though it's only 130bp and they're 151bp. 

![img_0766](https://user-images.githubusercontent.com/11037337/38153729-f90eca10-3422-11e8-87ba-7ab4a51d1e99.JPG)

**Comment by adamewing** [comment]
The results from `addsv.py` look correct for a big indel but aren't exactly where you want them to be because addsv doesn't allow exact specification of the insertion site due to how it operates. You might be able to convince addsv.py to make the mutation where you want (position 23737863) by setting the insertion motif column to something like `CCCCAGCGGGGCCC^AGGCAGAGCTG` (I picked some bases upstream and downstream of your target position). That said, `addindel.py` is the preferred way to make this sort of mutation and it seems there may be bug with large indels that I need to address.

**Comment by adamewing** [comment]
OK should be fixed in 32b3fae, please `git pull`, `python setup.py install` and re-try the insertion with `addindel.py` and let me know how it looks.

**Comment by charliecurnin** [comment]
Thanks for your quick action. `addindel.py` with `mem` on top, default on bottom. 

<img width="1096" alt="screen shot 2018-03-30 at 9 21 25 pm" src="https://user-images.githubusercontent.com/11037337/38159583-6b0d1f26-3460-11e8-96c2-0eab0ac1af05.png">

Without `--aligner mem`, it looks pretty much the same. (I think this BAM was produced with `bwa mem` actually.) But with, what's your take? To me, it seems like a good sign that there's soft-clipping in both directions. But still there's no read that spans the variant. And there's now a spike in the histogram right on the insertion site.

**Comment by adamewing** [comment]
Looks good to me.

- `bwa aln` (the default) is not good on indels, doesn't do soft-clipping, and is not widely used anymore. Chances are your bam was generated by `bwa mem`. I should probably make `mem` the default in the near future.

- I wouldn't expect to see reads that are aligned on both ends (I think that's what you mean by spanning) with an insert size this large relative to the read length in the middle. I'm not sure where the cutoff is with bwa mem, but if you insert something more typical like 10 bases you'll see the spanning reads.

- The red read is because its partner is mapped somewhere either distal to the read here or in an unexpected orientation (i.e. "discordant" or "improper"). These happen sporadically. If there's a bunch of them clustered together (not happening here) it can be a sign of a difficult to map region or a structural variant.

- Your explanation for the 'spike' is correct. This is a feature of real insertions as well.

**Comment by charliecurnin** [comment]
Thank you!
