### ISSUE TITLE
Output BAM Not Sorted

### ISSUE THREAD

**Issue by charliecurnin** [adamewing/bamsurgeon#111]
Hi Adam, 

Just a quick thing: while trying to index a BAM created by `addindel.py`, I got 
```
[E::hts_idx_push] Unsorted positions on sequence #22: 23737716 followed by 23737487
samtools index: failed to create index for "XXX.bs-Indel.bam"
```

It's not a big deal to sort it, but I want to check in case this means something's gone wrong? There are no errors I can see in the log files. 

Thanks,
Charlie

**Comment by adamewing** [comment]
Yep, the BAMs some out unsorted, you'll need to sort it with `samtools sort` or equivalent.
