### ISSUE TITLE
addsv.py Spike-Ins

### ISSUE THREAD

**Issue by charliecurnin** [adamewing/bamsurgeon#115]
Hi Adam, 

I tried to spike-in one indel per size [149, 1000] bp in my 151 bp read WGS BAM. 

```
python $addsv -v $svs -f $bam -p 8 -r $fasta --aligner mem -o $o
```

According to the VCF I genereated with `makevcf_sv.py`, 544 out of 852 mutations were made. A few things to note:

1. The sizes reported in the VCF in the`SVLEN` tag (for deletions) are not what I would expect. Of the 270 deletions that were spiked-in successfully, 56 have an `SVLEN=1800`, 53 have an SVLEN=`1799`. Are the deletions that are being spiked-in actually this size? Or are they being misreported. I'll look more into this too. 

2. 264 of the 852 mutations in my `$svs` file encountered the error `best contig too short to make mutation!`. It looks like in [this issue](https://github.com/adamewing/bamsurgeon/issues/103) you recommend lowering the `-l` value, so I'll try that?

3. Of the other 44 that weren't spiked in: 8 have `generated no contigs, skipping site`; 32 have `contig dropped due to ambiguous base (N), aborting mutation`... and the rest are a bunch of different errors. I'll look at these sites to see if they're just bad places to spike-in.
 
4. Of the mutations that were spiked-in and reported in the VCF, most look great. At the very least, something clearly happened at each of them. Many of the insertions, though, look kind of like less drastic versions of the insertion we discussed in [this issue](https://github.com/adamewing/bamsurgeon/issues/110): a sharp drop or increase in coverage, and asymmetric soft-clipping. A few examples: 

![chr22_31 114 309_31 115 309](https://user-images.githubusercontent.com/11037337/38347379-05fff358-3850-11e8-8320-3aaeae2a72f0.png)

![chr22_27 489 550_27 490 550](https://user-images.githubusercontent.com/11037337/38347381-061f06d0-3850-11e8-971c-24ba38b1373a.png)

![chr22_27 158 039_27 159 039](https://user-images.githubusercontent.com/11037337/38347382-0634e914-3850-11e8-96db-cc2a7fca1f80.png)

![chr22_26 346 972_26 347 972](https://user-images.githubusercontent.com/11037337/38347383-064b3c5a-3850-11e8-9d05-4233dcc9d90f.png)

**Comment by adamewing** [comment]
1. I think `SVLEN` is referring to the size of the window passed in the variant file or the size of the contig and not the insertion itself.

2. Before decreasing `-l`, try increasing the size of the windows in the input variant file.

3. Problems with contig generation is most often due to repetitive sequences (recent transposons, satellites, homopolymers, etc) where you're trying to mutate.

4. I think these look pretty good, there's a bit of a coverage 'shelf' in some of them but I see this in real insertions sometimes as well. I do notice that a lot of the altered reads are mapping as improper pairs - you might have a look at the insert size of your BAM file and adjust `--ismean` and `--issd` to match.

**Comment by charliecurnin** [comment]
Re. `4`: I tried to find the mean and sd in insert size with [`awk '{ if ($9 > 0) { N+=1; S+=$9; S2+=$9*$9 }} END { M=S/N; print "n="N", mean="M", stdev="sqrt ((S2-M*M*N)/(N-1))}'`](https://www.biostars.org/p/16556/#52894). 

Calculating across the entire `$bam` gave `mean=2618.68, stdev=173786`. Running `addsv.py` with this `--ismean` and `--issd` resulted in `no successful mutations`. Most of the spike-ins seem to results in `[wgsim_core] skip sequence 'target' as it is shorter than 523976!`. But interestingly,  `makevcf_sv.py` doesn't appear to be sensitive to these errors as it output a vcf with ~543 variants. 

Calculating after `head -n 10000` gave `mean=552.171, stdev=8074.31`.  Running `addsv.py` with these settings, too, resultsed in ` no succesful mutations` and the same `[wgsim_core]` errors. 

Is this because the insert size and sd I'm specifying are wrong?

**Comment by adamewing** [comment]
Hi, sorry, it's best to calculate insert size with a tool like [CollectInsertSizeMetrics](https://broadinstitute.github.io/picard/command-line-overview.html#CollectInsertSizeMetrics) from the [picard suite](https://broadinstitute.github.io/picard/) to avoid the metrics being driven by outliers. My guess is it's not going to be too far off the defaults.

**Comment by charliecurnin** [comment]
OK, so Picard reported `--ismean 356 --issd 116`. Here are the results from the same insertion (the first one appears to have been shifted a bit). 

![chr22_31 114 309_31 115 309](https://user-images.githubusercontent.com/11037337/38441719-90b7e186-399a-11e8-8d99-9cf73c05f5c8.png)

![chr22_27 489 550_27 490 550](https://user-images.githubusercontent.com/11037337/38441720-90cf8962-399a-11e8-8914-bd6d6a8ee444.png)

![chr22_27 158 039_27 159 039](https://user-images.githubusercontent.com/11037337/38441721-90e5a24c-399a-11e8-85bf-2b8af58294d1.png)

![chr22_26 347 070_26 348 070](https://user-images.githubusercontent.com/11037337/38441722-90fd6e4a-399a-11e8-8599-cc8626dc411e.png)

**Comment by adamewing** [comment]
Yes hard to say, was just a thought. How did you go with increasing the window size in the variant file?

**Comment by charliecurnin** [comment]
Tried increasing the window by 500bp. 

![chr22_31 114 309_31 115 309](https://user-images.githubusercontent.com/11037337/38465818-2e8ddaba-3ad5-11e8-8db3-bffde121202a.png)

![chr22_27 489 550_27 490 550](https://user-images.githubusercontent.com/11037337/38465814-29a7cfc4-3ad5-11e8-8ff4-9b6f9da6a9ab.png)

![chr22_27 158 039_27 159 039](https://user-images.githubusercontent.com/11037337/38465813-265b0f8e-3ad5-11e8-9ec3-658de7b64fe6.png)

The last mutation was now not made: `best contig too short to make mutation!`

**Comment by charliecurnin** [comment]
Got it! Thanks.
