### ISSUE TITLE
VAF information in makevcf_indels.py

### ISSUE THREAD

**Issue by iranmdl** [adamewing/bamsurgeon#116]
Hello!
I noticed that when I run `makevcf.vcf` for producing SNV ground truth VCF file with the successfully spiked-in mutations, VAF information is reported per each variant. However, when I run `makevcf_indels.py`  for producing the ground truth VCF with indels, VAF is missing. Is this intended? Is it possible to report VAF information as well?

Thank you in advance,

**Comment by adamewing** [comment]
Sorry for the delay. You're right, will add that asap.

**Comment by adamewing** [comment]
Fixed in b76e737.
