### ISSUE TITLE
Bam surgeon installation error

### ISSUE THREAD

**Issue by pinninti19** [adamewing/bamsurgeon#118]
Hi
I exported all the dependencies for bam surgeon , its saying can't find bwa, so annoying. 
raceback (most recent call last):
  File "setup.py", line 89, in <module>
    if not check_bwa(): sys.exit('Dependency problem: bwa >= 0.7.12 not found')
  File "setup.py", line 18, in check_bwa
    if line.startswith('Version:'):
TypeError: startswith first arg must be bytes or a tuple of bytes, not str

**Comment by adamewing** [comment]
This looks like it might be a python 3 error. Please check the python version you're using as bamsurgeon currently only supports python 2.7+

**Comment by adamewing** [comment]
Testing locally replicates the error on python 3. Bamsurgeon has not been updated to work with python 3 yet. Module error is due to not running `python setup.py install` If following the install instructions for python 2.7 does not work, please re-open.

**Comment by padovanas** [comment]
I'm having the same issue as pinninti19 when running addindel.py
Traceback (most recent call last):
  File "./addindel.py", line 9, in <module>
    import bamsurgeon.replacereads as rr
ImportError: No module named bamsurgeon.replacereads

I built bamsurgeon using python 2.7.11.

--A

**Comment by adamewing** [comment]
Are you able to run `python setup.py install` successfully?

If so, run the command as `addindel.py` from the working directory that contains the .bam file you're mutating and not `./addindel.py` or otherwise adding the path to the python script.
