### ISSUE TITLE
Documentation clarification regarding SNV vs INDEL spike-in locations

### ISSUE THREAD

**Issue by trutane** [adamewing/bamsurgeon#120]
I came across an important difference regarding how to specify the locations of SNV vs. indels variants that's not clear from the BAMSurgeon manual (dated 18 Feb 2016).

The BAMSurgeon manual states that the varfile file spec for SNVs (addsnv.py) uses 1-based input coordinates for SNVs and implies that the same is true for indels (addindel.py). However, in my experience, indels appear to follow a **0-based** scheme (the traditional BED file convention). So if you want to delete a single base at position 10: start=9, end=10 in the input varfile for addindel.py. I confirmed this by viewing my BAMSurgeon-edited files in IGV.

The BAMsurgeon docs indicate indels have length=(end-start) which suggests it is 0-based. [BED files](http://www.ensembl.org/info/website/upload/bed.html) are officially zero-based, [half-opened intervals](http://genome.ucsc.edu/blog/the-ucsc-genome-browser-coordinate-counting-systems/).

Adam: Thanks for maintaining this awesome tool!

**Comment by adamewing** [comment]
Thanks Steve! I've updated the documentation.
