### ISSUE TITLE
Reverse complemented insertions on minus strand

### ISSUE THREAD

**Issue by rebber** [adamewing/bamsurgeon#121]
Hi!

I've just started to use bamsurgeon, and found an unexpected behaviour for insertions created by addindel.py. The insertions added on the minus strand are represented as reversed complements in the bam file. I found this when running samtools mpileup on the expected insertion site.

For example the following insertion:
4	97260385	97260391	0.428517333023	INS	CTCGCC

After running addindel.py with this insertion (among other indels) in the varfile, and then samtools mpileup on the resulting (then sorted) bam, I get the following pileup:
```4       97260385        A       241     .$.$.$,$,,,,...,........,,..,...,..,,$,$,..,..+6CTCGCC.,+6ggcgag,+6ggcgag,.+6CTCGCC..+6CTCGCC.,,...+6CTCGCC.+6CTCGCC.,+6ggcgag,+6ggcgag.,+6ggcgag,..,+6ggcgag...+6CTCGCC.+6CTCGCC...+6CTCGCC..+6CTCGCC..+6CTCGCC.+6CTCGCC..,,,....+6CTCGCC.+6CTCGCC,.....,,.....+6CTCGCC,.+6CTCGCC.+6CTCGCC..+6CTCGCC..+6CTCGCC..+6CTCGCC..+6CTCGCC,...+6CTCGCC,.+6CTCGCC,+6ggcgag,+6ggcgag,.+6CTCGCC.+6CTCGCC.+6CTCGCC.,,,.,+6ggcgag...+6CTCGCC,+6ggcgag,+6ggcgag,.+6CTCGCC...+6CTCGCC..,+6ggcgag..+6CTCGCC.+6CTCGCC.+6CTCGCC,+6ggcgag..+6CTCGCC..+6CTCGCC.,+6ggcgag,,.....+6CTCGCC,+6ggcgag,+6ggcgag,+6ggcgag,+6ggcgag,+6ggcgag,+6ggcgag..+6CTCGCC,+6ggcgag.+6CTCGCC.+6CTCGCC,+6ggcgag.,+6ggcgag..+6CTCGCC,+6ggcgag,+6ggcgag...+6CTCGCC.+6CTCGCC.+6CTCGCC.+6CTCGCC....+6CTCGCC.,.+6CTCGCC,+6ggcgag.+6CTCGCC,+6ggcgag,.,.+6CTCGCC..,+6ggcgag,,.+6CTCGCC,+6ggcgag,....+6CTCGCC.,+6ggcgag.+6CTCGCC..+6CTCGCC,+6ggcgag,,.+6CTCGCC,....+6CTCGCC.+6CTCGCC.+6CTCGCC..+6CTCGCC...+6CTCGCC...+6CTCGCC..+6CTCGCC..+6CTCGCC,.+6CTCGCC,., DllDGGG<qYYGoo[\mmgmIINBGqGIGmmG55G\;GIGq66I\GGoGGooG\q56q6Gmo5om]^Ko[m\g][g[GGImoI[ZGIoqmoGGomGI^GT\oGqGm[IVIIqI<G65KGI\oIGGY6mI[66GGqGGmm5m^GU5o[oIG5GImmbm\56656.q^5]I6I5oI56oq\.IIIIoIII65I5III6oo5GGI6GqIqIm5II]6GIIIIqmG\Io^IIGqGIqGmAGGGiG```

I.e. on the plus stand the insertion is CTCGCC while on the minus strand it is GGCGAG (reverse complemented). (Corresponding pileup on the original bam file show only reference alleles, so both types of insertions were introduced by addindel.py). I would expect the representation of the insertion in the bam file to be the same on both strands (CTCGCC). This is also the behaviour I see when running mpileup on other bamfiles with real indels (e.g. "+2CG" vs "+2cg" for a CG insertion).

Also, the reversed complementation happens only for insertions and not deletions. 

So is this a bug, or is there some intension behind it?

Thanks!

**Comment by adamewing** [comment]
Sorry about that... good eye! Should be fixed in 461ce5d. Please pull, run `python setup.py install` and re-open if mpileup still doesn't look right.
