### ISSUE TITLE
No output from addindel.py

### ISSUE THREAD

**Issue by padovanas** [adamewing/bamsurgeon#125]
Hi,

I am running addindel.py on a computing cluster and although the install passed the tests, I have not been able to get it to work on my data.

I use:
addindel.py -p 10 -v mutaiton.txt -f sample-sorted.bam -r genome.fa -o sample.bam --picardjar /apps/picard/2.18.2/picard.jar --mindepth 4 --maxdepth 30 --aligner mem --insane

which ends with 

"ERROR 2018-11-02 13:12:06,546 no succesful mutations"

I have tried to troubleshoot this error alone, with the help of google and with the help of my local IT department, and we can't find a solution. Any help in defining this error and possible solutions is much appreciated.

**Comment by adamewing** [comment]
Sorry to hear that. Would you be able to send me the full output either as an attachment in a reply to this message or to adam.ewing@gmail.com? E.g. run:

`addindel.py -p 10 -v mutaiton.txt -f sample-sorted.bam -r genome.fa -o sample.bam --picardjar /apps/picard/2.18.2/picard.jar --mindepth 4 --maxdepth 30 --aligner mem --insane > log.txt 2>&1`

**Comment by adamewing** [comment]
Closing some inactive issues, please re-open if needed.
