### ISSUE TITLE
TypeError raised in addsv.py

### ISSUE THREAD

**Issue by lsantuari** [adamewing/bamsurgeon#128]
Hello, I am getting the following error when running addsv.py:

File addsv.py, line [393](https://github.com/adamewing/bamsurgeon/blob/8e06fe9a75a341d8146a9298809c67ae3c1da67a/bin/addsv.py#L393), in add_donor_reads

TypeError: unsupported operand type(s) for +: 'NoneType' and 'int'

**Comment by adamewing** [comment]
Hm, sorry - how big is the SV you're trying to make?

**Comment by lsantuari** [comment]
I used [randomsites.py](https://github.com/adamewing/bamsurgeon/blob/master/scripts/randomsites.py) to generate 1000 SVs. The maximum SV length is 29993 bp.

On a separate note that might be related to it, I am providing addsv.py the 'cnvs.txt' (-c option) generated by randomsites.py, gzipped and indexed with tabix. However, tabix requires it to be sorted, so I do it.

**Comment by adamewing** [comment]
OK, Is this happening for a subset of DUP mutations or on all of them? Do you still get the error if you omit the -c option?

**Comment by adamewing** [comment]
Hi, apologies for the delay - are you able to narrow this down to an example of a single mutation that fails with this error? If so, could you send me the relevant line from the variant file? Also if you're using a publicly available BAM file and can point me to it that will help.

**Comment by lsantuari** [comment]
I tried to run it with only 10 mutations and it works fine. What is the maximum number of mutations that you have introduced in a BAM file so far?
I am trying to run it with an increasing number of mutations.
I will see if I can pinpoint the mutation that triggers the error.

**Comment by lsantuari** [comment]
Still no insights on why [right_zero](https://github.com/adamewing/bamsurgeon/blob/8e06fe9a75a341d8146a9298809c67ae3c1da67a/bin/addsv.py#L393) is None. Here is an example of a BIGDUP that raises the exception:

INFO 2019-02-06 12:36:02,682 15_28921851_28921851_BIGDUP: TypeError raised from 15-28898270-28921896

It seems independent on the BAM file used. I am working with [this BAM file](ftp://ftp-trace.ncbi.nlm.nih.gov/giab/ftp/data/NA12878/NIST_NA12878_HG001_HiSeq_300x/RMNISTHS_30xdownsample.bam).
