### ISSUE TITLE
Must the input BAM be mate-pair? Can the BAM be pair-end?

### ISSUE THREAD

**Issue by HelloYiHan** [adamewing/bamsurgeon#129]
Dear all,

Figure1b in the manuscript of Bamsurgeon read: _Starting with a high-depth mate-pair BAM alignment,_

I was wondering if I could use pair-end bam files or not.

Thanks

**Comment by adamewing** [comment]
Yes that's probably a misnomer - the typical use case is Illumina paired end .bam files although it could work with either.
