### ISSUE TITLE
OverflowError while running Bamsurgeon

### ISSUE THREAD

**Issue by MicRei** [adamewing/bamsurgeon#130]
Hi there.
I'm trying to create a mutation in a BAM file but I am getting an OverflowError with all my BAM 
files. I get the following output when running bamsurgeon (on all three mutation scripts):

************************************************************
ERROR	2019-04-04 12:28:50.860866	encountered error in mutation spikein: ['chr17_7572842_7572842_None_None']
Traceback (most recent call last):
  File "~/bamsurgeon/bin/addsnv.py", line 248, in makemut
    read.qual = qual
  File "pysam/libcalignedsegment.pyx", line 2675, in pysam.libcalignedsegment.AlignedSegment.qual.__set__
  File "pysam/libcutils.pyx", line 38, in pysam.libcutils.qualitystring_to_array
OverflowError: unsigned byte integer is less than minimum
************************************************************
ERROR 2019-04-04 12:28:50,869 no succesful mutations

I am currently using pysam 0.15.2 but incase it was a pysam error I also tried pysam 0.8.4, which gave the same error message, as well as writing my own script to print out the quality string of the sequence which worked.

Extracting the quality string using pysam gives me the correct quality string but apparently  with not  bamsurgeon . I inserted a print statement in addsnv.py to see the quality string procured by bamsurgeon and it differs from the one procured by pysam in its own script. Used print(read.qual) in both printouts.

Quality string procured by Bamsurgeon:   ���������������p�p�}������~���������������������
Quality string procured by pysam in separate script:
EEEEEEEEEEEE/EEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEAEEEEEEEEEE

The command I'm using with bamsurgeon is the following:
`~/bamsurgeon/bin/addsnv.py -v mychr17snv.bed -r ./fastadocs/hg19.fa -f 17-1143_S26_R_001_nSCLC_NORMAL.molbar.trimmed.deduped.merged.sorted.bam -o addsnv_tester.bam --picard ~/bamsurgeon/picard-tools-1.131/picard.jar -p 30 --maxdepth 10000 --aligner mem` 

All quality strings and sequences before the one producing the error works perfectly though.

I am currently running python 2.7.5 with bamsurgeon and all external prerequisites are installed and working.

Do you have any suggestions or solutions for how to fix this error?

Thanks for your help in advance.

**Comment by adamewing** [comment]
Hmm that's a new one... when you say you've got everything installed and working, are you able to run the tests successfully?

**Comment by MicRei** [comment]
Thanks or the quick response.

All test that fill the external prerequisites (samtools, BCFTools, wgsim, Picard, BWA, Exonerate, Velvet, cython, and pysam) passed without errors.

The tests that failed are those related to other aligners than BWA, as they were not prerequisites.
Three  other tests, not related to aligners. failed; test_snv_haplo.sh andtest_trn.sh, which are missing txt files in the test_data directory, and  and test_snv_avoid.sh which cannot pileup testregion_mut.bam which was created by previous tests.

All other tests (big_sv, sv, snv, indel, *_maxdepth, skipmerge, sv_err, sv_exact, sv_inslib, and *_minmutreads) succeeded without errors but a few warnings.

The warnings that show up are related to samtools mpileup becoming deprecated and in the maxdepth tests which warn that mutations are aborted due to "depth at site is greater than cutoff".

**Comment by adamewing** [comment]
OK the main thing I'm after is that it didn't throw the OverflowError. Does your BAM file contain patient data or data that is sensitive for IP reasons? If not, and if you're able to share a section of it, could you use `samtools view -b` to produce a BAM file with +/-1 kbp around a site that throws this error and send it to me? (adam.ewing@gmail.com)

**Comment by MicRei** [comment]
That sounds great. It's not any sensitive data, so I'll be sending the section to you from my email account (mickaelreinman@hotmail.com) with the issue number as the title.
The specific regions I've identified as problematic are the sequences with the extqname:
CATAGTATTCCCTCCCCTTGCAAGCAAG_molbar_3,7572831,S
and
CCAAGACGCCCATCTCTCTGCAAGCAAG_molbar_3,7572831,S
.

**Comment by MicRei** [comment]
Thank you for your time and trying to help.

I managed to solve the problem this time by aligning my bam file from the fastq files again. Seems to work so far.

**Comment by adamewing** [comment]
Hmm, that's interesting. I haven't able to reproduce the error with the BAM you sent. Re-open if you run into the issue again. Thanks for the update!
