### ISSUE TITLE
Bam surgeon installation error: Not Python3

### ISSUE THREAD

**Issue by yvazirabad** [adamewing/bamsurgeon#131]
This is the same issue as #118, but this has nothing to do with Python3 as in the previous thread.

>**sudo python2 setup.py install**
Traceback (most recent call last):
  File "setup.py", line 89, in <module>
    if not check_bwa(): sys.exit('Dependency problem: bwa >= 0.7.12 not found')
  File "setup.py", line 16, in check_bwa
    p = subprocess.Popen(['bwa'], stderr=subprocess.PIPE)
  File "/usr/lib/python2.7/subprocess.py", line 711, in __init__
    errread, errwrite)
  File "/usr/lib/python2.7/subprocess.py", line 1343, in _execute_child
    raise child_exception
OSError: [Errno 2] No such file or directory
> softgen@hqbreak:~/NGSTools/bamsurgeon-1.2$ which bwa
**/home/softgen/bin/bwa**

BWA runs and is in the bin. Some direction on this would be appreciated.

**Comment by adamewing** [comment]
I seem to have overlooked this, my apologies. Is this still an issue? It looks like something to do with your linux environment.

**Comment by yvazirabad** [comment]
Thanks Adam, I moved to a fresh installation and it was resolved.
