### ISSUE TITLE
No Successful Mutation

### ISSUE THREAD

**Issue by XD-Ye** [adamewing/bamsurgeon#133]
Hi, I was trying to add some snv to my bam file. Here are the error message.

```
************************************************************
INFO 2019-06-12 17:05:20,585 haplo_chr1_248691771_248691771 creating tmp bam: addsnv.tmp/haplo_chr1_248691771_248691771.tmpbam.0107b22b-3ae3-446f-8d5c-53e7f9e72950.bam
************************************************************
ERROR   2019-06-12 17:05:20.589171      encountered error in mutation spikein: ['chr1_248691771_248691771_0.949225317272_None']
Traceback (most recent call last):
  File "/home/XDye/BAMSurgeon/bamsurgeon/bin/addsnv.py", line 162, in makemut
    mutfail, hasSNP, maxfrac, outreads, mutreads, mutmates = mutation.mutate(args, log, bamfile, bammate, chrom, min(mutpos_list), max(mutpos_list)+1, mutpos_list, avoid=avoid, mutid_list=mutid_list, is_snv=True, mutbase_list=mutbase_list, reffile=reffile)
  File "build/bdist.linux-x86_64/egg/bamsurgeon/mutation.py", line 275, in mutate
    assert maxfrac is not None, "Error: could not pile up over region: %s" % region
AssertionError: Error: could not pile up over region: haplo_chr1_248691771_248691772
************************************************************
ERROR 2019-06-12 17:05:20,590 no succesful mutations
```
This is my command:

`time python /home/XDye/BAMSurgeon/bamsurgeon/bin/addsnv.py -v /data/XDye_data/GIAB_BGISEQ/WES/bamsurgeon/snv_var_file.txt -f sample.markdup.chr1.bam -r /data/all_data/ref/hg19/chr1.fa -o sample.markdup.chr1.snv.bam
`
I've also tried different reference.

Here are a few lines of my var file:
chr1	154551811	154551811	0.4591845070357028
chr1	58078047	58078047	0.8899780218111231
chr1	147928404	147928404	0.06065225380164957
chr1	28737131	28737131	0.1950160374043166

I've also tired 
1	154551811	154551811	0.4591845070357028
1	58078047	58078047	0.8899780218111231
1	147928404	147928404	0.06065225380164957
1	28737131	28737131	0.1950160374043166

Can anyone please help me? :///

**Comment by XD-Ye** [comment]
I am using a conda environment with python 2.7

I had trouble with 
`python setup.py build`
and 
`python setup.py install`

So I commented out the check pits in setup.py and build+install, I don't know if that's the reason why.

**Comment by XD-Ye** [comment]
The var file was generated by randomly selecting exon region of chr1 and I wonder if some of the location was not in my read and hence the error. 

Another question unrelated to this, I wonder if there is a way to select site from my input bam file or bed file, currently I am doing it with some python script randomly selecting from the exon bed file.

Cheers,
Drew

**Comment by adamewing** [comment]
Hi, what happens if you run `samtools mpileup sample.markdup.chr1.snv.bam chr1:248691771-248691772`?

**Comment by XD-Ye** [comment]
There is no output file. I've got 2 folder addsnv_logs_sample.markdup.chr1.snv.bam/ and addsnv.tmp/, one is empty, the other one have lots of empty bam files.
I've also got a bam file, addsnv.3747f7db-958d-4c89-8d2c-deb82ae39c41.muts.bam, which is 3kb large with only the header of bam file.

**Comment by adamewing** [comment]
If there was no output that suggests there is no coverage over the region, which is consistent with that error message. You need to specify mutation positions that have coverage in your target .bam file.

**Comment by XD-Ye** [comment]
solved by using docker
