### ISSUE TITLE
Error running test_indel_del_ont.sh

### ISSUE THREAD

**Issue by GodloveD** [adamewing/bamsurgeon#140]
Hi there!  I'm trying to install this package as a [Singularity container](https://github.com/sylabs/singularity) on behalf of a user at the [NIH HPC](https://hpc.nih.gov/).  It is passing the 3 main tests mentioned in the user manual.  But it is failing others.   I'm trying to run `test_indel_del_ont.sh` and I'm getting the following error output.  Does this indicate that I'm missing a dependency or that BAMSurgeon is trying to write to a read-only file system or something else entirely?
```
$ ./test_indel_del_ont.sh $PICARD_JAR
[...snip]
INFO 2019-10-16 17:58:12,974 22_34169764_34169864_1.0:DEL aligning addindel.tmp/22_34169764_34169864_1.0:DEL.tmpbam.fb287e15-a344-4a27-8a0d-acc92bf33c41.fastq with minimap2
************************************************************
encountered error in mutation spikein: 22_34169764_34169864_1.0:DEL
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/bamsurgeon-1.0-py2.7.egg/EGG-INFO/scripts/addindel.py", line 240, in makemut
  File "build/bdist.linux-x86_64/egg/bamsurgeon/aligners.py", line 79, in remap_bam
    remap_mm2_bam(bamfn, threads, fastaref, picardjar, options['x'], mutid=mutid, paired=paired, insane=insane)
  File "build/bdist.linux-x86_64/egg/bamsurgeon/aligners.py", line 257, in remap_mm2_bam
    p = subprocess.Popen(sam_cmd, stdout=subprocess.PIPE)
  File "/usr/lib/python2.7/subprocess.py", line 394, in __init__
    errread, errwrite)
  File "/usr/lib/python2.7/subprocess.py", line 1047, in _execute_child
    raise child_exception
OSError: [Errno 2] No such file or directory
************************************************************
ERROR 2019-10-16 17:58:12,984 no succesful mutations
[E::hts_open_format] Failed to open file ../test_data/testregion_ont_mut.bam
samtools sort: can't open "../test_data/testregion_ont_mut.bam": No such file or directory
samtools index: "../test_data/testregion_ont_mut.bam" is in a format that cannot be usefully indexed
```

**Comment by adamewing** [comment]
This is due to `minimap2` not being in the `$PATH`. This test isn't essential unless you're planning on spiking variants into long-read sequence data (e.g. ONT data). The most relevant tests are:
```
test_snv.sh
test_indel.sh
test_sv.sh
```
So long as these three run you're probably good unless your use case includes an aligner other than `bwa`.

**Comment by GodloveD** [comment]
Thanks.  Are there any other "nice to haves" that I should install?  This is running in a container so if I don't install them the user will not have them.

**Comment by adamewing** [comment]
Ah, bamsurgeon supports the following aligners: bwa (both 'aln' and 'mem' modes), novoalign, gsnap, STAR, bowtie2, tmap, bwakit, and minimap2. The most common among these are probably bwa, bowtie2, novoalign, and minimap2. I've been adding these based on user requests.

**Comment by GodloveD** [comment]
Thank you.
