### ISSUE TITLE
Update dependency checks for openjdk

### ISSUE THREAD

**Issue by GodloveD** [adamewing/bamsurgeon#141]
Unless I'm mistaken, BAMSurgeon and its associated dependencies seem to work just fine with openjdk.  However, the `setup.py` makes some overly constrictive assumptions about the [string returned by the `java -version` command](https://github.com/adamewing/bamsurgeon/blob/master/setup.py#L10).  For instance:
```
$ java -version
openjdk version "11.0.4" 2019-07-16
OpenJDK Runtime Environment (build 11.0.4+11-post-Ubuntu-1ubuntu218.04.3)
OpenJDK 64-Bit Server VM (build 11.0.4+11-post-Ubuntu-1ubuntu218.04.3, mixed mode, sharing)
```
This will prevent BAMSurgeon from installing even though the dependency is satisfied.

**Comment by adamewing** [comment]
Hmm, good point. I haven't tested this with openjdk but changed what is accepted in 86a8f1a.
