### ISSUE TITLE
control picard path with env var

### ISSUE THREAD

**Issue by GodloveD** [adamewing/bamsurgeon#142]
Right now the path to the `picard.jar` file is a CLI option that the user passes at runtime.  This seems a little weird.  And it is actually detrimental in some cases.  For instance, if BAMSurgeon is installed and run from within a container, the user may not reasonably know (or care) where picard is installed in the container or may think the location should point to a picard installation on the host.  

I think it would be better if this could be controlled by an environment variable.  Even better, would be to remove the command line option altogether.  I would propose `BAMSURGEON_PICARD_JAR` as a good env var name.

**Comment by adamewing** [comment]
I agree that this would be a handy feature. In commit 1111e5d I've made a change such that if `BAMSURGEON_PICARD_JAR` is set this will override `--picardjar` for addsnv and addindel. Thanks for the suggestion.

**Comment by GodloveD** [comment]
That is immensely useful for my current application.  Thank you for the speedy changes.
