### ISSUE TITLE
run failure

### ISSUE THREAD

**Issue by fanyucai1** [adamewing/bamsurgeon#144]
hi doctor,I want to try :
chr7	55241708	55241708	0.1	C
chr7	55241707	55241707	0.1	T
but only success one entry "chr7	55241708	55241708	0.1	C"? 

what should I do ?

Thanks.

**Comment by adamewing** [comment]
Hi, try adding the parameter `-x 100` to addsnv.

**Comment by fanyucai1** [comment]
hi doctor,I want to try :
chr7	55241708	55241708	0.1	C
chr7	55241708	55241708	0.1	A
what should I do ?

And I use the version 1.2, I can not find the parameter '-x' ?

Thanks.

**Comment by adamewing** [comment]
Apologies, I meant `-z`, not `-x`. Try setting that to 100 for the first example you gave where the mutations are separated by 1 bp. For the example in your most recent reply those mutations are both referring to the same position which isn't supoprted.

**Comment by adamewing** [comment]
Closing some inactive issues, please re-open if needed.
