### ISSUE TITLE
SNP VAF problem

### ISSUE THREAD

**Issue by kkamii** [adamewing/bamsurgeon#145]
Hi
I have to make bam file having some specific SNPs (VAF==1).
so, I adjusted the 4th column to 1
But it doesn't work properly

show this IGV picture 

![as](https://user-images.githubusercontent.com/41320206/70773491-f3d27500-1dba-11ea-8c7c-9949b13210cf.PNG)

the upper sample's SNPs are my target SNP
and the last bam file is what I maked using bamsurgeon

how can I solve this problem?

**Comment by adamewing** [comment]
Hi, the default settings aren't suited for adding variants close together (i.e. less than one read width apart). Try setting `-z 100` for 100bp reads or `-z 150` for 150 bp reads.

**Comment by adamewing** [comment]
Closing some inactive issues, please re-open if needed.
