### ISSUE TITLE
No successful mutations using mito chr

### ISSUE THREAD

**Issue by TacModd** [adamewing/bamsurgeon#146]
Hi Adam,

I've been trying to simulate mutations in the human mito chromosome. I can get the tools to work on other chromosomes from the same sample, but when I run them on the mito chromosome they error.

For addsv.py:
```
INFO chrM_4070_8070_0.50 best contig length: 191
INFO chrM_4070_8070_0.50 alignment result: ['SUMMARY', '802', '0', '191', '1261', '1452']
INFO chrM_4070_8070_0.50 trimmed contig length: 191
INFO chrM_4070_8070_0.50 start: 4070, end: 8070, tgtstart: 1261, tgtend: 1452, refstart: 5331, refend: 5522
WARNING chrM_4070_8070_0.50 best contig too short to make mutation!
ERROR no succesful mutations
```
For addsnv/addindel.py, if I use a whole genome reference
```
haplo_chrM_4070_4070 dropped for outcover/incover < 0.9
ERROR no succesful mutations
```
For addsnv/addindel.py, if I use a mito only reference (subsetting the sample to just the mito using samtools view first)
```
contig mismatch: chr1
Target and donor are aligned to incompatable reference genomes!
```

I assume the above errors stem form a common source (relating to issues with the reference perhaps? or to filtering of contigs?) but I'm hoping it might be more readily apparent to you. I can post more information if you'd like - any guidance would be greatly appreciated!

**Comment by adamewing** [comment]
That's an interesting use case.

Starting from the bottom, the contig mismatch error means the chromosomes and/or ordering of the chromosomes differs between the reference genome .fasta and the input .bam file. The script in `bamsurgeon/scripts/match_fasta_to_bam.py` might be helpful here if the fasta is a superset of what's in the .bam.

You can try getting around the outcover/incover error by setting `-d` to something low (default is 0.9).

Regarding the addsv error about contigs, that's a trickier one to get around: addsv has to be able to build a useable contig before it can spike-in SVs and it seems to be having a hard time with chrM. I can try it myself and see if there's a way to get it working here. What is the depth like on chrM for this sample?

**Comment by TacModd** [comment]
Okay, went back and made sure chrM was realigned to its own reference before passing it back to bamsurgeon. It does appear to fix the above contig mismatch error (my bad!), but addsv.py still returns a similar error:
```
Estimated Coverage = 1.000000
Estimated Coverage cutoff = 0.500000
Final graph has 1870 nodes and n50 of 68, max 273, total 41580, using 3136/29496 reads
INFO chrM_4070_8080_DEL best contig length: 303
WARNING chrM_4070_8080_DEL alignstats: []
WARNING chrM_4070_8080_DEL No good alignment between mutated contig and original, aborting mutation!
WARNING chrM_4070_8080_DEL best contig did not have sufficent match to reference, aborting mutation.
ERROR no succesful mutations
```

**Comment by adamewing** [comment]
Yep it's not assembling well enough over that region for addsv to work. Is it highly repetitive? What if you try giving it a larger window? e.g. chrM:1070-11080 or something.

**Comment by TacModd** [comment]
Just tried that but unfortunately it hasn't worked either. Also made earlier attempts at smaller large deletions in other regions with no luck, so I'm not inclined to think it's due to the sequence itself. 
```
Estimated Coverage = 1.000000
Estimated Coverage cutoff = 0.500000
Final graph has 4172 nodes and n50 of 61, max 202, total 79522, using 4477/55592 reads
INFO chrM_1070_1070_BIGDEL best contig length: 183
INFO chrM_1070_1070_BIGDEL best transloc contig length: 232
WARNING chrM_1070_1070_BIGDEL alignstats: []
WARNING chrM_1070_1070_BIGDEL No good alignment between mutated contig and original, aborting mutation!
WARNING chrM_1070_1070_BIGDEL best contig did not have sufficent match to reference, aborting mutation.
ERROR no succesful mutations
```

**Comment by TacModd** [comment]
Got round to giving this another go Adam - turns out the read depth I'd been using was closer to 600 and just too high for Velvet to handle effectively. Took it down to below 200 and it worked like a charm.

```
INFO chrM_4070_8080_DEL best contig length: 5000
INFO chrM_4070_8080_DEL alignment result: ['SUMMARY', '19964', '664', '4664', '0', '4000']
INFO chrM_4070_8080_DEL trimmed contig length: 4000
INFO chrM_4070_8080_DEL start: 4075, end: 8075, tgtstart: 0, tgtend: 4000, refstart: 4075, refend: 8075
INFO chrM_4070_8080_DEL action: DEL 0.50 DEL
```

It's a little lower than I would have liked (I don't suppose you have any advice for getting it to work with higher read depths)? But I'd consider this case closed as far as the issue is concerned. Thanks for your help on it :)

**Comment by adamewing** [comment]
Ah, yes that makes sense. Thanks for tracking this down. There may be some tweakable parameters on velvet to look at, will update you if I find a solution.
