### ISSUE TITLE
New BAM generated but No new SNVs and No expected VAF

### ISSUE THREAD

**Issue by marcogao2019** [adamewing/bamsurgeon#149]
Hi Adam,
The expected SNV:  
chr7    55249071        55249071        1.0     T 
Here is the log:
####################
INFO 2020-01-20 14:26:00,614 starting /home/marcogao/.local/bin/addsnv.py called with args: /home/.local/bin/addsnv.py -v test2_EGFR_2369C2T.txt -r /mnt/c/Users/Documents/work/BAM_engineered/ref/genome.fa -f 02601-40-BB_RG_ch7_55248570-55249570_allPaired_more_no206.bam -o test2_pysam140.bam --picard /mnt/c/Users/Documents/work/bin/picard-tools-1.131/picard.jar -d 0 --aligner mem --seed 1234 --insane                                                                                                                                                                                      INFO 2020-01-20 14:26:00,621 created directory: addsnv_logs_test2_pysam140.bam                                                                                                                               INFO 2020-01-20 14:26:00,676 haplo_chr7_55249071_55249071 creating tmp bam: addsnv.tmp/haplo_chr7_55249071_55249071.tmpbam.bfa10b09-0736-4f6d-a5a7-15e559e7081b.bam                                          
INFO 2020-01-20 14:33:55,975 haplo_chr7_55249071_55249071 len(readlist): 1198                                                                                                                                INFO 2020-01-20 14:33:55,976 haplo_chr7_55249071_55249071 selected VAF: 1.000000                                                                                                                             INFO 2020-01-20 14:33:55,977 haplo_chr7_55249071_55249071 picked: 1198                                                                                                                                       INFO 2020-01-20 14:33:56,017 haplo_chr7_55249071_55249071 wrote: 1547, mutated: 1198                                                                                                                         INFO 2020-01-20 14:33:56,033 haplo_chr7_55249071_55249071 converting addsnv.tmp/haplo_chr7_55249071_55249071.tmpbam.bfa10b09-0736-4f6d-a5a7-15e559e7081b.bam to fastq                                        
INFO    2020-01-20 14:33:56.034762      converting BAM addsnv.tmp/haplo_chr7_55249071_55249071.tmpbam.bfa10b09-0736-4f6d-a5a7-15e559e7081b.bam to FASTQ                                                      
[Mon Jan 20 14:33:56 EST 2020] picard.sam.SamToFastq INPUT=addsnv.tmp/haplo_chr7_55249071_55249071.tmpbam.bfa10b09-0736-4f6d-a5a7-15e559e7081b.bam FASTQ=addsnv.tmp/haplo_chr7_55249071_55249071.tmpbam.bfa10b09-0736-4f6d-a5a7-15e559e7081b.fastq INTERLEAVE=true INCLUDE_NON_PRIMARY_ALIGNMENTS=false VALIDATION_STRINGENCY=SILENT    OUTPUT_PER_RG=false RG_TAG=PU RE_REVERSE=true INCLUDE_NON_PF_READS=false READ1_TRIM=0 READ2_TRIM=0 VERBOSITY=INFO QUIET=false COMPRESSION_LEVEL=5 MAX_RECORDS_IN_RAM=500000 CREATE_INDEX=false CREATE_MD5_FILE=false GA4GH_CLIENT_SECRETS=client_secrets.json                                  
[Mon Jan 20 14:33:56 EST 2020] Executing as marcogao@L-DL-4MD7462 on Linux 4.4.0-18362-Microsoft amd64; OpenJDK 64-Bit Server VM 1.8.0_232-8u232-b09-0ubuntu1~16.04.1-b09; Picard version: 1.131(cd60f90fdca902499c70a4472b6162ef37f919ce_1431022382) IntelDeflater                                                                                                                                                       [Mon Jan 20 14:33:56 EST 2020] picard.sam.SamToFastq done. Elapsed time: 0.00 minutes.                                                                                                                       Runtime.totalMemory()=257425408                                                                                                                                                                              To get help, see http://broadinstitute.github.io/picard/index.html#GettingHelp                                                                                                                               Exception in thread "main" java.lang.IllegalArgumentException: Cannot encode phred score: 140                                                                                                                        at htsjdk.samtools.SAMUtils.phredToFastq(SAMUtils.java:364)                                                                                                                                                  at htsjdk.samtools.SAMUtils.phredToFastq(SAMUtils.java:351)                                                                                                                                                  at htsjdk.samtools.SAMUtils.phredToFastq(SAMUtils.java:336)                                                                                                                                                  at htsjdk.samtools.SAMRecord.getBaseQualityString(SAMRecord.java:259)                                                                                                                                        at picard.sam.SamToFastq.writeRecord(SamToFastq.java:285)                                                                                                                                                    at picard.sam.SamToFastq.doWork(SamToFastq.java:184)                                                                                                                                                         at picard.cmdline.CommandLineProgram.instanceMain(CommandLineProgram.java:206)                                                                                                                               at picard.cmdline.PicardCommandLine.instanceMain(PicardCommandLine.java:95)                                                                                                                                  at picard.cmdline.PicardCommandLine.main(PicardCommandLine.java:105)                                                                                                                                 INFO 2020-01-20 14:33:56,505 haplo_chr7_55249071_55249071 aligning addsnv.tmp/haplo_chr7_55249071_55249071.tmpbam.bfa10b09-0736-4f6d-a5a7-15e559e7081b.fastq with bwa mem                                   
[M::bwa_idx_load_from_disk] read 0 ALT contigs                                                                                                                                                               [M::process] read 1 sequences (90 bp)...                                                                                                                                                                     [M::process] 1 single-end sequences; 0 paired-end sequences                                                                                                                                                  [M::mem_process_seqs] Processed 1 reads in 0.000 CPU sec, 0.002 real sec                                                                                                                                     [main] Version: 0.7.17-r1198-dirty                                                                                                                                                                           [main] CMD: bwa mem -t 1 -M -p /mnt/c/Users/Documents/work/BAM_engineered/ref/genome.fa addsnv.tmp/haplo_chr7_55249071_55249071.tmpbam.bfa10b09-0736-4f6d-a5a7-15e559e7081b.fastq                 
[main] Real time: 12.495 sec; CPU: 10.906 sec                                                                                                                                                                INFO 2020-01-20 14:34:09,028 haplo_chr7_55249071_55249071 writing addsnv.tmp/haplo_chr7_55249071_55249071.tmpbam.bfa10b09-0736-4f6d-a5a7-15e559e7081b.bam.realign.sam to BAM...                              
INFO 2020-01-20 14:34:09,086 haplo_chr7_55249071_55249071 deleting SAM: addsnv.tmp/haplo_chr7_55249071_55249071.tmpbam.bfa10b09-0736-4f6d-a5a7-15e559e7081b.bam.realign.sam                                  
INFO 2020-01-20 14:34:09,087 haplo_chr7_55249071_55249071 sorting output: samtools sort -@ 1 -T addsnv.tmp/haplo_chr7_55249071_55249071.tmpbam.bfa10b09-0736-4f6d-a5a7-15e559e7081b.bam.realign.sorted.bam -o addsnv.tmp/haplo_chr7_55249071_55249071.tmpbam.bfa10b09-0736-4f6d-a5a7-15e559e7081b.bam.realign.sorted.bam addsnv.tmp/haplo_chr7_55249071_55249071.tmpbam.bfa10b09-0736-4f6d-a5a7-15e559e7081b.bam          
INFO 2020-01-20 14:34:09,140 haplo_chr7_55249071_55249071 remove original bam: addsnv.tmp/haplo_chr7_55249071_55249071.tmpbam.bfa10b09-0736-4f6d-a5a7-15e559e7081b.bam                                       INFO 2020-01-20 14:34:09,141 haplo_chr7_55249071_55249071 rename sorted bam: addsnv.tmp/haplo_chr7_55249071_55249071.tmpbam.bfa10b09-0736-4f6d-a5a7-15e559e7081b.bam.realign.sorted.bam to original name: addsnv.tmp/haplo_chr7_55249071_55249071.tmpbam.bfa10b09-0736-4f6d-a5a7-15e559e7081b.bam                                                                                                                         INFO 2020-01-20 14:34:09,143 haplo_chr7_55249071_55249071 indexing: samtools index addsnv.tmp/haplo_chr7_55249071_55249071.tmpbam.bfa10b09-0736-4f6d-a5a7-15e559e7081b.bam                                  
INFO 2020-01-20 14:34:09,202 haplo_chr7_55249071_55249071 removing addsnv.tmp/haplo_chr7_55249071_55249071.tmpbam.bfa10b09-0736-4f6d-a5a7-15e559e7081b.fastq                                                 
INFO 2020-01-20 14:34:09,609 haplo_chr7_55249071_55249071 avgincover: 6220.333333, avgoutcover: 0.333333                                                                                                     
INFO 2020-01-20 14:34:09,619 done making mutations, merging mutations into 02601-40-BB_RG_ch7_55248570-55249570_allPaired_more_no206.bam --> test2_pysam140.bam                                              loading donor reads into dictionary...                                                                                                                                                                       secondary reads count:0                                                                                                                                                                                      supplementary reads count:0                                                                                                                                                                                  loaded 1 reads, (0 excluded, 0 null or secondary or supplementary--> ignored)                                                                                                                                replaced 0 reads (0 excluded )                                                                                                                                                                               kept 0 secondary reads.                                                                                                                                                                                      kept 0 supplementary reads.                                                                                                                                                                                  ignored 0 non-primary reads in target BAM.   
############################################

_**Did not see any error but there is no new snvs in output bam, VAF no change.**_

#############################################
addsnv_logs_test2_pysam140.bam/test2_pysam140.bam.haplo_chr7_55249071_55249071.log:

read A00896:6:HLKKYDMXX:1:1146:17219:22232:CTCGATG+GTACACG,55248978,F CCTCCAGGAAGCCTACGTGATGGCCAGCGTGGACAACCCCCACGTGTGCCGCCTGCTGGGCATCTGCCTCACCTCCACCGTGCAGCTCATCAT
read A00896:6:HLKKYDMXX:1:1113:19813:31078:ACATTC+AGAGACG,55248979,S CTCCAGGAAGCCTACGTGATGGCCAGCGTGGACAACCCCCACGTGTGCCGCCTGCTGGGCATCTGCCTCACCTCCACCGTGCAGCTCATCATGC     
''''''
''''''
read A00896:6:HLKKYDMXX:1:1112:14751:23625:GTTCGGA+TTGAACA,55249069,S ATGCAGCTCATGCCCTTCGGCTGCCTCCTGGACTATGTCCGGGAACACAAAGACAATATTGGCTCCCAGTACCTGCTCAACTGGTGTGTGCAG                                          
snv     chr7:55249071-55249071 (VAF=1.0)        55249071        C-->T   6220.33333333   0.333333333333  0.77440206852   0.0
###########################################

Could you give some suggestion about it?
Thanks

**Comment by adamewing** [comment]
There's an error up there in the output:
```
Exception in thread "main" java.lang.IllegalArgumentException: Cannot encode phred score: 140 at htsjdk.samtools.SAMUtils.phredToFastq(SAMUtils.java:364) 
```
Which suggests there's something unusual about the quality scores on the reads, specifically base qualities which are off the scale. Are these Illumina reads?

**Comment by marcogao2019** [comment]
Adam, u r right. I know what the problem is. Thanks
