### ISSUE TITLE
Cellularity simulation

### ISSUE THREAD

**Issue by tgong1** [adamewing/bamsurgeon#153]
Hi Adam,

I'm reading the paper (https://doi.org/10.1186/s13059-018-1539-5) using bamsurgeon for tumour simulation. I'm wondering how the cellularity = 80% simulated in _in silico_ 2 (Fig1d)? Which adds.py parameter is controlling this?
I can't find the information in paper nor Manual.pdf. Hope you can give me some help with that.

Thank you,
Tingting

**Comment by adamewing** [comment]
Hi Tingting,

There is no specific parameter for cellularity, it's just done by manipulating VAFs. You can get 80% cellularity by multiplying all VAFs by 0.8. Hope that helps!

--Adam
