### ISSUE TITLE
Problem with postprocess.py changing read group IDs

### ISSUE THREAD

**Issue by mairenileath** [adamewing/bamsurgeon#156]
Hi Adam,

Firstly, thanks for creating such a great tool! Hope that you're safe and well.

I'm running Bamsurgeon via the NGS-Tools-BAMSurgeon pipeline wrapper. I'm trying to run a germline simulation using the pipeline. 

One of the first steps (see https://st.aticpan.org/source/BOUTROSLB/NGS-Tools-BAMSurgeon-v1.0.0/bin/germline.pl) is to run postprocess.py. It appears this step is changing the read IDs for some reads (and I'm not certain why) without also updating the read IDs that appear in the BAM header.

_samtools view phase.0.bam |grep 'c473f9e6-fb2f-4e09-8897-997f7d722856'
amtools view  phase.0.postprocessed.sorted.bam |grep 'c473f9e6-fb2f-4e09-8897-997f7d722856' |head
HISEQ1:26:HA2RRADXX:1:2101:14286:12081	163	6	60011	0	148M	=	60107	244	AACTGTGAGATTAATCTCAGATAATGACACAAAATATAGTGAAGTTGGTAAGTTATTTAGTAAAGCTCATGAAAATTGTGCCCTCCATTCCCATATAATTTATTAATTGTCTAGGAACTTCCACATACATTGCCTCAATTTATCTTTC	CCCFFDFFHHHHHIJJJJJJJJJJJJJJJJJJJJIJJJJEGIIJIHHJBGHIIJJJJJJJFGIJJJJJJJJJJJJJIJHHIJJJHHHHFFFFFFFEEEFFEEFDFFEEDCDDEDDDDDDDDDDDDDDDDEEDDDDDDDDEDDDDDED>	MD:Z:148	NM:i:0	AS:i:148	XS:i:148	RG:Z:**c473f9e6-fb2f-4e09-8897-997f7d722856**_

Prior to running postprocess.py, this looked like
_HISEQ1:26:HA2RRADXX:1:2101:14286:12081	163	6	60011	0	148M	=	60107	244	AACTGTGAGATTAATCTCAGATAATGACACAAAATATAGTGAAGTTGGTAAGTTATTTAGTAAAGCTCATGAAAATTGTGCCCTCCATTCCCATATAATTTATTAATTGTCTAGGAACTTCCACATACATTGCCTCAATTTATCTTTC	CCCFFDFFHHHHHIJJJJJJJJJJJJJJJJJJJJIJJJJEGIIJIHHJBGHIIJJJJJJJFGIJJJJJJJJJJJJJIJHHIJJJHHHHFFFFFFFEEEFFEEFDFFEEDCDDEDDDDDDDDDDDDDDDDEEDDDDDDDDEDDDDDED>	MD:Z:148	NM:i:0	AS:i:148	XS:i:148	**RG:Z:80f9ec10-60e3-418e-9e43-3025657ce51a**_

The real issue is that later in the germline simulation, you run postprocess.py again but then hit the following error:
_INFO 2020-04-20 16:44:19.624057 no index found, outputting status every 100000 reads.
ERROR:	2020-04-20 16:44:19.625811	read group: c473f9e6fb2f4e09-8897-997f7d722856 not found!
Traceback (most recent call last):
  File "bamsurgeon/build/scripts-2.7/postprocess.py", line 297,
in <module>
    main(args)
  File "bamsurgeon/build/scripts-2.7/postprocess.py", line 258,
in main
    outsam.write(samrec(read, bam, IDRG, newname=newname) + '\n')               # output rea
d
  File "bamsurgeon/build/scripts-2.7/postprocess.py", line 113,
in samrec
   assert tagval in IDRG # make sure readgroup is value (i.e. in the header)
AssertionError_

So why are the read group IDs altered by this script and is there a way to either prevent this or to update the BAM header?

Cheers!

**Comment by adamewing** [comment]
Apologies for the delay and thanks - hope you're well too. It shouldn't be necessary to run the "posrprocess.py" script in most cases - it's there in case .bam validation issues occur which mostly happen with SV spikeins (i.e. addsv.py). I'm not really familiar with the wrapper "NGS-Tools-BAMSurgeon", googling suggests it's the perl wrapper on CPAN. Would it be possible to do what you're trying to do without the wrapper? If not we can go through what it does and find a solution if you're still keen on it.

**Comment by Rapsssito** [comment]
Closed due to inactivity
