### ISSUE TITLE
How is base quality for inserted bases determined?

### ISSUE THREAD

**Issue by danrlu** [adamewing/bamsurgeon#161]
Thanks for such a useful tool! We used bamsurgeon to add mutations and tried to detect them with GATK. I was looking at variant metrics, and noticed the BaseQRankSum 
https://gatk.broadinstitute.org/hc/en-us/articles/360042477772-BaseQualityRankSumTest
indicated the variant sites that were inserted ("2.truth") tended to have higher base quality in ALT bases comparing to REF bases (BaseQRankSum is larger than 0). May I ask how does bamsurgeon assign base quality of inserted bases?  

![image](https://user-images.githubusercontent.com/20667188/84930492-fded6d00-b096-11ea-8629-d99b805186b8.png)

Thanks!

**Comment by adamewing** [comment]
Hi, glad you find it useful. Bamsurgeon (addsnv/addindel) doesn't modify the original quality score, just the appropriate base(s) in the reads overlapping the mutation site are changed but the quality score is not modified from what's in the .bam file. A couple thoughts: are you doing base quality recalibration via GATK? Are you using the same aligner for bamsurgeon as was used on the original .bam file?

**Comment by danrlu** [comment]
Thanks for helping me rule out bamsurgeon. 
We don't do base quality recalibration, and bwa mem was used before and after bamsurgeon. 
I will report back if I get to track this down. 

Thanks!!
