### ISSUE TITLE
TCGA Mutation Calling Benchmark 4 Files

### ISSUE THREAD

**Issue by popicka** [adamewing/bamsurgeon#164]
We are currently working on a project that includes benchmarking of different CNV callers. We would like to use files from the TCGA Mutation Calling Benchmark (https://gdc.cancer.gov/resources-tcga-users/tcga-mutation-calling-benchmark-4-files), but we cannot find these files since all links are broken. We presume that files were moved from GDC.

Since BamSurgeon was used for generating these datasets, could you maybe help us find them?

Thank you

**Comment by adamewing** [comment]
Unfortunately I don't have these files, sorry.
