### ISSUE TITLE
Reads for DEL not being excluded

### ISSUE THREAD

**Issue by pauline-ng** [adamewing/bamsurgeon#171]
Hi,

I'm finding that  BAMSurgeon doesn't exclude any reads when the DEL size is < 5 kb.

When I run `test_sv.sh`  
with the 3.7 kb deletion below as input

22 33881043 33884754 DEL 0.75

BamSurgeon's message
`replaced 505 reads (0 excluded )`:

For larger deletions (BIGDEL), I see reads are being excluded. Is there a way to force reduced read depth for the smaller deletions? 

Many thanks,
Pauline

**Comment by adamewing** [comment]
Hi Pauline,

Yes something seems to have broken, likely during the update to python 3. I've changed things around so the coverage adjustment is now correct in the latest commit (b31f07b). The message you're referring to actually isn't terribly meaningful as reads can be excluded for a number of reasons regardless of whether they're in a deletion region, so I've changed that as well.

Best,
Adam

**Comment by pauline-ng** [comment]
Thanks Adam for the quick response! It appears to work now. 

I am now running into @RichardCorbett 's issue #166 , where the simulated DELs are capped at 2.8 kb.

(Is there anything wrong if I modified my local version of the source code and lowered the BIGDEL threshold to 1 kb?)
