### ISSUE TITLE
addsv error: no successful mutations

### ISSUE THREAD

**Issue by yifnzhao** [adamewing/bamsurgeon#172]
Hi, thanks for developing this software! I would like to use the addsv function to add copy number gain/loss to my samples. I found that somehow addsv works fine with deletions but not duplications. 
For example, here is my command:
```bash
addsv.py \
    -p 1 \
    -l 100 \
    -v mut.txt \
    -f input.X.bam \
    -r $REF \
    -o output.X.bam \
    --aligner mem \
    --keepsecondary \
    --seed 1234
````
And the content of mut.txt is
`X 131975501 146330341 DUP`

Then I got the following error message:
```
WARNING 2021-02-02 16:15:29,737 X 131975501 146330341 DUP is over 10kbp long: converting to use BIGDUP instead.
WARNING 2021-02-02 16:15:29,737 X 131975501 146330341 DUP: using BIGDUP requires specifying a --donorbam and none was provided, using input.X.bam
ERROR 2021-02-02 16:15:29,738 no succesful mutations
```
Different from issue #133, when I run samtools mpileup:
`samtools mpileup input.X.bam -r X:131975501-146330341`, the output is non-empty (it has 13398084 lines). The head of output is:
```
X       131975501       N       2       aA      ??
X       131975502       N       3       gGG     ??5
X       131975503       N       4       cCCC    ??55
X       131975504       N       5       tTTTT   ???55
X       131975505       N       4       cCCC    ???5
X       131975506       N       5       aAAAA   ???5?
X       131975507       N       5       gGGGG   ?????
X       131975508       N       5       gGGGG   5????
X       131975509       N       6       gGGGG^]g        5?????
X       131975510       N       5       TTTTt   ?????
```
When I changed the `DUP` in mut.txt to `DEL`, addsv worked fine. Any help would be much appreciated!

Yifan

**Comment by yifnzhao** [comment]
solved by specifying --donorbam

**Comment by adamewing** [comment]
Ah, yes, it has to get the additional reads from somewhere. Should make bamsurgeon complain more if this isn't specified... I thought the default was to rename input reads and use them but will need to double check that this is working properly now.
