### ISSUE TITLE
addsnv: avgoutcover = 0 and no changes in output bam

### ISSUE THREAD

**Issue by ruoyan-li** [adamewing/bamsurgeon#176]
Hi Adam,

Thanks for the great tool. I'm trying to add some SNVs into a BAM using the following commend line:

"addsnv.py -v spike_in_mut1.v7.txt -f PN8.sort.G.IR.FIX.rmdup.RC.bam -r /hg19.fa -o test.bam --seed 1234 --picardjar picard.jar --force"

![image](https://user-images.githubusercontent.com/59916380/107547545-79230680-6bc5-11eb-97fb-15cb4d2426fa.png)

I noticed there is a error: 'Unexpected end of file', the 'avgoutcover' for each SNV was 0, and 'loaded 0 reads' when writing to output bam. (The input bam was generated through 'bwa aln' and 'GATK IndelRealigner')

I'm not sure why this happened. Do you have any idea?

Many thanks,
Ruoyan

**Comment by adamewing** [comment]
Hi, Are you able to run `test_snv.sh` in the `bamsurgeon/test` directory?

**Comment by ruoyan-li** [comment]
Hi, thanks for the reply. Yes, I am able to run 'test_snv.sh'. Not sure what causes the 'Unexpected end of file', it seems like an error when running 'bwa same'.

**Comment by ruoyan-li** [comment]
Hi Adam, just let you know I solved this by re-indexing (bwa) reference genome fasta. Thanks!

**Comment by adamewing** [comment]
Ah, good to know. Thanks!
