### ISSUE TITLE
Tumor - Matched normal

### ISSUE THREAD

**Issue by jelisavetailic** [adamewing/bamsurgeon#182]
Hi,

I am trying to generate tumor / matched normal pair with BamSuregeon. I have created simulated BAM files with SNPs. Afterwards, I am using BamSurgeon AddSNV and AddSV to generate SNVs and SVs. Finally, I get the tumor file. Howeber, I was wondering how to get matched normal? Can I consider matched normal to be original BAM file (without SNVs and SVs) or matched normal will be generated as output from AddSV workflow (as written in the paper)? How to get that file?

Thank you!

**Comment by adamewing** [comment]
Firstly, if there's any way to not use simulated data, please do that if it's at all possible. If you must simulate, the best way to go about this is to start with a high-coverage .bam file (think > 80x, the more the better), split into two parts (i.e. sub-bams), and spike mutations into one part. The spike-in is then your "tumour" .bam and the untouched part is the "normal" .bam. Just using the before and after spike-in .bams as normal and tumour respectively is problematic as there is no background variability.

**Comment by jelisavetailic** [comment]
Thank you!
