### ISSUE TITLE
Clarification on editing of MNVs

### ISSUE THREAD

**Issue by ijhoskins** [adamewing/bamsurgeon#192]
Hello @adamewing 

I am wondering if  BamSurgeon prohibits simulation of MNVs (codon permutations), such as those found in saturation mutagenesis experiments. Is this possible with add_snv.py provided the right configurations? I understand the need to restrict phasing with true variants, but does this put a global constraint on editing of nearby positions? 

Thanks in advance for any insight!

**Comment by adamewing** [comment]
While this wasn't designed with MNPs in mind, it is possible to mutate consecutive bases by setting `-z` to something > the MNP length.  That said, depending on your use case it might be better to consider read simulation approaches vs something like bamsurgeon if there's going to be a lot of mutations packed together. Given the opportunity I'd like to add MNP support among many other things but really can't afford to attend to bamsurgeon much these days.

**Comment by ijhoskins** [comment]
Hi @adamewing thank you for the prompt response and recommendations. No problem on not supporting this directly.
