### ISSUE TITLE
Dockerfile installation issue

### ISSUE THREAD

**Issue by MaxSalm** [adamewing/bamsurgeon#205]
Hi there.

Thank you for such a useful tool. However, the Dockerfile is not currently building. The key issues are:

1. The Ubuntu version is not supported
2. Velvet is no longer available from https://www.ebi.ac.uk/~zerbino/velvet/velvet_1.2.10.tgz
3. The python bamsurgeon install is not linking to the path for bamsurgeon modules

The following Docker file solves 1 & 2, but bug 3 remains:

```
FROM ubuntu:20.04
MAINTAINER Adam Ewing <adam.ewing@gmail.com>

ENV PATH=$PATH:$HOME/bin

WORKDIR ~/

#install the bareminimum and remove the cache

RUN apt-get update && apt-get install -y --no-install-recommends build-essential

RUN apt-get update && apt-get install -y --no-install-recommends \
    python3 \
    python3-dev \
    python3-numpy \
    python3-scipy \
    python3-pip \
    python3-setuptools \
    python3-wheel \
    zlib1g-dev \
    libbz2-dev \
    git \
    wget \
    libncurses5-dev \
    liblzma-dev \
    pkg-config \
    automake \
    autoconf \
    gcc \
    libglib2.0-dev \
    default-jre \
    samtools \
    bcftools \
    bwa \
    && rm -rf /var/lib/apt/lists/*


RUN mkdir $HOME/bin

RUN git clone https://github.com/dzerbino/velvet.git velvet_1.2.10
RUN make -C velvet_1.2.10
RUN cp velvet_1.2.10/velvetg $HOME/bin && cp velvet_1.2.10/velveth $HOME/bin

# RUN wget https://www.ebi.ac.uk/~zerbino/velvet/velvet_1.2.10.tgz && tar -xvzf velvet_1.2.10.tgz
# RUN make -C velvet_1.2.10
# RUN cp velvet_1.2.10/velvetg $HOME/bin && cp velvet_1.2.10/velveth $HOME/bin

RUN git clone https://github.com/adamewing/exonerate.git
RUN cd exonerate && autoreconf -fi  && ./configure && make && make install

RUN pip3 install cython && pip3 install pysam

RUN git clone https://github.com/adamewing/bamsurgeon.git
RUN export PATH=$PATH:$HOME/bin && cd bamsurgeon && python3 setup.py install

CMD []
```

Upon building the image, and running the container the following error occurs

```
docker run \
-v /:/host/ \
-w "/host/$(pwd)" \
-it bamsurgeon:1.3 addindel.py -v test_data/test_indels.txt -f test_data/testregion_realign.bam -r test_data/Homo_sapiens_chr22_assembly19.fasta -o test_data/testregion_mut.bam --seed 123456

Traceback (most recent call last):
  File "/usr/local/bin/addindel.py", line 4, in <module>
    __import__('pkg_resources').run_script('bamsurgeon==1.3', 'addindel.py')
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 658, in run_script
    self.require(requires)[0].run_script(script_name, ns)
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 1445, in run_script
    exec(script_code, namespace, namespace)
  File "/usr/local/lib/python3.6/dist-packages/bamsurgeon-1.3-py3.6.egg/EGG-INFO/scripts/addindel.py", line 9, in <module>
ModuleNotFoundError: No module named 'bamsurgeon'


```

Do you have any suggestions on how to mend this?

**Comment by Rapsssito** [comment]
@MaxSalm, I have updated the Dockerfile (to match the new standalone script approach). Could you check if it works now?

**Comment by MaxSalm** [comment]
Thank you @Rapsssito. The Dockerfile now builds. However upon testing it with 
`docker run \
-v /:/host/ \
-w "/host/$(pwd)" \
-i bamsurgeon:1.3 addindel.py -v test_data/test_indels.txt -f test_data/testregion_realign.bam -r test_data/Homo_sapiens_chr22_assembly19.fasta -o test_data/testregion_mut.bam --seed 123456

docker run \
-v /:/host/ \
-w "/host/$(pwd)" \
-i bamsurgeon:1.3 addsv.py -p 1 -v test_data/test_sv.txt -f test_data/testregion_realign.bam -r test_data/Homo_sapiens_chr22_assembly19.fasta -o test_data/testregion_sv_mut.bam --aligner mem --keepsecondary --seed 1234 --inslib test_data/test_inslib.fa`

Both tests failed as the executables were not found on the PATH

`container_linux.go:235: starting container process caused "exec: \"addsv.py\": executable file not found in $PATH"
`

**Comment by Rapsssito** [comment]
@MaxSalm, BAMSurgeon does no longer need to be installed. It can now be executed as any other python script:
```
python3 addsv.py ...
```
