### ISSUE TITLE
Release to pull in some new fixes

### ISSUE THREAD

**Issue by apregier** [adamewing/bamsurgeon#211]
Would it be possible to make a new release to pull in some of the newer fixes into a fixed version?  I'm especially interested in the updated dockerfile, as Ubuntu 19.04 in the latest release is no longer supported.

**Comment by adamewing** [comment]
@Rapsssito any objection if I tag the current repo as another version?

**Comment by Rapsssito** [comment]
@adamewing, yeah, no objection!

**Comment by adamewing** [comment]
The current repo is tagged as 1.4 now, if that's all you're after.

**Comment by apregier** [comment]
Perfect, thank you!
