### ISSUE TITLE
error using addsnv.py

### ISSUE THREAD

**Issue by danielecook** [adamewing/bamsurgeon#25]
ERROR	2015-02-02 13:21:00.370856	encountered error in mutation spikein: IV_8282495_8282495_0.5_None
    Traceback (most recent call last):
      File "/bamsurgeon/addsnv.py", line 166, in makemut
        basepile += pread.alignment.seq[pread.qpos-1]
    AttributeError: 'pysam.calignmentfile.PileupRead' object has no attribute 'qpos'

Here is an error I am getting - any idea what might be causing it?

**Comment by adamewing** [comment]
Hm, could you let me know which pysam version you are running?

**Comment by danielecook** [comment]
I think it might - I dug a little further and found that the pread object had a query_position rather than qpos... I'm wondering if that's it. Testing now.

**Comment by adamewing** [comment]
Yes looking at the latest pysam api doc I bet that's not backwards compatible, will update pysam on my end and update bamsurgeon scripts to match if that's the case.

**Comment by danielecook** [comment]
I am using pysam Version: 0.8.1

**Comment by danielecook** [comment]
After replacing fread.qpos with fread.query_position it works up until I get this error:

    error replacing quality score for read: FCC1WMEACXX:1:2316:8398:78658#TCGCAGGA : quality and sequence mismatch: 36 != 90
    donor:  FCC1WMEACXX:1:2316:8398:78658#TCGCAGGA	163	2	7098563	60	46M44S	2	7098647	90	GTGGTGTTAAAAGTCGATCAGCTACGGACGAAGTCCTACAAGTATTGAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA	array('B', [57, 62, 62, 68, 63, 66, 66, 66, 68, 70, 69, 70, 70, 68, 56, 63, 69, 67, 70, 71, 72, 72, 72, 69, 71, 69, 71, 71, 71, 71, 71, 71, 72, 69, 71, 69, 69, 70, 70, 68, 70, 71, 64, 54, 54, 50, 45, 45, 59, 62, 59, 65, 67, 64, 33, 33, 33, 33, 33, 33, 33, 33, 33, 33, 33, 33, 33, 33, 33, 33, 33, 33, 33, 33, 33, 33, 33, 33, 33, 33, 33, 33, 33, 33, 33, 33, 33, 33, 33, 33])	[('NM', 1), ('MD', '14T31'), ('AS', 41), ('XS', 0), ('SA', 'I,9696389,-,10S36M44S,0,0;')]
    target: FCC1WMEACXX:1:2316:8398:78658#TCGCAGGA	2227	0	9696388	0	10H36M44H	2	7098647	36	TTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTCAA	array('B', [33, 33, 33, 33, 33, 33, 33, 33, 33, 33, 33, 33, 33, 33, 33, 33, 33, 33, 33, 33, 33, 33, 33, 33, 33, 33, 64, 67, 65, 59, 62, 59, 45, 45, 50, 54])	[('SA', 'III,7098564,+,46M44S,60,1;'), ('MD', '36'), ('NM', 0), ('AS', 36), ('XS', 35), ('RG', 'BGI2-RET1-N2_CGC'), ('PG', 'MarkDuplicates-A6F510E')]

I'll set up a pull request if you are interested. I can try to resolve this one as well.

**Comment by danielecook** [comment]
Looks like it's trying to replace a donor with a supplementary alignment...
