### ISSUE TITLE
Partial reads

### ISSUE THREAD

**Issue by hzhanghenry** [adamewing/bamsurgeon#27]
Hi, Adam.

BAMSurgeon reported errors as below:
error replacing quality score for read: SRR359108.180851272 : quality and sequence mismatch: 34 != 100

It looks like BAMSurgeon requests all reads having same length.
Is it a feature of BAMSurgeon or just a bug?
Should the bam file be filtered first?

Thank you very much.

Henry

**Comment by adamewing** [comment]
Hi Henry - this occurs when the length of the quality string is different from the length of the sequence for a given read in your BAM file. In this instance you might check on this by isolating reads with the name 'SRR359108.180851272' from the original BAM (e.g. via grep or awk). The length of all input quality scores and read sequences will need to be identical. Let me know if this helps get you running. - Adam

**Comment by hzhanghenry** [comment]
Hi, Adam.

Thank you very much for your reply. I will check out my bam file.
Regards,

Henry

**Comment by trutane** [comment]
This error has occurred for me when running addsnv.py on a BAM file containing the following reads:

```
HISEQ557:352:HTMGLBCXX:2:1113:16380:86381     355     10      21823469        60      39M86H  12      6976630 0       CCGGGCCGGGCGGGGGGCGCCGGGGCGGGCTCGGGGGGC        GGGGGGGIIIIGIIGIIIIIIIIIIIIIIIIIGIIIIGI NM:i:0  MD:Z:39 AS:i:39 XS:i:22 RG:Z:DNA_HCC1187_DUMMYFC03      SA:Z:12,6976587,+,31S94M,60,0;
HISEQ557:352:HTMGLBCXX:2:1113:16380:86381     99      12      6976587 60      31S94M  =       6976630 168     CCGGGCCGGGCGGGGGGCGCCGGGGCGGGCTCGGGGGGCAGGGCTCCGGGGGACTGGGCGGGCCATGGCGGAGGACGGCGAGGAGGCGGAGTTCCACTTCGCGGCGCTCTATATAAGTGGGCAGT  GGGGGGGIIIIGIIGIIIIIIIIIIIIIIIIIGIIIIGIIIIIIIIIIIIIIGIIIIIIIIIIIIIIIIIIGGIGIIIIIGIIGIIGIIIIIIIIIIGIIIGIIIIIIIIIIIIIIIIIIIIIII  NM:i:0  MD:Z:94 AS:i:94 XS:i:19 RG:Z:DNA_HCC1187_DUMMYFC03      SA:Z:10,21823469,+,39M86S,60,0;
HISEQ557:352:HTMGLBCXX:2:1113:16380:86381     147     12      6976630 60      125M    =       6976587 -168    ACGGCGAGGAGGCGGAGTTCCACTTCGCGGCGCTCTATATAAGTGGGCAGTGGCCGCGACTGCGCGCAGACACTGACCTTCAGCGCCTCGGCTCCAGCGCCATGGCGCCCTCCAGGAAGTTCTTC  IIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIGIIIIIIIIGIIIIIGIIIIIIIIGIIIGIIGIIIIIIIIIIIIIIIIIIIIIGIIIIIIIIIIIIIGGIIIIIIIIGGGGG  NM:i:0  MD:Z:125        AS:i:125        XS:i:58 RG:Z:DNA_HCC1187_DUMMYFC03
```

BAMsurgeon's error message:
```
error replacing quality score for read: HISEQ557:352:HTMGLBCXX:2:1113:16380:86381 : quality and sequence mismatch: 39 != 125
donor:  HISEQ557:352:HTMGLBCXX:2:1113:16380:86381       99      11      6976586 29      31S43M51S       11      6976629 43      CCGGGCCGGGCGGGGGGCGCCGGGGCGGGCTCGGGGGGCAGGGCTCCGGGGGACTGGGCGGGCCATGGCGGAGGACGGCGAGGAGGCGGAGTTCCACTTCGCGGCGCTCTATATAAGTGGGCAGT  array('B', [38, 38, 38, 38, 38, 38, 38, 40, 40, 40, 40, 38, 40, 40, 38, 40, 40, 40, 40, 40, 40, 40, 40, 40, 40, 40, 40, 40, 40, 40, 40, 40, 38, 40, 40, 40, 40, 38, 40, 40, 40, 40, 40, 40, 40, 40, 40, 40, 40, 40, 40, 40, 38, 40, 40, 40, 40, 40, 40, 40, 40, 40, 40, 40, 40, 40, 40, 40, 40, 40, 40, 38, 38, 40, 38, 40, 40, 40, 40, 40, 38, 40, 40, 38, 40, 40, 38, 40, 40, 40, 40, 40, 40, 40, 40, 40, 40, 38, 40, 40, 40, 38, 40, 40, 40, 40, 40, 40, 40, 40, 40, 40, 40, 40, 40, 40, 40, 40, 40, 40, 40, 40, 40, 40, 40])     [('XT', 'M'), ('NM', 0), ('SM', 29), ('AM', 29), ('XM', 0), ('XO', 0), ('XG', 0), ('MD', '43')]
target: HISEQ557:352:HTMGLBCXX:2:1113:16380:86381       355     9       21823468        60      39M86H  11      6976629 39      CCGGGCCGGGCGGGGGGCGCCGGGGCGGGCTCGGGGGGC        array('B', [38, 38, 38, 38, 38, 38, 38, 40, 40, 40, 40, 38, 40, 40, 38, 40, 40, 40, 40, 40, 40, 40, 40, 40, 40, 40, 40, 40, 40, 40, 40, 40, 38, 40, 40, 40, 40, 38, 40])       [('NM', 0), ('MD', '39'), ('AS', 39), ('XS', 22), ('RG', 'DNA_HCC1187_DUMMYFC03'), ('SA', '12,6976587,+,31S94M,60,0;')]
```
For the reads listed in the error message, one has seq & quality scores = 125 and the other has seq & quality scores = 39. So they are consistent _within_ each read, but not consistent _across_ the read pair. Perhaps that is an additional constraint for PE sequence data? If so, what's the recommended way to filter out such read pairs prior to running BAMsurgeon? (note that there are **three** reads with that QNAME in my BAM, but BAMsurgeon complained only about two of them)

**Comment by adamewing** [comment]
It _should_ be using the reads with bitfields 99 and 147, 355 means it's not a primary alignment which are ignored. It could be an issue with some more recent changes meant to accommodate alternate alignments from hg38, will get back to you shortly. In the meantime, you could filter out secondary / supplementary alignments using samtools view.
