### ISSUE TITLE
Infinite time when using addsnv.py on single-end IonTorrent data

### ISSUE THREAD

**Issue by tdelhomme** [adamewing/bamsurgeon#31]
I am trying to use bamsurgeon on BAM files generated by our own IonTorrent machine which produces single-end reads, and I get an infinite time execution. 
All the files needed to test this are available here on GitHub : tdelhomme/test_bamsurgeon.
I am trying addsnv.py on a small BAM file (001_fragment.bam), and I would like only one mutation from a T reference to an A (test_var_file1.txt).
This is the command line : 
../bamsurgeon-master/addsnv.py --single -v test_var_file1.txt -f 001_fragment.bam -r references/chr17_torrent.fasta -o test_result.bam

This is the messages I get, and after that the program is running and running with no end : 

INFO	2015-08-24 15:56:10.907789	starting ../bamsurgeon-master/addsnv.py called with args: ../bamsurgeon-master/addsnv.py --single -v test_var_file1.txt -f BAM/001_fragment.bam -r references/chr17_torrent.fasta -o results/test.bam

Debug, haploclusters:[[{'start': 7573000, 'end': 7573001, 'chrom': 'chr17', 'altbase': 'A', 'vaf': 0.2}]]
INFO	2015-08-24 15:56:11.434572	haplo_chr17_7573000_7573000	creating tmp bam:  addsnv.tmp/haplo_chr17_7573000_7573000.tmpbam.b8238288-be60-407a-8577-0923918b57f1.bam
WARN	2015-08-24 15:56:11.791626	haplo_chr17_7573000_7573001	could not pileup for region: chr17:7572794
INFO	2015-08-24 15:56:16.468507	haplo_chr17_7573000_7573001	mpileup failed, no coverage for base: chr17:7572836
WARN	2015-08-24 15:56:16.468885	haplo_chr17_7573000_7573001	could not pileup for region: chr17:7572836
INFO	2015-08-24 15:56:45.990263	haplo_chr17_7573000_7573000	len(readlist): 828
INFO	2015-08-24 15:56:45.993464	haplo_chr17_7573000_7573000	selected VAF: 0.2

INFO	2015-08-24 15:56:45.993591	haplo_chr17_7573000_7573000	picked: 165

Thank you in advance...

**Comment by adamewing** [comment]
Many thanks for the report. The default aligner (bwa aln) probably isn't appropriate for IonTorrent data - is the original BAM aligned with bwa mem, TMAP, or something else?

**Comment by adamewing** [comment]
The latest commit should fix this: (https://github.com/adamewing/bamsurgeon/commit/34da1675113e79a4f842ef4276bfaf6949806dbc). Please note that the merge will not work using the chr17-only reference in your test_bamsurgeon repo - you should use the same reference index used to create the original BAM file.

Your command-line should look like this (alter paths as needed):

../bamsurgeon-master/addsnv.py --single -v test_var_file1.txt -f 001_fragment.bam -r /path/to/tmem_and_samtools_indexed/hg19.fasta -o test_result.bam --picardjar /path/to/picard.jar --aligner tmem

Let me know if this runs successfully.

**Comment by tdelhomme** [comment]
First, many thanks for your quick answer.

Note that I had to add "shell=TRUE" to all subprocess.Popen() lines, before that I had an error like "OSError: [Errno 2] No such file or directory" for  File "/usr/lib/python2.7/subprocess.py". (Sorry, I did not report this before but this change was made before my first message).
Also note that I have to do not use a picard version more recent than 1.131.

This is the new error I get :

************************************************************
ERROR	2015-08-25 11:35:00.891005	encountered error in mutation spikein: ['chr17_7573000_7573001_0.2_A']
Traceback (most recent call last):
  File "../bamsurgeon-master/addsnv.py", line 231, in makemut
    aligners.remap_bam(args.aligner, tmpoutbamname, args.refFasta, alignopts, mutid=hapstr, paired=(not args.single), picardjar=args.picardjar)
  File "/data/delhommet/BAMSurgeon_istumors/bamsurgeon-master/bs/aligners.py", line 70, in remap_bam
    remap_tmap_bam(bamfn, threads, fastaref, picardjar, mutid=mutid, paired=paired)
  File "/data/delhommet/BAMSurgeon_istumors/bamsurgeon-master/bs/aligners.py", line 474, in remap_tmap_bam
    raise ValueError("ERROR\t" + now() + "\t" + mutid + "\tbam readcount < fastq readcount, alignment sanity check failed!\n")
ValueError: ERROR	2015-08-25 11:35:00.890722	haplo_chr17_7573001_7573001	bam readcount < fastq readcount, alignment sanity check failed!

************************************************************
INFO	2015-08-25 11:35:00.910582	no succesful mutations

**Comment by adamewing** [comment]
Not sure why you need the shell=TRUE, what system are you running on? Were you able to get the tests (test/*.sh) to run?

Could  you paste a bit more context from above that error message? Usually that happens when the aligner fails, so it would be helpful to see if the aligner is throwing an error.

**Comment by tdelhomme** [comment]
I tried the tests with shell=TRUE option and yes it worked.
I am working on a linux CentOS5.11.
You can find the whole output I get here on github : tdelhomme/test_bamsurgeon/error_output.txt

**Comment by tdelhomme** [comment]
The problem may be due to different versions of tmap used to 1.generate the original .bam file and 2.provide to bamsurgeon...
I will correct this and will get back to you.

**Comment by adamewing** [comment]
It ran OK on my end but worth a try ... looking at your log file, it seems like tmap is not running. Did you add 'shell=True' to the Popen() lines in bs/aligners.py? (I still can't work out why you seem to need that, but if it works, great.)

**Comment by tdelhomme** [comment]
Ok I removed all "shell=TRUE" I added.
Now this is the new error : 

INFO	2015-08-26 09:07:15.279048	haplo_chr17_7573000_7573000	aligning ['addsnv.tmp/haplo_chr17_7573000_7573000.tmpbam.71b0d948-9762-4e5d-9e84-7135626aa095.fastq'] with tmap

[tmap mapall] running with 1 threads (user set).
[tmap mapall] map4 will be run in stage 1.
[tmap mapall] reading in reference data.

src/io/tmap_file.c:84: in function "tmap_file_fopen"
/appli57/reference/hg19_torrentserver.fasta.tmap.anno
fatal error: could not open the file
the file stream error was: No such file or directory 

That's clear... I will add the tmap index for my reference and try again.

But do you know why I did not see this error when I had "shell=TRUE"?

**Comment by tdelhomme** [comment]
After setting the reference index in the fasta reference folder everything seems to be ok.
Thank you for adapting your code to my data and for your help.

**Comment by adamewing** [comment]
Glad to hear it!
