### ISSUE TITLE
High coverage - alignment sanity check failed

### ISSUE THREAD

**Issue by tdelhomme** [adamewing/bamsurgeon#32]
Dear Adam,

With an high coverage (around 7000), I get this error (not everytime but around 1 time out of 10) : 

---

ERROR   2015-08-31 10:01:45.879129  encountered error in mutation spikein: ['chr17_7573000_7573000_0.2_A']
Traceback (most recent call last):
  File "../bamsurgeon-master/addsnv.py", line 231, in makemut
    aligners.remap_bam(args.aligner, tmpoutbamname, args.refFasta, alignopts, mutid=hapstr, paired=(not args.single), picardjar=args.picardjar)
  File "/home/delhommet/Documents/Softs/bamsurgeon/bamsurgeon-master/bs/aligners.py", line 70, in remap_bam
    remap_tmap_bam(bamfn, threads, fastaref, picardjar, mutid=mutid, paired=paired)
  File "/home/delhommet/Documents/Softs/bamsurgeon/bamsurgeon-master/bs/aligners.py", line 476, in remap_tmap_bam
    raise ValueError("ERROR\t" + now() + "\t" + mutid + "\tbam readcount < fastq readcount, alignment sanity check failed!\n")
ValueError: ERROR   2015-08-31 10:01:45.879037  haplo_chr17_7573000_7573000 bam readcount < fastq readcount, alignment sanity check failed!

---

I think this is in the case where some reads after being mutated can not be aligned (I check the number of aligned reads after and before alignment with samtools idxstats and this shows that (fastq readcount - bamfn readcount) = unmapped readcount in the final bam).
Do you think I'm right? Is it possible to just have a warning in this case?
The data I used can be found here : https://github.com/tdelhomme/test_bamsurgeon (001tmapAligned_options_sorted.*) in additon to the whole error output (error_output.txt).

**Comment by adamewing** [comment]
bs.common.bamreadcount should count mapped + unmapped so probably something else is happening here, will look into it asap.

**Comment by Alyssameng** [comment]
Hi, did you know why BAMSurgeon gives this error report? Could you please tell me how to fix it?

**Comment by adamewing** [comment]
Workaround in 310dbbf: `--insane` option.
