### ISSUE TITLE
tmap realignement - NOID read group not in the header

### ISSUE THREAD

**Issue by tdelhomme** [adamewing/bamsurgeon#33]
Dear Adam,

I am trying to use MuTect to perform variant calling on IonTorrent data mutated with bamsurgeon.
I've just checked that the final bamsurgeon bam file does not contain in the header the "NOID" read group from tmap realignement, and MuTect doesn't like this.
To fix this problem I add a posteriori a new read group line in the final bam file header (you can see my commands here https://github.com/IARC-bioinfo/BAM-tricks). 
Do you see any other solution?
Does this problem arise with the other aligners?

**Comment by adamewing** [comment]
It should be possible to incorporate a fix to add the appropriate read group info for TMAP alignments, will do ASAP (overseas at the moment) but if you want to pull request that's even better!

Other aligners generate GATK/MuTect passable RG info as recently as I'm aware but will double check.

**Comment by adamewing** [comment]
Cleaning up old open issues, please re-open if still an active issue.
