### ISSUE TITLE
AttributeError: 'csamtools.PileupRead' object has no attribute 'query_position'

### ISSUE THREAD

**Issue by rhalperin** [adamewing/bamsurgeon#34]
I am getting the an error running bamsurgeon (see below).  Please let me know if you need any more information.  Thanks in advance for your help!

$ INFO	2015-10-09 15:27:31.643881	starting /packages/bamsurgeon/addsnv.py called with args: /packages/bamsurgeon/addsnv.py -v randStrexomePos.txt -f Control.bwa.final.bam -r hs37d5.fa -o output.bam -m 0.25

Debug, haploclusters:[[{'start': 1133208, 'end': 1133208, 'chrom': '1', 'altbase': None, 'vaf': 0.25}]]
INFO	2015-10-09 15:27:31.749428	haplo_1_1133208_1133208	creating tmp bam:  addsnv.tmp/haplo_1_1133208_1133208.tmpbam.ea057829-9464-4363-8fde-72e8ef7eea39.bam
************************************************************
ERROR	2015-10-09 15:27:31.756894	encountered error in mutation spikein: ['1_1133208_1133208_0.25_None']
Traceback (most recent call last):
  File "/packages/bamsurgeon/addsnv.py", line 155, in makemut
    mutfail, hasSNP, maxfrac, outreads, mutreads, mutmates = mutation.mutate(args, log, bamfile, bammate, chrom, min(mutpos_list), max(mutpos_list)+1, mutpos_list, avoid=avoid, mutid_list=mutid_list, is_snv=True, mutbase_list=mutbase_list, reffile=reffile)
  File "/packages/bamsurgeon/bs/mutation.py", line 141, in mutate
    if pread.query_position is not None and not pread.alignment.is_secondary and bin(pread.alignment.flag & 2048) != bin(2048):
AttributeError: 'csamtools.PileupRead' object has no attribute 'query_position'
************************************************************
INFO	2015-10-09 15:27:31.770180	no succesful mutations

**Comment by adamewing** [comment]
Have a look at your pysam version:

python -c "import pysam; print pysam.__version__"

If it's below 0.8 you'll need to update to the latest (pip install -U pysam)

**Comment by rhalperin** [comment]
Hello Adam,

Thanks for your suggestions.  However, we have installed Pysam-0.8.3 and I am still getting the same error.  What version of Python do you recommend using with bamsurgeon?  Do you have any other ideas about what might cause this error?

Thanks,
Rebecca

________________________________
________________________________

This electronic message is intended to be for the use only of the named recipient, and may contain information that is confidential or privileged, including patient health information. If you are not the intended recipient, you are hereby notified that any disclosure, copying, distribution or use of the contents of this message is strictly prohibited. If you have received this message in error or are not the named recipient, please notify us immediately by contacting the sender at the electronic mail address noted above, and delete and destroy all copies of this message. Thank you.

**Comment by adamewing** [comment]
Hi Rebecca,

That's odd as I know this specific error is caused by older version of pysam - newer versions have the PileupRead.query_position attribute (see API: https://pysam.readthedocs.org/en/latest/api.html#pysam.PileupRead) ... could you double check that the python pointed to by /usr/bin/env python is the same one that uses the updated pysam module? i.e. check that the following two commands produce the same output:

python -c "import pysam; print pysam.__version__"

/usr/bin/env python -c "import pysam; print pysam.__version__"

Let me know how that goes.

-Adam

**Comment by rhalperin** [comment]
Hi Adam,

I am getting help from Dustin in our HPC group to install bamsurgeon as a module on one of our clusters.  From his email below, it looks like we do have python pointed to the updated pysam module.  Can you think of any other reason we might be getting this error?

Thanks so much for your help.

Rebecca

________________________________
________________________________

This electronic message is intended to be for the use only of the named recipient, and may contain information that is confidential or privileged, including patient health information. If you are not the intended recipient, you are hereby notified that any disclosure, copying, distribution or use of the contents of this message is strictly prohibited. If you have received this message in error or are not the named recipient, please notify us immediately by contacting the sender at the electronic mail address noted above, and delete and destroy all copies of this message. Thank you.

From: Dustin Ashton <dashton@tgen.org<mailto:dashton@tgen.org>>
Date: Thursday, October 22, 2015 at 10:03 AM
To: TGen TGen <rhalperin@tgen.org<mailto:rhalperin@tgen.org>>
Subject: RE: [bamsurgeon] AttributeError: 'csamtools.PileupRead' object has no attribute 'query_position' (#34)

Here’s the output from the two commands that he suggested we run:

# python -c "import pysam; print pysam.version"
<module 'pysam.version' from '/packages/python/python-2.7.3/lib/python2.7/site-packages/RSeQC-2.3.6-py2.7-linux-x86_64.egg/pysam/version.pyc'>

# /usr/bin/env python -c "import pysam; print pysam.version"
<module 'pysam.version' from '/packages/python/python-2.7.3/lib/python2.7/site-packages/RSeQC-2.3.6-py2.7-linux-x86_64.egg/pysam/version.pyc'>

We run Modules however in our environment so python is installed in a specified directory and not the default in /usr/bin. But this shouldn’t matter too much as both commands output the same information.

I’d also include the update command results I ran as well just to give Adam all of the information:

“pip install –U pysam” as he suggested:

“Requirement already up-to-date: pysam in /packages/python/python-2.7.3/lib/python2.7/site-packages/pysam-0.8.3-py2.7-linux-x86_64.egg”

Thanks,

Dustin Ashton
TGen
HPC Engineer
X8538

________________________________

This electronic message is intended to be for the use only of the named recipient, and may contain information that is confidential or privileged, including patient health information. If you are not the intended recipient, you are hereby notified that any disclosure, copying, distribution or use of the contents of this message is strictly prohibited. If you have received this message in error or are not the named recipient, please notify us immediately by contacting the sender at the electronic mail address noted above, and delete and destroy all copies of this message. Thank you.
From: Rebecca Halperin
Sent: Thursday, October 22, 2015 9:26 AM
To: Dustin Ashton <dashton@tgen.org<mailto:dashton@tgen.org>>
Subject: FW: [bamsurgeon] AttributeError: 'csamtools.PileupRead' object has no attribute 'query_position' (#34)

Hi Dustin,

I got a response from the author.  He still thinks we must not have the right version of pysam (see below).

Rebecca

________________________________

This electronic message is intended to be for the use only of the named recipient, and may contain information that is confidential or privileged, including patient health information. If you are not the intended recipient, you are hereby notified that any disclosure, copying, distribution or use of the contents of this message is strictly prohibited. If you have received this message in error or are not the named recipient, please notify us immediately by contacting the sender at the electronic mail address noted above, and delete and destroy all copies of this message. Thank you.

**Comment by rhalperin** [comment]
Hi Adam,

I am really interested in running bamsurgeon to evaluate a variant caller that I am developing.  I just wanted to follow up with you and see if you had any additional thoughts on why we might be getting this error.  We noticed that Python 2.7 is “untested” with Pysam, but some of the other modules such as Counter are only available in Python 2.7.  What version of Python do you recommend using with bamsurgeon?

Thanks,
Rebecca

________________________________
________________________________

This electronic message is intended to be for the use only of the named recipient, and may contain information that is confidential or privileged, including patient health information. If you are not the intended recipient, you are hereby notified that any disclosure, copying, distribution or use of the contents of this message is strictly prohibited. If you have received this message in error or are not the named recipient, please notify us immediately by contacting the sender at the electronic mail address noted above, and delete and destroy all copies of this message. Thank you.

From: TGen TGen <rhalperin@tgen.org<mailto:rhalperin@tgen.org>>
Date: Thursday, October 22, 2015 at 10:15 AM
To: adamewing/bamsurgeon <reply@reply.github.com<mailto:reply@reply.github.com>>
Cc: Dustin Ashton <dashton@tgen.org<mailto:dashton@tgen.org>>
Subject: FW: [bamsurgeon] AttributeError: 'csamtools.PileupRead' object has no attribute 'query_position' (#34)

Hi Adam,

I am getting help from Dustin in our HPC group to install bamsurgeon as a module on one of our clusters.  From his email below, it looks like we do have python pointed to the updated pysam module.  Can you think of any other reason we might be getting this error?

Thanks so much for your help.

Rebecca

From: Dustin Ashton <dashton@tgen.org<mailto:dashton@tgen.org>>
Date: Thursday, October 22, 2015 at 10:03 AM
To: TGen TGen <rhalperin@tgen.org<mailto:rhalperin@tgen.org>>
Subject: RE: [bamsurgeon] AttributeError: 'csamtools.PileupRead' object has no attribute 'query_position' (#34)

Here’s the output from the two commands that he suggested we run:

# python -c "import pysam; print pysam.version"
<module 'pysam.version' from '/packages/python/python-2.7.3/lib/python2.7/site-packages/RSeQC-2.3.6-py2.7-linux-x86_64.egg/pysam/version.pyc'>

# /usr/bin/env python -c "import pysam; print pysam.version"
<module 'pysam.version' from '/packages/python/python-2.7.3/lib/python2.7/site-packages/RSeQC-2.3.6-py2.7-linux-x86_64.egg/pysam/version.pyc'>

We run Modules however in our environment so python is installed in a specified directory and not the default in /usr/bin. But this shouldn’t matter too much as both commands output the same information.

I’d also include the update command results I ran as well just to give Adam all of the information:

“pip install –U pysam” as he suggested:

“Requirement already up-to-date: pysam in /packages/python/python-2.7.3/lib/python2.7/site-packages/pysam-0.8.3-py2.7-linux-x86_64.egg”

Thanks,

Dustin Ashton
TGen
HPC Engineer
X8538

________________________________

This electronic message is intended to be for the use only of the named recipient, and may contain information that is confidential or privileged, including patient health information. If you are not the intended recipient, you are hereby notified that any disclosure, copying, distribution or use of the contents of this message is strictly prohibited. If you have received this message in error or are not the named recipient, please notify us immediately by contacting the sender at the electronic mail address noted above, and delete and destroy all copies of this message. Thank you.
From: Rebecca Halperin
Sent: Thursday, October 22, 2015 9:26 AM
To: Dustin Ashton <dashton@tgen.org<mailto:dashton@tgen.org>>
Subject: FW: [bamsurgeon] AttributeError: 'csamtools.PileupRead' object has no attribute 'query_position' (#34)

Hi Dustin,

I got a response from the author.  He still thinks we must not have the right version of pysam (see below).

Rebecca

________________________________

This electronic message is intended to be for the use only of the named recipient, and may contain information that is confidential or privileged, including patient health information. If you are not the intended recipient, you are hereby notified that any disclosure, copying, distribution or use of the contents of this message is strictly prohibited. If you have received this message in error or are not the named recipient, please notify us immediately by contacting the sender at the electronic mail address noted above, and delete and destroy all copies of this message. Thank you.

**Comment by adamewing** [comment]
In my hands, anything python 2.7+ will work (not python 3 though). Maybe try installing via anaconda: https://www.continuum.io/downloads ... I'm a bit mystified as to why PileupRead objects don't have the query_position attribute if you have an up-to-date version of pysam ... what is the actual version? Can you please let me know the output of the following command:

```
/usr/bin/env python -c "import pysam; print pysam.version"
```
