### ISSUE TITLE
Exonerate has moved

### ISSUE THREAD

**Issue by jasper1918** [adamewing/bamsurgeon#36]
Adam,

Thanks for this awesome tool.

I noticed the path you have for exonerate on the readme and elsewhere is incorrect.

I was able to download from here if you want to update.
http://www.ebi.ac.uk/sites/ebi.ac.uk/files/groups/flicek/exonerate/exonerate-2.2.0-x86_64.tar.gz

**Comment by adamewing** [comment]
Thanks, it's also available at https://github.com/nathanweeks/exonerate and I've forked it here: https://github.com/adamewing/exonerate. I've updated the readme and the manual to reflect this.
