### ISSUE TITLE
When to use addindel versus addsv?

### ISSUE THREAD

**Issue by jjfarrell** [adamewing/bamsurgeon#38]
At what size of a deletion/insertion should the addsv.py be used instead of addindel.py?

**Comment by adamewing** [comment]
Indel length for addindel.py is currently capped at the length of the reads minus 2. So currently to go beyond that you'll need to use addsv.py.

**Comment by jjfarrell** [comment]
Will addsv.py also handle the indels less than read length+2?  In other words, Does addsv.py handle the full range of SV sizes including small indels? Or is it best to use both programs on two different ranges?

**Comment by adamewing** [comment]
addsv will handle it but not as precisely: for addsv you need to specify a region large enough for local assembly to work - then for insertions you could have it insert a single base... for deletions it's not as fine-grained. In general the local assembly --> alter contig --> generate reads approach taken by addsv will not be as realistic as what addindel does (altering the actual reads) so I guess I would recommend using addindel for small events and addsv beyond that.
