### ISSUE TITLE
realignment problem with BWAMEM

### ISSUE THREAD

**Issue by lijingya** [adamewing/bamsurgeon#39]
Try to run the test (test_snv_bwamem.sh), resulting following error message:
Command:

../test/test_snv_bwamem.sh 1 1 /net/kodiak/volumes/river/shared/users/ltfang/link_to_reference/human_g1k_v37_decoy.fasta /home/yaol12/opt/picard-tools-1.130/picard.jar

Logs:

INFO    2015-11-17 14:37:49.936238      starting /home/yaol12/river/software/PythonLibs/bamsurgeon/bin/addsnv.py called with args: /home/yaol12/river/software/PythonLibs/bamsurgeon/bin/addsnv.py -v ../test_data/random_snvs.txt -f ../test_data/testregion.bam -r /net/kodiak/volumes/river/shared/users/ltfang/link_to_reference/human_g1k_v37_decoy.fasta -o ../test_data/testregion_mut.bam -n 1 -c ../test_data/test_cnvlist.txt.gz -p 1 --picardjar /home/yaol12/opt/picard-tools-1.130/picard.jar --aligner mem

Debug, haploclusters:[[{'start': 34166720, 'end': 34166721, 'chrom': '22', 'altbase': None, 'vaf': 1.0}]]
INFO    2015-11-17 14:37:49.991232      haplo_22_34166721_34166721      creating tmp bam:  addsnv.tmp/haplo_22_34166721_34166721.tmpbam.e50b82c5-5bca-4047-846a-bc5df9a950fc.bam
INFO    2015-11-17 14:37:51.910871      haplo_22_34166721_34166721      len(readlist): 58
INFO    2015-11-17 14:37:51.911185      haplo_22_34166721_34166721      copy number in snp region: 22 34166721 34166721 = 3.0

adjusted VAF: 0.333333333333

INFO    2015-11-17 14:37:51.911363      haplo_22_34166721_34166721      picked: 19
INFO    2015-11-17 14:37:51.912878      haplo_22_34166721_34166721      wrote:  58 mutated: 19
INFO    2015-11-17 14:37:51.928637      haplo_22_34166721_34166721      converting addsnv.tmp/haplo_22_34166721_34166721.tmpbam.e50b82c5-5bca-4047-846a-bc5df9a950fc.bam to fastq

INFO    2015-11-17 14:37:51.929061      converting BAM addsnv.tmp/haplo_22_34166721_34166721.tmpbam.e50b82c5-5bca-4047-846a-bc5df9a950fc.bam to FASTQ
[Tue Nov 17 14:37:52 PST 2015] picard.sam.SamToFastq INPUT=addsnv.tmp/haplo_22_34166721_34166721.tmpbam.e50b82c5-5bca-4047-846a-bc5df9a950fc.bam FASTQ=addsnv.tmp/haplo_22_34166721_34166721.tmpbam.e50b82c5-5bca-4047-846a-bc5df9a950fc.fastq INTERLEAVE=true INCLUDE_NON_PRIMARY_ALIGNMENTS=false VALIDATION_STRINGENCY=SILENT    OUTPUT_PER_RG=false RG_TAG=PU RE_REVERSE=true INCLUDE_NON_PF_READS=false READ1_TRIM=0 READ2_TRIM=0 VERBOSITY=INFO QUIET=false COMPRESSION_LEVEL=5 MAX_RECORDS_IN_RAM=500000 CREATE_INDEX=false CREATE_MD5_FILE=false
[Tue Nov 17 14:37:52 PST 2015] Executing as yaol12@tehran-11 on Linux 3.2.0-4-amd64 amd64; OpenJDK 64-Bit Server VM 1.7.0_79-b14; Picard version: 1.130(8b3e8abe25f920f5aa569db482bb999f29cc447b_1427207353) IntelDeflater
[Tue Nov 17 14:37:52 PST 2015] picard.sam.SamToFastq done. Elapsed time: 0.00 minutes.
Runtime.totalMemory()=1521483776
INFO    2015-11-17 14:37:52.499853      haplo_22_34166721_34166721      aligning addsnv.tmp/haplo_22_34166721_34166721.tmpbam.e50b82c5-5bca-4047-846a-bc5df9a950fc.fastq with bwa mem

[main] unrecognized command 'mem'
INFO    2015-11-17 14:37:52.528034      haplo_22_34166721_34166721      writing addsnv.tmp/haplo_22_34166721_34166721.tmpbam.e50b82c5-5bca-4047-846a-bc5df9a950fc.bam.realign.sam to BAM...
INFO    2015-11-17 14:37:52.553217      haplo_22_34166721_34166721      deleting SAM: addsnv.tmp/haplo_22_34166721_34166721.tmpbam.e50b82c5-5bca-4047-846a-bc5df9a950fc.bam.realign.sam
INFO    2015-11-17 14:37:52.572843      haplo_22_34166721_34166721      sorting output: samtools sort -@ 1 -m 10000000000 addsnv.tmp/haplo_22_34166721_34166721.tmpbam.e50b82c5-5bca-4047-846a-bc5df9a950fc.bam addsnv.tmp/haplo_22_34166721_34166721.tmpbam.e50b82c5-5bca-4047-846a-bc5df9a950fc.bam.realign.sorted
INFO    2015-11-17 14:37:52.595364      haplo_22_34166721_34166721      remove original bam:addsnv.tmp/haplo_22_34166721_34166721.tmpbam.e50b82c5-5bca-4047-846a-bc5df9a950fc.bam
INFO    2015-11-17 14:37:52.611344      haplo_22_34166721_34166721      rename sorted bam: addsnv.tmp/haplo_22_34166721_34166721.tmpbam.e50b82c5-5bca-4047-846a-bc5df9a950fc.bam.realign.sorted.bam to original name: addsnv.tmp/haplo_22_34166721_34166721.tmpbam.e50b82c5-5bca-4047-846a-bc5df9a950fc.bam
INFO    2015-11-17 14:37:52.619693      haplo_22_34166721_34166721      indexing: samtools index addsnv.tmp/haplo_22_34166721_34166721.tmpbam.e50b82c5-5bca-4047-846a-bc5df9a950fc.bam
************************************************************
ERROR   2015-11-17 14:37:52.645301      encountered error in mutation spikein: ['22_34166720_34166721_1.0_None']
Traceback (most recent call last):
  File "/home/yaol12/river/software/PythonLibs/bamsurgeon/bin/addsnv.py", line 258, in makemut
    aligners.remap_bam(args.aligner, tmpoutbamname, args.refFasta, alignopts, mutid=hapstr, paired=(not args.single), picardjar=args.picardjar)
  File "build/bdist.linux-x86_64/egg/bamsurgeon/aligners.py", line 58, in remap_bam
    remap_bwamem_bam(bamfn, threads, fastaref, picardjar, mutid=mutid, paired=paired)
  File "build/bdist.linux-x86_64/egg/bamsurgeon/aligners.py", line 199, in remap_bwamem_bam
    raise ValueError("ERROR\t" + now() + "\t" + mutid + "\tbam readcount < fastq readcount, alignment sanity check failed!\n")
ValueError: ERROR       2015-11-17 14:37:52.645257      haplo_22_34166721_34166721      bam readcount < fastq readcount, alignment sanity check failed!

************************************************************
INFO    2015-11-17 14:37:52.677268      no succesful mutations
[main] Unrecognized command.
[mpileup] 1 samples in 1 input files

**Comment by lijingya** [comment]
I update the bwa. The problem solved.

**Comment by adamewing** [comment]
Thanks for the report, good to know!
