### ISSUE TITLE
structural variants are not simulated exactly as input

### ISSUE THREAD

**Issue by amcpherson** [adamewing/bamsurgeon#4]
SVs appear to simulated only approximately, usually within a 500-1000bp of the input regions.  It would be nice if this were fixed.  However, since this appears to be as designed rather than a bug, as a less preferable alternative it would be nice to have an output of the actual sv locations that were simulated.

**Comment by adamewing** [comment]
Fixed (or as close as it's going to get) in 4243560 with `--require_exact`
