### ISSUE TITLE
add SNVs on close locations failed

### ISSUE THREAD

**Issue by tdelhomme** [adamewing/bamsurgeon#40]
Hello,
I try to add two SNVs on a bam file (IonTorrent data).
The varfile looks like the following : 
```
chr17	7577552	7577552	0.2722953	A
chr17	7577590	7577590	0.0521716	A
```
NB : the distance between the two SNVs is < 100pb so probably we have overlapping reads.
The problem is : at the end, 0.05 VAF is respected, 0.27 is not. If we do the steps independently, it works. I also noticed that intermediate merged mutbam respects the two VAFs. After some researches, I am convinced the failed step is `ReplaceReads` but I still don't understand why...   

[Here](https://github.com/tdelhomme/test_bamsurgeon) is a link where you can find my files (`MLT019SK_2*`). The command line I used is : 
`addsnv.py -f MLT019SK_2.bam -v MLT019SK_2.var -r hg19.fasta -o MLT019SK_2_mut.bam --maxdepth 150000 --picardjar picard.jar --aligner tmap --single`

Thank you in avance!

**Comment by tdelhomme** [comment]
Also I commented the line `474` in `aligners.py` (close counts, just a 1-2 reads difference): 
```
 # raise ValueError("ERROR\t" + now() + "\t" + mutid + "\tbam readcount < fastq readcount, alignment sanity check failed!\n")
```

**Comment by adamewing** [comment]
Hi, currently if two mutations are close enough to each other to share reads, the VAF of the first variant in the set of variants sharing reads will be used. This is currently the expected behaviour, but will hopefully have a better solution in the future.

**Comment by tdelhomme** [comment]
ok, many thanks Adam!
This is the way I used to run sequentially each mutation from the varfile : 
```
#!/bin/bash
first_in_bam='MLT019SK_2.bam' 
varfile='MLT019SK_2.var'
while read var_line; do
	if [ ! -f test_out_sort.bam ]; then
		bam_in=$first_in_bam
	else
		bam_in=test_out_sort.bam
	fi
	echo $var_line > one_vaf.var
	./addsnv.py -f $bam_in -v one_vaf.var -r hg19.fasta -o test_out.bam --picardjar picard.jar --aligner tmap --single
	samtools sort test_out.bam test_out_sort
	samtools index test_out_sort.bam
    rm test_out.bam
done < ${varfile}
mv test_out_sort.bam MLT019SK_2_mut.bam
```
With this we can have two mutations on the same read with distinct VAFs.
Cheers.
