### ISSUE TITLE
How to use autoreconf without root permission

### ISSUE THREAD

**Issue by aistrand** [adamewing/bamsurgeon#48]
Hi,

I am having trouble using autoreconf without having root permission. When I try doing autoreconf -i when installing exonerate, I get "Permission denied". What should I do to resolve this issue?

Thanks,
Alva

**Comment by adamewing** [comment]
Hi Alva - First, I'd try building without running autoconf, it shouldn't be required but it seems to help on some systems. Also check the permissions on the directory where you're running the command, is it possible your user account doesn't have write permission in that directory?

--Adam

**Comment by aistrand** [comment]
I got the following error after doing make:
CDPATH="${ZSH_VERSION+.}:" && cd . && aclocal 
autom4te: cannot create /ifs/data/c2b2/gs_lab/shared/tmp//am4t1612.44242: Permission denied
 at /usr/bin/autom4te line 958
aclocal: autom4te failed with exit status: 13
make: *** [aclocal.m4] Error 13
How do I run this without root permission?

**Comment by adamewing** [comment]
Normally this doesn't require root permissions, it seems like a systems configuration difference on your end. Specifically, it looks like you can't write to a tmp folder:
```
autom4te: cannot create /ifs/data/c2b2/gs_lab/shared/tmp//am4t1612.44242: Permission denied
```
My guess is this tmp dir is coming from $TMPDIR so try setting it somewhere you have write permission, e.g.:

export TMPDIR=/tmp

and see if that helps.

**Comment by aistrand** [comment]
I think I was able to install exonerate successfully. It's now in a new tmp directory I created; as long as it's in my path, I should be able to use exonerate properly, correct?

**Comment by adamewing** [comment]
Great, yes, as long as the 'exonerate' executable is somewhere in your path you should be fine.
