### ISSUE TITLE
Default VAF vs. specifying VAF in BED file

### ISSUE THREAD

**Issue by aistrand** [adamewing/bamsurgeon#49]
Hi Adam,

I know I can specify the VAF in the input BED file, but I also know there is a -m option and am not sure how to deal with that. If I want to specify individual VAFs for each site in the BED file, do I omit the -m option? 

Thanks,
Alva

**Comment by adamewing** [comment]
Hi Alva,

The VAF in the input file overrides the VAF specified with -m. The -m option is to set a default if nothing is specified in the input. As a technical aside, I wouldn't refer to the input (-v) file as a BED, in part because BED uses 0-based positions and the bamsurgeon input is 1-based (like VCF) and it doesn't adhere to other BED format specs.

--Adam

**Comment by aistrand** [comment]
Thanks for the clarification! I didn't know that the input -v file was 1-based; since you referred to it as having BED-3 format in the Manual document, I thought it was zero-based. So your program converts the positions from 1-based to zero-based then, since we are actually trying to introduce mutations into BAM files?

**Comment by aistrand** [comment]
Also, does the -v input file have to be tab-separated or just separated by a single space? Anything else that is important to know about this file?

**Comment by aistrand** [comment]
There is a small typo in the Manual; in 2.2, it should say Figure 1 instead of Figure 2 (since we are talking about SNVs)

**Comment by adamewing** [comment]
Thanks for pointing out the issues with the manual (inappropriate reference to BED and fig 1 vs 2)!

-v is whitespace seperated (so any number of spaces or tabs should be equivalent)

-v can have at minimum three columns and at most five, with the extra two being VAF and a base which will be substituted for the base at the specified position.

- For SNVs, If more than one base is specified (e.g. chr1 1000 1005 1.0) it will pick the mutation site from the interval [1000, 1005] at random. To specify a specific base use chr1 1002 1002 (for position 1002).

It is zero based in the BAM, yes, but SAM is 1-based so positions using e.g. samtools mpileup will match positions in the -v file which will match positions in the VCF file, if that makes sense.

**Comment by aistrand** [comment]
Thanks for clarifying! Can I still use BAM files as input, then? (as specified in the Manual: -f BAMFILENAME - sam/bam file from which to obtain reads) Or do I have to convert my BAM files to SAM files?

**Comment by adamewing** [comment]
Input to -f needs to be an indexed BAM.

**Comment by aistrand** [comment]
OK, great.
