### ISSUE TITLE
Suggestions for coverdiff?

### ISSUE THREAD

**Issue by aistrand** [adamewing/bamsurgeon#50]
Hi Adam,

I am not interested in there being a difference between input and output coverage. Is 0.9 (default) a good value in terms of the threshold for coverdiff, in that case?

Thanks,
Alva

**Comment by aistrand** [comment]
There is also an inconsistency in the documentation for the default value of -mindepth: in one place it says the default is 5, and in another it says it's 10. Which is it?

**Comment by adamewing** [comment]
Yes I think 0.9 is a good default for --coverdiff most cases. The idea is to prevent mutations that alter too many read mappings (this can happen especially in regions with low mappability).

Default for --mindepth is 10.
