### ISSUE TITLE
OSError: [Errno 17] File exists: 'addsnv.tmp'

### ISSUE THREAD

**Issue by aistrand** [adamewing/bamsurgeon#51]
When I run bamsurgeon on one of my BAM files, I get the following error message:

Traceback (most recent call last):
  File "/ifs/home/c2b2/mp_lab/ams2432/bamsurgeon-master/bin/addsnv.py", line 513, in <module>
    run()
  File "/ifs/home/c2b2/mp_lab/ams2432/bamsurgeon-master/bin/addsnv.py", line 510, in run
    main(args)
  File "/ifs/home/c2b2/mp_lab/ams2432/bamsurgeon-master/bin/addsnv.py", line 352, in main
    os.mkdir(args.tmpdir)
OSError: [Errno 17] File exists: 'addsnv.tmp'

The program works for my other bam files. I am using identical parameters for all of the runs. These are the inputs:

INFO	2016-04-13 00:29:11.257192	starting /ifs/home/c2b2/mp_lab/ams2432/bamsurgeon-master/bin/addsnv.py called with args: /ifs/home/c2b2/mp_lab/ams2432/bamsurgeon-master/bin/addsnv.py -v /ifs/scratch/c2b2/mp_lab/ams2432/hutt/dnm_files/matching/bamsurgeon/bed_input/sites.non_cpgs.84.02.trio3.chr2.20000.txt -f /ifs/scratch/c2b2/mp_lab/ams2432/hutt/best_practices/recal_bams_split/recal_Hutt3-chr2_5mb_region.bam -r /ifs/data/c2b2/mp_lab/ams2432/files_needed/human_ref/hs37d5.fa -o /ifs/scratch/c2b2/mp_lab/ams2432/hutt/dnm_files/matching/bamsurgeon/spiked_bams/spikedin_20000_Hutt3-chr2_5mb_region.bam --picardjar /ifs/home/c2b2/mp_lab/ams2432/picard-tools-1.141/ --mindepth 11 --maxdepth 48 --minmutreads 3 --tagreads --aligner mem

I'm not sure I understand what the error is. How do I fix it?

**Comment by adamewing** [comment]
Try setting a different tmp diretory with --tmpdir
