### ISSUE TITLE
art_illumina instead of wgsim

### ISSUE THREAD

**Issue by tseemann** [adamewing/bamsurgeon#54]
I was wondering if `art_illumina` would be more useful compared to `wgsim`?

http://www.niehs.nih.gov/research/resources/software/biostatistics/art/

It has more flexible parameters, and has profiles (and a profile builder) for different machines.

**Comment by adamewing** [comment]
Adding other read simulators for the SV stuff has been on the to-do list - wgsim was just a choice of convenience as it's bundled with samtools. Note that changing the read simulator will only affect reads involved in creating SVs. ART seems widely used and looks like a good choice, thanks for the suggestion!

**Comment by tseemann** [comment]
In that case it is probably better to stick with `wgsim` - there isn't much to gain from more specialised read simulators, plus you get it for free with `samtools`.
