### ISSUE TITLE
Allowing for variation in coverage given specified allelic fraction?

### ISSUE THREAD

**Issue by aistrand** [adamewing/bamsurgeon#56]
Hi Adam,

I see in the code that you calculate existing coverage of aligned reads over a region of interest (and you also calculate output coverage). Do you allow for some variation in coverage when mutations are introduced (when you flip reads from covering the reference base to an alternate base)? Or, say if coverage is 20 and VAF is 0.5, does that simply mean that the bases in 10 reads aligned to the reference position are changed to an alternate base? 

Thanks in advance,
Alva

**Comment by adamewing** [comment]
Hi Alva, Each read covering a mutation site has a chance to be mutated directly corresponding to the VAF, so it's not guaranteed that out of 20 reads exactly 10 will be mutated: with a VAF of 0.5 each read has a 50% chance of being mutated. Let me know if that answers your question.

--Adam
