### ISSUE TITLE
addsnv doesn't add SNVs to some locations even though very high read depth and no overlapping reads

### ISSUE THREAD

**Issue by rdbcasillas** [adamewing/bamsurgeon#57]
Hi adam,
I used the following command:

`
addsnv.py -p 10 --ignoresnps --force --maxdepth 10000  -v locations.bed -f sortedbam -r reference -o output > output.log 2>&1 &
`
As can be noticed from the options, I am taking care of lot of things that could possibly stop bamSurgeon from adding a mutation. The only thing missing is the 5th column in spike-in file with a specific base.

But anyway, I notice many locations where mutations weren't made and from the logs I was surprised about a particular warning:

``
WARN    2016-05-17 11:21:15.388444      haplo_1_115256537_115256538     could not pileup for region: 1:115256399

WARN    2016-05-17 11:21:15.388939      haplo_1_115256442_115256443     could not pileup for region: 1:115256399

WARN    2016-05-17 11:21:15.480708      haplo_1_115256537_115256538     could not pileup for region: 1:115256410

INFO    2016-05-17 11:21:15.482319      haplo_1_115256442_115256443     mpileup failed, no coverage for base: 1:115256410
``
I am already taking care of min depth by making sure the spike-in sites in my bed file all have >1000 read depth. Why would it try to add mutations at places other than what I specify? Why is it worried about 1:115256399 and 1:115256410  when that is not what I ask for? For both the locations that I get warning for above, no mutations are added in modified Bam ( I expected at least one). Also, no overlapping reads are causing issues (no close locations other than these 2)

Thank you for answering.

**Comment by adamewing** [comment]
It currently checks for coverage over any reads that contain the mutation position. Try adding `--ignorepileup` to the parameters and see if that helps.

**Comment by rdbcasillas** [comment]
Thanks Adam. But I did check with --ignorepileup and it didn't help.  I am not clear about the warning and it would be great if you can clarify that. So part of my bed file looks like this:

```
1       115256442       115256442       0.25
1       115256537       115256537       0.25
```


And following is one of the warnings I get when I look for locations where bamSurgeon couldn't add mutations:

```
haplo_1_115256442_115256443     could not pileup for region: 1:115256399
haplo_1_115256537_115256538     could not pileup for region: 1:115256399
haplo_1_115256537_115256538     could not pileup for region: 1:115256410
haplo_1_115256442_115256443     could not pileup for region: 1:115256399
```

My question is why "1:115256399" and "1:115256399" are being checked when they aren't even part of the reads where my specified SNV locations are? It seems like bamSurgeon isn't adding SNPs at those two locations in bed file, after deciding that it "could not pileup" for unrelated (not on same read) locations. 

Am I clearer in framing of my question or am I confused about something obvious?

**Comment by adamewing** [comment]
Cleaning up old open issues, please re-open if still an active issue.
