### ISSUE TITLE
addsnv has errors in the pysam step

### ISSUE THREAD

**Issue by jayaramanp** [adamewing/bamsurgeon#60]
hello, 
i'm trying to spike a bam file but i keep getting the following errors and i need to know how to debug this:
python addsnv.py -v ../test_data/random_snvs.txt -f ../test_data/testregion_novo_realign.bam -r ../test_data/Homo_sapiens_chr22_assembly19.fasta -o ../test_data/testregion_novo_spikedMut.bam -p 5 --picardjar /nfs/Public/picard/1.140/picard.jar --ignoresnps --force --tmpdir /tmp/BamspikingTmp

when using the test data and using the default aligner (or when im using novoalign as my aligner and provide the index for novoalign, i get the following output for my process:

(..only copying the last couple logs as there are many, i presume, one for each snv that it tried to spike. )
************************************************************
************************************************************
ERROR	2016-05-27 07:05:58.862516	encountered error in mutation spikein: ['22_34314307_34314308_None_None']
Traceback (most recent call last):
  File "addsnv.py", line 156, in makemut
    mutfail, hasSNP, maxfrac, outreads, mutreads, mutmates = mutation.mutate(args, log, bamfile, bammate, chrom, min(mutpos_list), max(mutpos_list)+1, mutpos_list, avoid=avoid, mutid_list=mutid_list, is_snv=True, mutbase_list=mutbase_list, reffile=reffile)
  File "build/bdist.linux-x86_64/egg/bamsurgeon/mutation.py", line 186, in mutate
    mate = find_mate(pread.alignment, bammate)
  File "build/bdist.linux-x86_64/egg/bamsurgeon/mutation.py", line 121, in find_mate
    chrom = read.next_reference_name
AttributeError: 'pysam.calignmentfile.AlignedSegment' object has no attribute 'next_reference_name'
************************************************************
************************************************************
ERROR	2016-05-27 07:05:59.529534	encountered error in mutation spikein: ['22_34322818_34322819_None_None']
Traceback (most recent call last):
  File "addsnv.py", line 156, in makemut
    mutfail, hasSNP, maxfrac, outreads, mutreads, mutmates = mutation.mutate(args, log, bamfile, bammate, chrom, min(mutpos_list), max(mutpos_list)+1, mutpos_list, avoid=avoid, mutid_list=mutid_list, is_snv=True, mutbase_list=mutbase_list, reffile=reffile)
  File "build/bdist.linux-x86_64/egg/bamsurgeon/mutation.py", line 186, in mutate
    mate = find_mate(pread.alignment, bammate)
  File "build/bdist.linux-x86_64/egg/bamsurgeon/mutation.py", line 121, in find_mate
    chrom = read.next_reference_name
AttributeError: 'pysam.calignmentfile.AlignedSegment' object has no attribute 'next_reference_name'
************************************************************
INFO	2016-05-27 07:05:59.531348	no succesful mutations

**Comment by jayaramanp** [comment]
okay, so i went through the "closed issues" and figured out my pysam installation wasnt good enough so followed advice on installing pysam from git and not use pip upgrade. 


test data runs successfully but when i use my own data i get issues with mutfrac. 
how do i debug this?


[jayaramanp@dgdrhr-01 bin]$ python addsnv.py -v ~/bamSurgeonData/snvToSpike.bed -f ~/bamSurgeonData/CLINICALWES-10_CWES-0045-P-A-DGD-15-8_1.recal.sorted.bam -r /nfs/DGD/Clinical/kbase/reference/g1k_v37/human_g1k_v37.fasta -o ../test_data/testregion_novo_spikedMut_CLINWES.bam -p 5 --picardjar /nfs/Public/picard/1.140/picard.jar --aligner novoalign --alignopts novoref:/nfs/DGD/Clinical/kbase/reference/g1k_v37/human_g1k_v37.nix --ignoresnps --force --tmpdir /tmp/BamspikingTmp
INFO	2016-05-27 07:52:22.113316	starting addsnv.py called with args: addsnv.py -v /home/jayaramanp/bamSurgeonData/snvToSpike.bed -f /home/jayaramanp/bamSurgeonData/CLINICALWES-10_CWES-0045-P-A-DGD-15-8_1.recal.sorted.bam -r /nfs/DGD/Clinical/kbase/reference/g1k_v37/human_g1k_v37.fasta -o ../test_data/testregion_novo_spikedMut_CLINWES.bam -p 5 --picardjar /nfs/Public/picard/1.140/picard.jar --aligner novoalign --alignopts novoref:/nfs/DGD/Clinical/kbase/reference/g1k_v37/human_g1k_v37.nix --ignoresnps --force --tmpdir /tmp/BamspikingTmp

INFO	2016-05-27 07:52:22.203288	created directory: addsnv_logs_testregion_novo_spikedMut_CLINWES.bam
Debug, haploclusters:[[{'start': 166047762, 'end': 166047763, 'chrom': '2', 'altbase': None, 'vaf': 0.49}], [{'start': 166056406, 'end': 166056407, 'chrom': '2', 'altbase': None, 'vaf': 0.4}], [{'start': 166073546, 'end': 166073547, 'chrom': '2', 'altbase': None, 'vaf': 0.5}]]
INFO	2016-05-27 07:52:22.368405	haplo_2_166047763_166047763	creating tmp bam:  /tmp/BamspikingTmp/haplo_2_166047763_166047763.tmpbam.3e40f883-ca4a-4d85-becd-d19d3e85d2b7.bam
************************************************************
ERROR	2016-05-27 07:52:22.374686	encountered error in mutation spikein: ['2_166047762_166047763_0.49_None']
Traceback (most recent call last):
  File "addsnv.py", line 156, in makemut
    mutfail, hasSNP, maxfrac, outreads, mutreads, mutmates = mutation.mutate(args, log, bamfile, bammate, chrom, min(mutpos_list), max(mutpos_list)+1, mutpos_list, avoid=avoid, mutid_list=mutid_list, is_snv=True, mutbase_list=mutbase_list, reffile=reffile)
  File "build/bdist.linux-x86_64/egg/bamsurgeon/mutation.py", line 225, in mutate
    assert maxfrac is not None, "Error: could not pile up over region: %s" % region
AssertionError: Error: could not pile up over region: haplo_2_166047763_166047764
************************************************************
INFO	2016-05-27 07:52:22.424745	haplo_2_166056407_166056407	creating tmp bam:  /tmp/BamspikingTmp/haplo_2_166056407_166056407.tmpbam.62955e92-fe98-4027-9591-5d6a5a99057a.bam
INFO	2016-05-27 07:52:22.426326	haplo_2_166073547_166073547	creating tmp bam:  /tmp/BamspikingTmp/haplo_2_166073547_166073547.tmpbam.08b6d944-9c10-4554-8422-0912183c8b65.bam
************************************************************
ERROR	2016-05-27 07:52:22.430809	encountered error in mutation spikein: ['2_166073546_166073547_0.5_None']
Traceback (most recent call last):
  File "addsnv.py", line 156, in makemut
    mutfail, hasSNP, maxfrac, outreads, mutreads, mutmates = mutation.mutate(args, log, bamfile, bammate, chrom, min(mutpos_list), max(mutpos_list)+1, mutpos_list, avoid=avoid, mutid_list=mutid_list, is_snv=True, mutbase_list=mutbase_list, reffile=reffile)
  File "build/bdist.linux-x86_64/egg/bamsurgeon/mutation.py", line 225, in mutate
    assert maxfrac is not None, "Error: could not pile up over region: %s" % region
AssertionError: Error: could not pile up over region: haplo_2_166073547_166073548
************************************************************
INFO	2016-05-27 07:52:29.386252	haplo_2_166056407_166056407	len(readlist): 1
WARN	2016-05-27 07:52:29.386470	haplo_2_166056407_166056407	too few reads in region (1) skipping...
INFO	2016-05-27 07:52:29.417672	no succesful mutations

**Comment by adamewing** [comment]
The "test" BAMs that come with BAMSurgeon don't have coverage for anything except a small region of chr22 - if you're using these to test mutations anywhere else it will fail due to lack of coverage. Let me know if that makes sense, sorry for the delay as I'm overseas at the moment!
