### ISSUE TITLE
not sure how to troubleshoot error

### ISSUE THREAD

**Issue by astewart-twist** [adamewing/bamsurgeon#68]
Hi there.  I'm getting the following error but I'm not sure why since I'm passing `--ignorepileup`.  Any advice?

```
INFO	2016-07-26 22:14:12.345381	ol_1_5_9_0.1:DEL	creating tmp bam:  addindel.tmp/ol_1_5_9_0.1:DEL.tmpbam.f52f1d5b-d1c9-4021-8a18-13eb14059958.bam
************************************************************
encountered error in mutation spikein: ol_1_5_9_0.1:DEL
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/site-packages/bamsurgeon-1.0-py2.7.egg/EGG-INFO/scripts/addindel.py", line 116, in makemut
  File "build/bdist.macosx-10.10-x86_64/egg/bamsurgeon/mutation.py", line 225, in mutate
    assert maxfrac is not None, "Error: could not pile up over region: %s" % region
AssertionError: Error: could not pile up over region: haplo_ol_1_5_10
```

**Comment by adamewing** [comment]
What does your mutation input file (the one you're passing to -v) look like?

**Comment by astewart-twist** [comment]
Thanks for the fast reply @adamewing !

I'm just trying to use some very basic example inputs to start with:

```
ol_1 5 9 0.1 DEL
ol_2 5 9 0.2 DEL
ol_3 5 9 0.3 DEL
```

One thing that might be an issue (though I'm not specifically sure how) is that my reference consists of several short sequences (~100bp each) rather than a small number of long genomic sequences.

**Comment by astewart-twist** [comment]
Ah, disregard.  I had accidentally overwritten my reference file.
