### ISSUE TITLE
SNV insertion creates a discordant read pair hotspot

### ISSUE THREAD

**Issue by d-cameron** [adamewing/bamsurgeon#70]
Inserting a SNV results in more discordant read pairs containing reads spanning the SNV than would be expected from an actual SNV in the data. Is this a data issue where the bamsurgeon aligner was not the same aligner used for the alignment of originating BAM, a bamsurgeon algorithm issue, or an issue caused by the aligner behaving differently when only dealing with the bamsurgeon subset of the data (eg bwa calculation of fragment size distribution could be problematic if there's lots of SV in the bamsurgeon subset).
From the IS6 DREAM challenge data set:
![synthetic6-false-positive-signal-from-snv](https://cloud.githubusercontent.com/assets/6036536/17703230/4f30acfa-6414-11e6-878a-b37b6f114c29.png)

**Comment by d-cameron** [comment]
I'm having a similar problem around indel insertions. If an indel is inserted in a repetitive element, my assembly algorithm is finding good quality contigs from the indel insertion site, to a nearby location that RepeatMasker informs me is of the same repeat class as that of reads spanning the insertion. Are these likely to be due to contig misassemblies in bamsurgeon, or does indel insertion not generate contigs?

Whilst it is nice to be able to be sensitive enough to pick up such bamsurgeon artefacts, it's somewhat frustrating as it's throwing out my specificity. IS6 examples of this behaviour include:
- chr10:38,795,782
- chr1:32,944,985-32
- chr20:48,152,085 (this is an actual SV, but reassembly of the anchoring bases causes an overlapping FP call)

**Comment by adamewing** [comment]
Altering reads may lead to changes in read mapping locations, yielding this kind of result. This is especially true in repeat element locations as you note. No assembly is involved in SNV/INDEL spike-in, just altering the read over specific bases. So, I'm not sure I'd call it an artefact, as a real mutation in a repeat element might have the same effect i.e. altering read mappings for the reads with the alternate base. I'll have a look at the specific examples you cite so see whether this is really the case at those locations.

**Comment by adamewing** [comment]
Actually, it would be helpful if you could send me a few examples of locations and ALT bases where spikein SNVs alter read mappings leading to discordant pairs.

**Comment by d-cameron** [comment]
Do you feed the aligner a baseline set of reads as well as the ones to be realigned? The issue might be as simple as SV reads skewing the insert size distribution statistics causing a change in the concordant fragment size range, of even just a different aligner version/parameters than what the original bam was aligned with.

**Comment by adamewing** [comment]
The way bamsurgeon is currently written, snvs, svs, and indels are added by different scripts, so SV reads won't be realigned along with SNV reads. To make a BAM file that simulates all three kinds of variants, I recommend creating a set of altered realigned reads for each mutation type separately (using --skipmerge) before finally swapping these into the original BAM. You are correct that using the same aligner and the same aligner parameters is important (these can be tweaked in the bamsurgeon/aligners.py).

So when you say a read is discordant, is this based on the "proper pair" flag? (I think this is what IGV uses to visually identify "discordant" read pairs). Are the altered reads from your first and second messages actually mapping with a markedly different insert size vs. non-altered reads or is just the proper pair flag set differently between them?

**Comment by d-cameron** [comment]
chr1:687,234-712,997 is a good example to view in IGV. Just looking at the reads, you can clearly see that that inter-chromosomal mapping rate is way higher in the tumour than in the normal implying that some event has been inserted in that region.

**Comment by adamewing** [comment]
Thanks, so first impressions, this is a region with pretty poor mappability: [browser shot of chr1:687,234-712,997](https://genome.ucsc.edu/cgi-bin/hgTracks?hgS_doOtherUser=submit&hgS_otherUserName=Adam%20Ewing&hgS_otherUserSessionName=dc_example1_lomap)

I've come across a few cases like this where a mutation at one site, typically with low mappability (e.g. repeats, low complexity regions, duplicated regions) will cause reads to map to another site with high sequence similarity to the intended mutation site. Another side effect of this is the actual intended mutation site will have a dip in coverage while the realignment site will see an increase in mapped reads. I suspect this is what is happening in this instance as there is nothing in the IS6 truth file in the interval chr1:687,234-712,997, which means the intended mutation is probably somewhere else with high sequence similarity to chr1:687,234-712,997. Hope that makes some sense, I agree it's a rather annoying side effect of SNV/INDEL addition but it is a "real" effect in the sense that if a somatic mutation actually occurs that affects read placement in this way, you'll get a bunch of discordant reads clustered over the alternate mapping location.

**Comment by d-cameron** [comment]
It does, and I see why a variant in repetitive sequence would have echos in the alternate mapping locations, but it doesn't explain why there is such a rate of chimeric fragments in that interval. I presume that is not present in the unmodified bam.

Filtering to display only the discordant reads (top/bottom 0.5%) with mapq > 10 you get something like this:
![igv_snapshot](https://cloud.githubusercontent.com/assets/6036536/17736189/bb3e151c-64c9-11e6-8082-69e0e20a86fe.png)

As you can see, there's 8 reads in the normal that are discordant, and about 500 in the tumour in addition to ~80 soft clipped reads at chr1:701,857.

The soft clips at chr1:701,857 and the doubling of coverage at the peaks can be explained by it being the end of a somatic het tandem duplication and that's what I've called, but it doesn't explain why the realigner doesn't care about concordant placement but the initial alignment did. It looks very much like it was aligned by different aligner (or different version of the aligner or with different flags). 500 vs 8 is a big difference.

At this point I don't know whether to attribute this to an artifact of the bamsurgeon design, or an IS6 data generation issue.

**Comment by adamewing** [comment]
I see, and I agree that seems like an odd pattern. Given that those pileups of mq>10 reads seem to correspond roughly to the Alu repeats I would guess that maybe it's the result of one of more SV spike-ins somewhere involving Alu repeat at the breakpoint and this is a side-effect? Just speculation. The original mapping and re-mappings for that "IS" bam were both done with bwa mem 0.7.10, default parameters, but as you alluded to previously, remapping is done with a limited subset of reads, which includes altered reads, so the insert size estimation for SV remappings might explain this. Maybe adding a bunch of non-discordant reads to the pool to be remapped would help as you suggest. I'll need to play around with it, but thanks for the example!

**Comment by d-cameron** [comment]
chr16:71027569-71032237 is another example of a SV insertion in which the reads aren't concordantly mapped. In this example, they all map off to chr1_gl000192_random - a mapping location not readily explained by another event.

IS6 also has reads that contain both invalid CIGARs (eg I5145M), and mapq scores outside bwa reporting range (in the 61-70 range). Is this bamsurgeon doing this when performing indel insertion, or it is something else?

**Comment by adamewing** [comment]
Thanks for the example. Bamsurgeon doesn't manipulate CIGAR strings or mapQs directly as those are generated by the aligner.
