### ISSUE TITLE
bamsurgeon gives error while creating snvs for bowtie2

### ISSUE THREAD

**Issue by MMJ7** [adamewing/bamsurgeon#71]
While using 
bamsurgeon-master/bin/addsnv.py  -f /gpfs/gpfs0/projects/Drm/1000_genome_fastq/SRR1291026.sorted.bam -v test2.var -r ucsc.hg19.fasta -o SRR1291026_mutc.bam

I get the error below:
************************************************************
ERROR	2016-08-31 22:28:51.479370	encountered error in mutation spikein: ['chr1_144923733_144923733_0.563_None']
Traceback (most recent call last):
  File "bamsurgeon-master/bin/addsnv.py", line 159, in makemut
    mutfail, hasSNP, maxfrac, outreads, mutreads, mutmates = mutation.mutate(args, log, bamfile, bammate, chrom, min(mutpos_list), max(mutpos_list)+1, mutpos_list, avoid=avoid, mutid_list=mutid_list, is_snv=True, mutbase_list=mutbase_list, reffile=reffile)
  File "/gpfs/gpfs0/home/mjalalzai/bamsurgeon-master/bamsurgeon/mutation.py", line 207, in mutate
    basepile = countBaseAtPos(args.bamFileName,chrom,pcol.pos,mutid=region)
  File "/gpfs/gpfs0/home/mjalalzai/bamsurgeon-master/bamsurgeon/mutation.py", line 14, in countBaseAtPos
    p = subprocess.Popen(args,stdout=subprocess.PIPE,stderr=subprocess.PIPE)
  File "/usr/lib/python2.7/subprocess.py", line 710, in __init__
    errread, errwrite)
  File "/usr/lib/python2.7/subprocess.py", line 1327, in _execute_child
    raise child_exception
OSError: [Errno 2] No such file or directory

**Comment by adamewing** [comment]
resolved via email

**Comment by rbatorsky-claritas** [comment]
I'm getting a similar subprocess error issue trying to run the snv test. I've tried a few things, and adding "shell=True" to each subprocess call seems to allow the command to run. Wondering how this code is running for others. Thanks.

I'm running:
bamsurgeon/test> ./test_snv.sh 1 1 ../test_data/Homo_sapiens_chr22_assembly19.fasta

With result:
INFO	2016-10-17 09:03:32.758026	starting /usr/local/bin/addsnv.py called with args: /usr/local/bin/addsnv.py -v ../test_data/random_snvs.txt -f ../test_data/testregion_realign.bam -r ../test_data/Homo_sapiens_chr22_assembly19.fasta -o ../test_data/testregion_mut.bam -n 1 -p 1 --ignoresnps --ignorepileup --seed 1234

Debug, haploclusters:[[{'start': 34166720, 'end': 34166721, 'chrom': '22', 'altbase': None, 'vaf': 1.0}]]
INFO	2016-10-17 09:03:32.775549	haplo_22_34166721_34166721	creating tmp bam:  addsnv.tmp/haplo_22_34166721_34166721.tmpbam.5957150c-ccf5-4378-8864-0471d508b0d1.bam
INFO	2016-10-17 09:03:33.874813	haplo_22_34166721_34166721	len(readlist): 58
INFO	2016-10-17 09:03:33.874942	haplo_22_34166721_34166721	selected VAF: 1.0

INFO	2016-10-17 09:03:33.875171	haplo_22_34166721_34166721	picked: 58
INFO	2016-10-17 09:03:33.877082	haplo_22_34166721_34166721	wrote:  58 mutated: 58
backtrack
addsnv.tmp/haplo_22_34166721_34166721.tmpbam.5957150c-ccf5-4378-8864-0471d508b0d1.bam
../test_data/Homo_sapiens_chr22_assembly19.fasta
{}
haplo_22_34166721_34166721
False
None
INFO	2016-10-17 09:03:33.879779	haplo_22_34166721_34166721	mapping 1st end, cmd: bwa aln -q 5 -l 32 -k 3 -t 1 -o 1 -f addsnv.tmp/haplo_22_34166721_34166721.tmpbam.5957150c-ccf5-4378-8864-0471d508b0d1.bam.1.sai -b1 ../test_data/Homo_sapiens_chr22_assembly19.fasta addsnv.tmp/haplo_22_34166721_34166721.tmpbam.5957150c-ccf5-4378-8864-0471d508b0d1.bam
************************************************************
ERROR	2016-10-17 09:03:33.884458	encountered error in mutation spikein: ['22_34166720_34166721_1.0_None']
Traceback (most recent call last):
  File "/Library/Python/2.7/site-packages/bamsurgeon-1.0-py2.7.egg/EGG-INFO/scripts/addsnv.py", line 283, in makemut
  File "build/bdist.macosx-10.10-intel/egg/bamsurgeon/aligners.py", line 59, in remap_bam
    remap_backtrack_bam(bamfn, threads, fastaref, mutid=mutid, paired=paired)
  File "build/bdist.macosx-10.10-intel/egg/bamsurgeon/aligners.py", line 98, in remap_backtrack_bam
    subprocess.call(sai1args)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/subprocess.py", line 522, in call
    return Popen(*popenargs, **kwargs).wait()
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/subprocess.py", line 710, in __init__
    errread, errwrite)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/subprocess.py", line 1335, in _execute_child
    raise child_exception
OSError: [Errno 2] No such file or directory
************************************************************
INFO	2016-10-17 09:03:33.886000	no succesful mutations
[E::hts_open_format] fail to open file '../test_data/testregion_mut.bam'
[mpileup] failed to open ../test_data/testregion_mut.bam: No such file or directory
Failed to open -: unknown file type
