### ISSUE TITLE
ValueError: reference_id -1 out of range 0<=tid<84

### ISSUE THREAD

**Issue by nbl1027** [adamewing/bamsurgeon#73]
Hiya Adam

I am having issues running the addsnp.py file. I am using the human_g1k_v37 reference from the 1000 genomes project along with a BAM file from the project and I am getting the following error:

ERROR	2016-10-04 10:27:05.346346	encountered error in mutation spikein: ['1_115251145_115251145_0.5_C']
Traceback (most recent call last):
  File "addsnv.py", line 156, in makemut
    mutfail, hasSNP, maxfrac, outreads, mutreads, mutmates = mutation.mutate(args, log, bamfile, bammate, chrom, min(mutpos_list), max(mutpos_list)+1, mutpos_list, avoid=avoid, mutid_list=mutid_list, is_snv=True, mutbase_list=mutbase_list, reffile=reffile)
  File "/usr/local/lib/python2.7/dist-packages/bamsurgeon-1.0-py2.7.egg/bamsurgeon/mutation.py", line 186, in mutate
    mate = find_mate(pread.alignment, bammate)
  File "/usr/local/lib/python2.7/dist-packages/bamsurgeon-1.0-py2.7.egg/bamsurgeon/mutation.py", line 121, in find_mate
    chrom = read.next_reference_name
  File "pysam/calignedsegment.pyx", line 941, in pysam.calignedsegment.AlignedSegment.next_reference_name.__get__ (pysam/calignedsegment.c:11814)
  File "pysam/calignmentfile.pyx", line 1654, in pysam.calignmentfile.AlignmentFile.getrname (pysam/calignmentfile.c:18204)
  File "pysam/calignmentfile.pyx", line 679, in pysam.calignmentfile.AlignmentFile.get_reference_name (pysam/calignmentfile.c:9070)
ValueError: reference_id -1 out of range 0<=tid<84

I have checked all the reference files etc and I cant see what is wrong. Any help would be appreciated as I am a bit stumped!

Ta!
Kirsty

**Comment by adamewing** [comment]
Hi Kirsty,

Are you able to run the test_snv.sh (or test_snv_bwamem.sh) scripts in the test directory?

If those work fine on your end, could you send me the header of your BAM file (samtools view -H) and the command line you are using when you hit this error (removing local paths is fine).

Thanks!

**Comment by nbl1027** [comment]
Thanks for getting back to me!

The test_snv.sh does not work, I get this error:

ERROR	2016-10-05 17:11:06.000901	encountered error in mutation spikein: ['22_34166720_34166721_1.0_None']
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/bamsurgeon-1.0-py2.7.egg/EGG-INFO/scripts/addsnv.py", line 275, in makemut
    aligners.remap_bam(args.aligner, tmpoutbamname, args.refFasta, alignopts, mutid=hapstr, paired=(not args.single), picardjar=args.picardjar)
  File "/usr/local/lib/python2.7/dist-packages/bamsurgeon-1.0-py2.7.egg/bamsurgeon/aligners.py", line 59, in remap_bam
    remap_backtrack_bam(bamfn, threads, fastaref, mutid=mutid, paired=paired)
  File "/usr/local/lib/python2.7/dist-packages/bamsurgeon-1.0-py2.7.egg/bamsurgeon/aligners.py", line 110, in remap_backtrack_bam
    os.rename(sortfn, bamfn)
OSError: [Errno 2] No such file or directory

And my BAM header looks like this 

@HD	VN:1.0	GO:none	SO:coordinate
@SQ	SN:1	LN:249250621	M5:91E16EEE832989A1C0CEE9C2FB2FE429
@SQ	SN:2	LN:243199373	M5:D1E265E7ADA3D91A83CA2B253BCB6AF8
@SQ	SN:3	LN:198022430	M5:AA1735C79DBA04F2B457216BF5CB7787
@SQ	SN:4	LN:191154276	M5:357F6B8FAA5E95F04D1F02B9D9A8475E
@SQ	SN:5	LN:180915260	M5:94E592D6EEFC999610A9CF2EF0D798C3
@SQ	SN:6	LN:171115067	M5:926BF0A6DFD8ED3439B2E413186548B2
@SQ	SN:7	LN:159138663	M5:7F178509DFCEB0B3127BA9CA928B6871
@SQ	SN:8	LN:146364022	M5:44BBF9F85B1018DEDCB699287116413F
@SQ	SN:9	LN:141213431	M5:D423422F7B2921551A599110737CC4E7
@SQ	SN:10	LN:135534747	M5:F3E6602D046C43678F479EB5B0461466
@SQ	SN:11	LN:135006516	M5:1B3FE10BB7DD59565193E4C2E1AAD64A
@SQ	SN:12	LN:133851895	M5:430BA2F2F4C6E1005FB611FA48C31D4F
@SQ	SN:13	LN:115169878	M5:A649DE6D032C291CFC22F0F46A0BFECC
@SQ	SN:14	LN:107349540	M5:0BEEA166A9DC2611E0CD244B18D68930
@SQ	SN:15	LN:102531392	M5:EEA4D0D6D1735590D662B8AC2D9ABBB2
@SQ	SN:16	LN:90354753	M5:1F12162808AA0B76E3CA07B250CB990A
@SQ	SN:17	LN:81195210	M5:6D7CB6033702D911B860355E699447E6
@SQ	SN:18	LN:78077248	M5:BD8CC3637A234DD3052FFD4A17AFC795
@SQ	SN:19	LN:59128983	M5:5893844B519F8F0FFB5D730F7D5350FE
@SQ	SN:20	LN:63025520	M5:187795B057E2482349AC40D4FD848B24
@SQ	SN:21	LN:48129895	M5:720F8716257C796615028FD85D47273C
@SQ	SN:22	LN:51304566	M5:AB8C879CAC14608B5EBC774CFC35F6D7
@SQ	SN:X	LN:155270560	M5:B53E327FB364EA5C51380FA83513ACF7
@SQ	SN:Y	LN:59373566	M5:02C05F8E29C4895453BE5AFF61084D55
@SQ	SN:MT	LN:16569	M5:40BB9DA558CB5E962C3579587879B0B7
@SQ	SN:GL000207.1	LN:4262	M5:7A7DD60C0D486F01FF69D2D6ACD34DCD
@SQ	SN:GL000226.1	LN:15008	M5:14BEBBA6322F1BB80D7D1B71DEA7B98C
@SQ	SN:GL000229.1	LN:19913	M5:88EE3B0D7AE703087068506089C8A915
@SQ	SN:GL000231.1	LN:27386	M5:F37254DC3D89D64BFDF02931A8E7B5FA
@SQ	SN:GL000210.1	LN:27682	M5:D0656538624C0BC72C6ED894C2EEA333
@SQ	SN:GL000239.1	LN:33824	M5:7BFC81010D443729D865E760FDE3207D
@SQ	SN:GL000235.1	LN:34474	M5:F55F2095D2BC368AE9F8B0F7DA915BC0
@SQ	SN:GL000201.1	LN:36148	M5:37207AF1A80E5B2A5119A6DF96396F53
@SQ	SN:GL000247.1	LN:36422	M5:BDC80158060000383FAF27498C2697A0
@SQ	SN:GL000245.1	LN:36651	M5:34FC8FAA5A9A1BB43B59627D4B66E944
@SQ	SN:GL000197.1	LN:37175	M5:E1D8D9A81FDEF5BEB15E5909369366BA
@SQ	SN:GL000203.1	LN:37498	M5:A5FA811B6E0845FD95D3B4BD048C7A7C
@SQ	SN:GL000246.1	LN:38154	M5:68EDB934704C4C3F51F64E0309EFD3C4
@SQ	SN:GL000249.1	LN:38502	M5:0E52B0FDCE01BE053F07833E9CCFA955
@SQ	SN:GL000196.1	LN:38914	M5:8AB92992572FA945172ECE1723CF2678
@SQ	SN:GL000248.1	LN:39786	M5:79E86C04750BB844BB11B55721EC4679
@SQ	SN:GL000244.1	LN:39929	M5:4E1C0EDF2DB6D28066A1116CCCD272CE
@SQ	SN:GL000238.1	LN:39939	M5:ECE8EEC11F910DE0CEB7CBD76B90CC09
@SQ	SN:GL000202.1	LN:40103	M5:692C1C402A697A813A2A35F7C8294385
@SQ	SN:GL000234.1	LN:40531	M5:FDCF9C4BBEF5EEA64A67D9396F81C613
@SQ	SN:GL000232.1	LN:40652	M5:69EF43E665904948C754C5D63B0F6660
@SQ	SN:GL000206.1	LN:41001	M5:04C9DEC0A45692505292ABEC66CB7334
@SQ	SN:GL000240.1	LN:41933	M5:5A2D4BBA8A2E030DA7A579E9B34DC107
@SQ	SN:GL000236.1	LN:41934	M5:CFFAD7A58EEF8BD493D38DB0ABE2229B
@SQ	SN:GL000241.1	LN:42152	M5:5E5513B4A688ABF771EF760CF90ACA40
@SQ	SN:GL000243.1	LN:43341	M5:E35D7D57E16D8A997B97BDECCD403D83
@SQ	SN:GL000242.1	LN:43523	M5:565B6928B064333A2E820A18CE89D94D
@SQ	SN:GL000230.1	LN:43691	M5:0D4007E804335D9E3AA06C4F0C5F8F3E
@SQ	SN:GL000237.1	LN:45867	M5:85CD9749FF277E57F4D07C6137008466
@SQ	SN:GL000233.1	LN:45941	M5:064C417250618BF6A359309555451885
@SQ	SN:GL000204.1	LN:81310	M5:507325EE6C94FE9384DB41C11837081F
@SQ	SN:GL000198.1	LN:90085	M5:DB506CB66A463DA75600898BA10BF7CE
@SQ	SN:GL000208.1	LN:92689	M5:555FB2871A54E5088F0D548FDBE8F70A
@SQ	SN:GL000191.1	LN:106433	M5:974E11767A552E388B30B999C9355F90
@SQ	SN:GL000227.1	LN:128374	M5:457EEA59CAE2C0F6306127D494598D44
@SQ	SN:GL000228.1	LN:129120	M5:78D06B8DDACB2240BBC92B6275FA5212
@SQ	SN:GL000214.1	LN:137718	M5:8AF5511C5287E87EB1794B75DB5BDFC3
@SQ	SN:GL000221.1	LN:155397	M5:DD1FDF0C0D2D8C93BB5E0B4D4D87E736
@SQ	SN:GL000209.1	LN:159169	M5:F804D0EAADA4252EBB6B027D463C8A9A
@SQ	SN:GL000218.1	LN:161147	M5:4E688DCAF6403628F93C93F71941C748
@SQ	SN:GL000220.1	LN:161802	M5:F4E3A2F9B1E761BE3065D8FA90C5C848
@SQ	SN:GL000213.1	LN:164239	M5:140B371A7D93173003F84E81EE06EE2B
@SQ	SN:GL000211.1	LN:166566	M5:A06ED54AEF0B4CD7C40E2A6CFBF795CB
@SQ	SN:GL000199.1	LN:169874	M5:DDDF120F71C14C8CFC01DDE8693769BF
@SQ	SN:GL000217.1	LN:172149	M5:BF06A0B3E9212C1BA5A03C0E61BEEABF
@SQ	SN:GL000216.1	LN:172294	M5:D87853DA25D33D070D6393016E9030AF
@SQ	SN:GL000215.1	LN:172545	M5:CAEA923D784AFE1BB1888A9C56C24445
@SQ	SN:GL000205.1	LN:174588	M5:9F36FBBFA24BE81B79B8E5AD055D924D
@SQ	SN:GL000219.1	LN:179198	M5:4DA3600A997A09FB336FEC10F55FFA91
@SQ	SN:GL000224.1	LN:179693	M5:9ADF3459F480FBE5AFB3678D66D03D7E
@SQ	SN:GL000223.1	LN:180455	M5:3BD271714D8FA2ADF1EB311B612BD4BC
@SQ	SN:GL000195.1	LN:182896	M5:B30DD6AEB033A5B1C03081F8E450CEA6
@SQ	SN:GL000212.1	LN:186858	M5:29262A3FA78A5A90F5C560758B2DE53C
@SQ	SN:GL000222.1	LN:186861	M5:FCD2A392CF559D050BFD324F8B0CEC80
@SQ	SN:GL000200.1	LN:187035	M5:73287C34551DF39E6455DBE4658E41D0
@SQ	SN:GL000193.1	LN:189789	M5:074B99380CBE68AD1B60BE215EDC01CC
@SQ	SN:GL000194.1	LN:191469	M5:970FB96F012735B482536CA9EA285965
@SQ	SN:GL000225.1	LN:211173	M5:E3AF66286DA84EBDFD601483C033A11C
@SQ	SN:GL000192.1	LN:547496	M5:09CAEB263E32A57D9038A9A1339D03C2
@RG	ID:SRR099961	PL:illumina	PU:ILLUMINA	LB:Solexa-50813	SM:HG00120	CN:bi

And I am using the command 
sudo python addsnv.py -v */SNP_BAMsurgeon_Tumour15.bed -f */HG00120.mapped.illumina.mosaik.GBR.exome.20110411.bam -r */mutatedbam.bam

Thanks again :)

**Comment by adamewing** [comment]
Let's get the test working properly first ... from the error it looks like either samtools or bwa might not be installed properly. Can you check that running 'samtools' or 'bwa' works for the same user account you are using to run addsnv.py?

**Comment by nbl1027** [comment]
Yep they are installed okay I think. 

Program: samtools (Tools for alignments in the SAM format)
Version: 0.1.18 (r982:295)

Program: bwa (alignment via Burrows-Wheeler transformation)
Version: 0.7.15-r1142-dirty

**Comment by adamewing** [comment]
Hmm, you might try upgrading your samtools then to 1.3 which is the latest.

The reason I'm suggesting this is the error:
'''
os.rename(sortfn, bamfn)
OSError: [Errno 2] No such file or directory
'''

indicates there is an intermediate BAM file that is not being generated properly, which in this instance is done through bwa and samtools, hence my suspicion. Let me know if updating samtools helps at all...

**Comment by nbl1027** [comment]
Hi Adam!

I have updated Samtools and the test script now works but getting the same original error when I run addsnv.py. Making progress though :)!

**Comment by adamewing** [comment]
OK, good - next thing is validate your BAM file. I'm wondering if there are reads where the mate read is marked mapped but is actually unmapped as this could generate the `ValueError: reference_id -1 out of range 0<=tid<84` you are getting. If you're able, try using the ValidateSamFile tool from picard ([https://broadinstitute.github.io/picard/](https://broadinstitute.github.io/picard/)) to see if it throws any errors about the BAM structure.

**Comment by nbl1027** [comment]
Hi Adam, 

Thanks so much for your help! Got it working. Ran the ValidateSamTool and turned out there was missing mates so I removed all of those and now it is working perfect.

Thanks again!
Kirsty

**Comment by adamewing** [comment]
Excellent. Let me know if you run into another error down the track.

**Comment by olschu** [comment]
Hi Adam, 

I am getting a very similar error to Kirsty but I am not able to find anything to be wrong. The test_snv_bwamem.sh ran without any problems and also my bam file passes the samtools ValidateSamFile without errors. Do you have any idea what could have gone wrong in my case?

(I am working with yeast and thus couldn't run the test_snv_bwamem.sh with my actual reference genome; to run the test, I just used the reference genome in the test_data folder.)

Thank you very much for your help!

Olga


Here is what the header of my bam file looks like:

(snakemake) [olgas@juno bam]$ samtools view -H quotetest.q20.sorted_chrNumbers.bam
@HD	VN:1.3	SO:coordinate
@SQ	SN:1	LN:230218
@SQ	SN:2	LN:813184
@SQ	SN:3	LN:316620
@SQ	SN:4	LN:1531933
@SQ	SN:5	LN:576874
@SQ	SN:6	LN:270161
@SQ	SN:7	LN:1090940
@SQ	SN:8	LN:562643
@SQ	SN:9	LN:439888
@SQ	SN:10	LN:745751
@SQ	SN:11	LN:666816
@SQ	SN:12	LN:1078177
@SQ	SN:13	LN:924431
@SQ	SN:14	LN:784333
@SQ	SN:15	LN:1091291
@SQ	SN:16	LN:948066
@SQ	SN:17	LN:85779
@RG	ID:1	SM:Mfa-lo_S3	PL:ILLUMINA	LB:lib1
@PG	ID:bwa	PN:bwa	VN:0.7.15-r1140	CL:bwa mem -t 12 -M -R @RG\tID:1\tSM:Mfa-lo_S3\tPL:ILLUMINA\tLB:lib1 /home/olgas/genomes/S288C_reference_genome_R64-1-1_20110203_new/SGD_20110203_OS_chrNumbers.fasta ../../../phenotypeSequencing/data/fastq/Mfa1-lo_S3.trimmed_Q20.fastq



And here is the error message I got from BAMSurgeon:

(snakemake) [olgas@juno bam]$ ~/miniconda3/envs/python27/bin/addsnv.py -f quotetest.q20.sorted_chrNumbers.bam -v ../mutations/BAMSurgeon_input_loci10_freq0100_chrNumbers.txt -r /home/olgas/genomes/S288C_reference_genome_R64-1-1_20110203_new/SGD_20110203_OS_chrNumbers.fasta -o quotetest_bamsurgeon.bam --mindepth 10 --maxdepth 300 --ignoresnps --force --picardjar ~/miniconda3/envs/python27/share/picard-2.7.1-0/picard.jar --aligner mem --procs 2 --seed 1234 --maxopen 1000
INFO	2016-12-15 22:45:41.540977	starting /home/olgas/miniconda3/envs/python27/bin/addsnv.py called with args: /home/olgas/miniconda3/envs/python27/bin/addsnv.py -f quotetest.q20.sorted_chrNumbers.bam -v ../mutations/BAMSurgeon_input_loci10_freq0100_chrNumbers.txt -r /home/olgas/genomes/S288C_reference_genome_R64-1-1_20110203_new/SGD_20110203_OS_chrNumbers.fasta -o quotetest_bamsurgeon.bam --mindepth 10 --maxdepth 300 --ignoresnps --force --picardjar /home/olgas/miniconda3/envs/python27/share/picard-2.7.1-0/picard.jar --aligner mem --procs 2 --seed 1234 --maxopen 1000

Debug, haploclusters:[[{'start': 100000, 'end': 100000, 'chrom': '5', 'altbase': 'T', 'vaf': 0.1}], [{'start': 200000, 'end': 200000, 'chrom': '5', 'altbase': 'C', 'vaf': 0.1}]]
INFO	2016-12-15 22:45:41.569337	haplo_5_100000_100000	creating tmp bam:  addsnv.tmp/haplo_5_100000_100000.tmpbam.26ccb6d0-b193-40fd-ae6b-2fc9e3322d12.bam
INFO	2016-12-15 22:45:41.569552	haplo_5_200000_200000	creating tmp bam:  addsnv.tmp/haplo_5_200000_200000.tmpbam.6333b086-6f0e-4059-8c93-4b357e77371f.bam
************************************************************
ERROR	2016-12-15 22:45:43.420808	encountered error in mutation spikein: ['5_200000_200000_0.1_C']
Traceback (most recent call last):
  File "/home/olgas/miniconda3/envs/python27/lib/python2.7/site-packages/bamsurgeon-1.0-py2.7.egg/EGG-INFO/scripts/addsnv.py", line 156, in makemut
  File "build/bdist.linux-x86_64/egg/bamsurgeon/mutation.py", line 186, in mutate
    mate = find_mate(pread.alignment, bammate)
  File "build/bdist.linux-x86_64/egg/bamsurgeon/mutation.py", line 121, in find_mate
    chrom = read.next_reference_name
  File "pysam/calignedsegment.pyx", line 941, in pysam.calignedsegment.AlignedSegment.next_reference_name.__get__ (pysam/calignedsegment.c:11814)
  File "pysam/calignmentfile.pyx", line 1654, in pysam.calignmentfile.AlignmentFile.getrname (pysam/calignmentfile.c:18212)
  File "pysam/calignmentfile.pyx", line 679, in pysam.calignmentfile.AlignmentFile.get_reference_name (pysam/calignmentfile.c:9078)
ValueError: reference_id -1 out of range 0<=tid<17
************************************************************
************************************************************
ERROR	2016-12-15 22:45:43.920696	encountered error in mutation spikein: ['5_100000_100000_0.1_T']
Traceback (most recent call last):
  File "/home/olgas/miniconda3/envs/python27/lib/python2.7/site-packages/bamsurgeon-1.0-py2.7.egg/EGG-INFO/scripts/addsnv.py", line 156, in makemut
  File "build/bdist.linux-x86_64/egg/bamsurgeon/mutation.py", line 186, in mutate
    mate = find_mate(pread.alignment, bammate)
  File "build/bdist.linux-x86_64/egg/bamsurgeon/mutation.py", line 121, in find_mate
    chrom = read.next_reference_name
  File "pysam/calignedsegment.pyx", line 941, in pysam.calignedsegment.AlignedSegment.next_reference_name.__get__ (pysam/calignedsegment.c:11814)
  File "pysam/calignmentfile.pyx", line 1654, in pysam.calignmentfile.AlignmentFile.getrname (pysam/calignmentfile.c:18212)
  File "pysam/calignmentfile.pyx", line 679, in pysam.calignmentfile.AlignmentFile.get_reference_name (pysam/calignmentfile.c:9078)
ValueError: reference_id -1 out of range 0<=tid<17
************************************************************
INFO	2016-12-15 22:45:43.925744	no succesful mutations

**Comment by jhl667** [comment]
@olschu What happens if you don't include read groups in your header (@rg)?  For me, this was a difference between whether or not the ValueError was raised.  I kind of figured it was because I am using a little bit older version of pysam, so just worked around it.  Is this related, @adamewing?

**Comment by olschu** [comment]
Thanks for your message @jhl667. For me the problem turned out to be that I had a single-end BAM file and adding the --single option to the addsnv.py command solved the problem.

Best,
Olga
