### ISSUE TITLE
Picard prerequisite

### ISSUE THREAD

**Issue by datakid** [adamewing/bamsurgeon#76]
Picard is now up to 2.7.0.

Is there a reason why 1.131 is chosen instead of, at least, 1.141 (the last to support Java 1.7, if that's what you need).

There are almost 180 changes between 131 and 141. 500+ changes bn 131 and 2.7.0

**Comment by adamewing** [comment]
The only bit of Picard that BS currently uses is SamToFastq for a subset of alignment methods. 1.131 is admittedly arbitrary and the intention is >= 1.131. Is the setup failing on 2.7.0?

Really I should get rid of this dep altogether and just use python function for BAM-->fastq...

**Comment by datakid** [comment]
No, it's not failing to my knowledge - I have no idea how to run your software. I'm the sysadmin - I don't steer, I just make the engine go :) I'll try with the latest version then.

**Comment by adamewing** [comment]
OK, gotcha. Let me know if it breaks.
