### ISSUE TITLE
mate not found while using addsnv.py

### ISSUE THREAD

**Issue by PaolaD** [adamewing/bamsurgeon#77]
Hi Adam,
i'm trying to spike in SNVs mutations in the NA12878 bam file derived from 1000Genomes, in particular the exome realigned to the GRCh38DH human assembly and the illumina platinum pedigree genome.
This is the input:
python /path/to/bamsurgeon/bamsurgeon-master/bin/addsnv.py -v regions.bed -f NA12878.alt_bwamem_GRCh38DH.20150826.CEU.exome.srt.bam -r GRCh38_full_analysis_set_plus_decoy_hla.fa -o output.bam -s 0.1 -m 0.5 --aligner mem --alignopts t:1,B:4,O:6,E:1,M: --picardjar /opt/tools/picard-tools-1.140/picard.jar --tagreads
And this is what happens:
INFO    2016-10-19 10:07:00.965334      haplo_chr1_2604262_2604262      creating tmp bam:  addsnv.tmp/haplo_chr1_2604262_2604262.tmpbam         .2ce674c7-436d-442d-b2d2-b943d072335c.bamINFO   2016-10-19 10:07:00.965334      haplo_chr1_3756813_3756813      creating tmp bam:
 addsnv.tmp/haplo_chr1_3756813_3756813.tmpbam.794a4f15-2f2f-4314-bd26-9a334193e4ed.bam
INFO    2016-10-19 10:07:00.965757      haplo_chr1_6254008_6254008      creating tmp bam:  addsnv.tmp/haplo_chr1_6254008_6254008.tmpbam         .35974f03-463a-4bc0-8be3-b0a5c4ebc0b1.bam
INFO    2016-10-19 10:07:00.965882      haplo_chr1_8015351_8015351      creating tmp bam:  addsnv.tmp/haplo_chr1_8015351_8015351.tmpbam         .75982e73-85fa-4517-bc34-e2facc9e5ea5.bam
INFO    2016-10-19 10:07:00.965947      haplo_chr1_3844974_3844974      creating tmp bam:  addsnv.tmp/haplo_chr1_3844974_3844974.tmpbam         .07f20227-6940-4d61-8df2-8de9b952b67c.bam
INFO    2016-10-19 10:07:00.968445      haplo_chr1_1668397_1668397      creating tmp bam:  addsnv.tmp/haplo_chr1_1668397_1668397.tmpbam         .0f0c1948-f969-4816-bf2d-a0d551625e4b.bam
INFO    2016-10-19 10:07:00.974558      haplo_chr1_8422758_8422758      creating tmp bam:  addsnv.tmp/haplo_chr1_8422758_8422758.tmpbam         .e0133028-2f07-4e7b-81af-58c24bda375f.bam
WARN    2016-10-19 10:07:01.605163      haplo_chr1_1668397_1668398      dropped for proximity to SNP, nearby SNP MAF: 0.25625 (max snv          frac: 0.1)
WARN    2016-10-19 10:07:01.860107      chr1_6253717_6254147_None_None  warning: no mate for SRR098401.8225801
WARN    2016-10-19 10:07:01.864627      chr1_3844906_3844983_None_None  warning: no mate for SRR1517848.5321
WARN    2016-10-19 10:07:01.865476      chr1_3844906_3844983_None_None  warning: no mate for SRR098401.87905115
WARN    2016-10-19 10:07:01.870470      chr1_3844906_3844983_None_None  warning: no mate for SRR1518151.5881
WARN    2016-10-19 10:07:01.871256      chr1_3844906_3844983_None_None  warning: no mate for SRR1517848.5326
WARN    2016-10-19 10:07:01.872458      chr1_3844906_3844983_None_None  warning: no mate for SRR098401.17828958
WARN    2016-10-19 10:07:01.873968      chr1_3844906_3844983_None_None  warning: no mate for SRR1517974.5815
WARN    2016-10-19 10:07:01.876574      chr1_3844906_3844983_None_None  warning: no mate for SRR098401.730667
WARN    2016-10-19 10:07:01.877116      chr1_1668326_1668472_None_None  warning: no mate for SRR1517991.2930
WARN    2016-10-19 10:07:01.878038      chr1_1668326_1668472_None_None  warning: no mate for SRR098401.21076287
WARN    2016-10-19 10:07:01.878261      chr1_3844906_3844983_None_None  warning: no mate for SRR098401.18771219
WARN    2016-10-19 10:07:01.878517      chr1_6253717_6254147_None_None  warning: no mate for SRR098401.29619889
WARN    2016-10-19 10:07:01.878564      chr1_3844906_3844983_None_None  warning: no mate for SRR098401.26323221
WARN    2016-10-19 10:07:01.880482      chr1_3844906_3844983_None_None  warning: no mate for SRR098401.67518704
WARN    2016-10-19 10:07:01.881927      chr1_1668326_1668472_None_None  warning: no mate for SRR098401.84773996
WARN    2016-10-19 10:07:01.882513      chr1_1668326_1668472_None_None  warning: no mate for SRR1517968.3393
WARN    2016-10-19 10:07:01.883274      chr1_1668326_1668472_None_None  warning: no mate for SRR098401.45180288
WARN    2016-10-19 10:07:01.884434      chr1_1668326_1668472_None_None  warning: no mate for SRR098401.78156498
WARN    2016-10-19 10:07:01.884514      chr1_3844906_3844983_None_None  warning: no mate for SRR098401.102934682
WARN    2016-10-19 10:07:01.884730      chr1_1668326_1668472_None_None  warning: no mate for SRR098401.44119978
WARN    2016-10-19 10:07:01.886218      chr1_3844906_3844983_None_None  warning: no mate for SRR1517974.5814
WARN    2016-10-19 10:07:01.886530      chr1_3844906_3844983_None_None  warning: no mate for SRR098401.27337592
WARN    2016-10-19 10:07:01.886733      chr1_1668326_1668472_None_None  warning: no mate for SRR098401.88631178
WARN    2016-10-19 10:07:01.886832      chr1_3844906_3844983_None_None  warning: no mate for SRR1517938.5944
It gaves me this warning for every chromosome and when the process ends the output bam doesn't have any mutation.
I've got the latest version of  pysam and samtools installed except for picard-tools. 
I was wondering if the problem is that BamSurgeon doesn't support GRCh38? or if the problem may be picard?

**Comment by adamewing** [comment]
To get started, could you let me know whether running ValidateSamFile from the Picard tool set yields any errors for your input BAM?

GRCh38 is mostly supported through the work of a collaborator, there may be some fiddly things with alt loci that still don't get picked up but that doesn't look like what's happening here at first glance - what I want to verify first is whether there are really mates missing from the input.

**Comment by PaolaD** [comment]
yes,it actually gives me this error:
To get help, see http://broadinstitute.github.io/picard/index.html#GettingHelp
Exception in thread "main" htsjdk.samtools.SAMException: Value was put into PairInfoMap more than once.  3073: SRR1517848.769506
        at htsjdk.samtools.CoordinateSortedPairInfoMap.ensureSequenceLoaded(CoordinateSortedPairInfoMap.java:132)
        at htsjdk.samtools.CoordinateSortedPairInfoMap.access$300(CoordinateSortedPairInfoMap.java:53)
        at htsjdk.samtools.CoordinateSortedPairInfoMap$MapIterator.advanceToNextNonEmptyReferenceIndex(CoordinateSortedPairInfoMap.java:227)
        at htsjdk.samtools.CoordinateSortedPairInfoMap$MapIterator.<init>(CoordinateSortedPairInfoMap.java:221)
        at htsjdk.samtools.CoordinateSortedPairInfoMap$MapIterator.<init>(CoordinateSortedPairInfoMap.java:211)
        at htsjdk.samtools.CoordinateSortedPairInfoMap.iterator(CoordinateSortedPairInfoMap.java:208)
        at htsjdk.samtools.SamFileValidator$CoordinateSortedPairEndInfoMap.iterator(SamFileValidator.java:728)
        at htsjdk.samtools.SamFileValidator.validateUnmatchedPairs(SamFileValidator.java:227)
        at htsjdk.samtools.SamFileValidator.validateSamFile(SamFileValidator.java:200)
        at htsjdk.samtools.SamFileValidator.validateSamFileSummary(SamFileValidator.java:127)
        at picard.sam.ValidateSamFile.doWork(ValidateSamFile.java:163)
        at picard.cmdline.CommandLineProgram.instanceMain(CommandLineProgram.java:209)
        at picard.cmdline.PicardCommandLine.instanceMain(PicardCommandLine.java:95)
        at picard.cmdline.PicardCommandLine.main(PicardCommandLine.java:105)

**Comment by PaolaD** [comment]
I solved the problem, thank you Adam.
