### ISSUE TITLE
'pysam.calignmentfile.AlignedSegment' object has no attribute 'next_reference_name'

### ISSUE THREAD

**Issue by sheilazt** [adamewing/bamsurgeon#79]
Dear users,
I'm trying to perform Bamsurgeon's tests for snvs but I get the following error message.

$ ./test_snv.sh 4 5 /data/references/human/genome/GRCh37_hg19/hg19_wochrs.fasta
addsnv.py -v ../test_data/random_snvs.txt -f ../test_data/testregion_realign.bam -r /data/references/human/genome/GRCh37_hg19/hg19_wochrs.fasta -o ../test_data/testregion_mut.bam -n 4 -p 5 --ignoresnps --ignorepileup --seed 1234

INFO	2016-11-07 05:34:06.947648	starting /usr/local/bin/addsnv.py called with args: /usr/local/bin/addsnv.py -v ../test_data/random_snvs.txt -f ../test_data/testregion_realign.bam -r /data/references/human/genome/GRCh37_hg19/hg19_wochrs.fasta -o ../test_data/testregion_mut.bam -n 4 -p 5 --ignoresnps --ignorepileup --seed 1234

Debug, haploclusters:[[{'start': 33714964, 'end': 33714965, 'chrom': '22', 'altbase': None, 'vaf': None}], [{'start': 33769483, 'end': 33769484, 'chrom': '22', 'altbase': None, 'vaf': None}], [{'start': 33908770, 'end': 33908771, 'chrom': '22', 'altbase': None, 'vaf': None}], [{'start': 34166720, 'end': 34166721, 'chrom': '22', 'altbase': None, 'vaf': None}]]
INFO	2016-11-07 05:34:07.043328	haplo_22_33714965_33714965	creating tmp bam:  addsnv.tmp/haplo_22_33714965_33714965.tmpbam.b7077202-4470-4165-be96-01367e35cd4a.bam
INFO	2016-11-07 05:34:07.043409	haplo_22_33769483_33769483	creating tmp bam:  addsnv.tmp/haplo_22_33769483_33769483.tmpbam.2466f7b7-9fe6-45b1-af2c-cce8598c9a13.bam
INFO	2016-11-07 05:34:07.043451	haplo_22_33908770_33908770	creating tmp bam:  addsnv.tmp/haplo_22_33908770_33908770.tmpbam.de40905a-9b29-4c56-8da1-d999c6f6a133.bam
INFO	2016-11-07 05:34:07.043542	haplo_22_34166721_34166721	creating tmp bam:  addsnv.tmp/haplo_22_34166721_34166721.tmpbam.76575af3-18ec-4099-878c-3b8eb073420a.bam
************************************************************
ERROR	2016-11-07 05:34:07.345068	encountered error in mutation spikein: ['22_33769483_33769484_None_None']
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/bamsurgeon-1.0-py2.7.egg/EGG-INFO/scripts/addsnv.py", line 156, in makemut
  File "build/bdist.linux-x86_64/egg/bamsurgeon/mutation.py", line 186, in mutate
    mate = find_mate(pread.alignment, bammate)
  File "build/bdist.linux-x86_64/egg/bamsurgeon/mutation.py", line 121, in find_mate
    chrom = read.next_reference_name
AttributeError: 'pysam.calignmentfile.AlignedSegment' object has no attribute 'next_reference_name'
************************************************************
************************************************************
ERROR	2016-11-07 05:34:07.441006	encountered error in mutation spikein: ['22_34166720_34166721_None_None']
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/bamsurgeon-1.0-py2.7.egg/EGG-INFO/scripts/addsnv.py", line 156, in makemut
  File "build/bdist.linux-x86_64/egg/bamsurgeon/mutation.py", line 186, in mutate
    mate = find_mate(pread.alignment, bammate)
  File "build/bdist.linux-x86_64/egg/bamsurgeon/mutation.py", line 121, in find_mate
    chrom = read.next_reference_name
AttributeError: 'pysam.calignmentfile.AlignedSegment' object has no attribute 'next_reference_name'
************************************************************
************************************************************
ERROR	2016-11-07 05:34:07.541356	encountered error in mutation spikein: ['22_33908770_33908771_None_None']
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/bamsurgeon-1.0-py2.7.egg/EGG-INFO/scripts/addsnv.py", line 156, in makemut
  File "build/bdist.linux-x86_64/egg/bamsurgeon/mutation.py", line 186, in mutate
    mate = find_mate(pread.alignment, bammate)
  File "build/bdist.linux-x86_64/egg/bamsurgeon/mutation.py", line 121, in find_mate
    chrom = read.next_reference_name
AttributeError: 'pysam.calignmentfile.AlignedSegment' object has no attribute 'next_reference_name'
************************************************************
************************************************************
ERROR	2016-11-07 05:34:07.624716	encountered error in mutation spikein: ['22_33714964_33714965_None_None']
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/bamsurgeon-1.0-py2.7.egg/EGG-INFO/scripts/addsnv.py", line 156, in makemut
  File "build/bdist.linux-x86_64/egg/bamsurgeon/mutation.py", line 186, in mutate
    mate = find_mate(pread.alignment, bammate)
  File "build/bdist.linux-x86_64/egg/bamsurgeon/mutation.py", line 121, in find_mate
    chrom = read.next_reference_name
AttributeError: 'pysam.calignmentfile.AlignedSegment' object has no attribute 'next_reference_name'
************************************************************
INFO	2016-11-07 05:34:07.654180	no succesful mutations
Note: none of --samples-file, --ploidy or --ploidy-file given, assuming all sites are diploid
[E::hts_open_format] fail to open file '../test_data/testregion_mut.bam'
[mpileup] failed to open ../test_data/testregion_mut.bam: No such file or directory
Failed to open -: unknown file type

Any help would be much appreciated.

Best regards,

Sheila

**Comment by adamewing** [comment]
It looks like you're using an older version of pysam. Upgrade with `pip install -U pysam` or try running `python setup.py install` from the bamsurgeon root directory.

**Comment by sheilazt** [comment]
python setup.py install --upgrade  
made the job :+1: 

Thanks very much for your help.

Sheila

**Comment by adamewing** [comment]
Great!
