### ISSUE TITLE
OSError from call to subprocess

### ISSUE THREAD

**Issue by lilseo** [adamewing/bamsurgeon#80]
Hi there,

I have seen other people having similar issues to this, but haven't been able to resolve mine after reading those threads. I am encountering this error with both my own files and test_addindel. I am running: 

python addindel.py -v ../test_data/test_indels.txt -f ../test_data/testregion_realign.bam  -r ../test_data/Homo_sapiens_chr22_assembly19.fasta -o ../test_data/testregion_mut.bam -c ../test_data/test_cnvlist.txt.gz --seed 1234

And am getting this error for all attempted spikeins: 

encountered error in mutation spikein: 22_33958087_33958090_0.4:DEL
Traceback (most recent call last):
  File "addindel.py", line 119, in makemut
    mutfail, hasSNP, maxfrac, outreads, mutreads, mutmates = mutation.mutate(args, log, bamfile, bammate, chrom, mutpos, mutpos+del_ln+1, mutpos_list, avoid=avoid, mutid_list=[mutid], is_insertion=is_insertion, is_deletion=is_deletion, ins_seq=ins, reffile=reffile, indel_start=start, indel_end=end)
  File "/home/junzli_lab/lilseo/strfinder/BAMSurgeon/bamsurgeon/mutation.py", line 208, in mutate
    basepile = countBaseAtPos(args.bamFileName,chrom,pcol.pos,mutid=region)
  File "/home/junzli_lab/lilseo/strfinder/BAMSurgeon/bamsurgeon/mutation.py", line 14, in countBaseAtPos
    p = subprocess.Popen(args, stdout=subprocess.PIPE, stderr=subprocess.PIPE)
  File "/usr/local/mbni/garage/junzli_lab/Python-2.7.3/lib/python2.7/subprocess.py", line 679, in __init__
    errread, errwrite)
  File "/usr/local/mbni/garage/junzli_lab/Python-2.7.3/lib/python2.7/subprocess.py", line 1249, in _execute_child
    raise child_exception
OSError: [Errno 2] No such file or directory

You said in another thread that you shouldn't have to use shell=True for subprocess. How else can I resolve this OSError? 
____________________________________________________________________________________________________________
To temporarily patch over this, I added shell=True to all subprocess calls. Upon running with this change, I saw that there were some reads being mutated but zero being written. For example: 

INFO	2016-11-10 09:54:12.576521	22_33694303_33694304_0.5:INS:ATGGC	copy number in snp region: 22 33694303 33694304 = 3.0
INFO	2016-11-10 09:54:12.576582	22_33694303_33694304_0.5:INS:ATGGC	adjusted VAF: 0.333333333333
INFO	2016-11-10 09:54:12.576752	22_33694303_33694304_0.5:INS:ATGGC	picked: 18 reads
INFO	2016-11-10 09:54:12.577711	22_33694303_33694304_0.5:INS:ATGGC	wrote: 0 reads, mutated: 18 read

To circumvent this, I ran it with --force, and proceeded to get another OSError, this time raised by os.rename as follows: 

encountered error in mutation spikein: 22_33694303_33694304_0.5:INS:ATGGC
Traceback (most recent call last):
  File "addindel.py", line 238, in makemut
    aligners.remap_bam(args.aligner, tmpoutbamname, args.refFasta, alignopts, mutid=mutid, paired=(not args.single), picardjar=args.picardjar)
  File "/home/junzli_lab/lilseo/strfinder/BAMSurgeon/bamsurgeon/aligners.py", line 59, in remap_bam
    remap_backtrack_bam(bamfn, threads, fastaref, mutid=mutid, paired=paired)
  File "/home/junzli_lab/lilseo/strfinder/BAMSurgeon/bamsurgeon/aligners.py", line 125, in remap_backtrack_bam
    os.rename(sortfn, bamfn)
OSError: [Errno 2] No such file or directory

I'm not sure if the latter 2 issues are related to the subprocess/shell issue, which is why I thought I'd also ask about them. Let me know if anything is unclear. Thank you in advance for your help!

**Comment by adamewing** [comment]
Hi, could you double-check that `samtools` is installed and in your $PATH?

**Comment by lilseo** [comment]
Just checked that and indeed, samtools was not in my $PATH. However, I added it to $PATH and re-ran, and am still getting the same OSError from os.rename: 

INFO	2016-11-11 09:46:39.523256	22_33694303_33694304_0.5:INS:ATGGC	creating tmp bam:  addindel.tmp/22_33694303_33694304_0.5:INS:ATGGC.tmpbam.7c074b3c-5413-404b-82f6-6c98317e3be9.bam
len(readlist): 56
INFO	2016-11-11 09:46:46.055279	22_33694303_33694304_0.5:INS:ATGGC	copy number in snp region: 22 33694303 33694304 = 3.0
INFO	2016-11-11 09:46:46.055356	22_33694303_33694304_0.5:INS:ATGGC	adjusted VAF: 0.333333333333
INFO	2016-11-11 09:46:46.055601	22_33694303_33694304_0.5:INS:ATGGC	picked: 18 reads
INFO	2016-11-11 09:46:46.057421	22_33694303_33694304_0.5:INS:ATGGC	wrote: 57 reads, mutated: 18 reads
INFO	2016-11-11 09:46:46.061694	22_33694303_33694304_0.5:INS:ATGGC	mapping 1st end, cmd: bwa aln ../test_data/Homo_sapiens_chr22_assembly19.fasta -q 5 -l 32 -k 3 -t 1 -o 1 -f addindel.tmp/22_33694303_33694304_0.5:INS:ATGGC.tmpbam.7c074b3c-5413-404b-82f6-6c98317e3be9.bam.1.sai -b1 addindel.tmp/22_33694303_33694304_0.5:INS:ATGGC.tmpbam.7c074b3c-5413-404b-82f6-6c98317e3be9.bam
aln: bwa: command not found
INFO	2016-11-11 09:46:46.086637	22_33694303_33694304_0.5:INS:ATGGC	mapping 2nd end, cmd: bwa aln ../test_data/Homo_sapiens_chr22_assembly19.fasta -q 5 -l 32 -k 3 -t 1 -o 1 -f addindel.tmp/22_33694303_33694304_0.5:INS:ATGGC.tmpbam.7c074b3c-5413-404b-82f6-6c98317e3be9.bam.2.sai -b2 addindel.tmp/22_33694303_33694304_0.5:INS:ATGGC.tmpbam.7c074b3c-5413-404b-82f6-6c98317e3be9.bam
aln: bwa: command not found
INFO	2016-11-11 09:46:46.106918	22_33694303_33694304_0.5:INS:ATGGC	pairing ends, building .sam, cmd: bwa sampe -P -f addindel.tmp/22_33694303_33694304_0.5:INS:ATGGC.tmpbam.7c074b3c-5413-404b-82f6-6c98317e3be9.bam.sam ../test_data/Homo_sapiens_chr22_assembly19.fasta addindel.tmp/22_33694303_33694304_0.5:INS:ATGGC.tmpbam.7c074b3c-5413-404b-82f6-6c98317e3be9.bam.1.sai addindel.tmp/22_33694303_33694304_0.5:INS:ATGGC.tmpbam.7c074b3c-5413-404b-82f6-6c98317e3be9.bam.2.sai addindel.tmp/22_33694303_33694304_0.5:INS:ATGGC.tmpbam.7c074b3c-5413-404b-82f6-6c98317e3be9.bam addindel.tmp/22_33694303_33694304_0.5:INS:ATGGC.tmpbam.7c074b3c-5413-404b-82f6-6c98317e3be9.bam
sampe: bwa: command not found
INFO	2016-11-11 09:46:46.125634	22_33694303_33694304_0.5:INS:ATGGC	sam --> bam, cmd: samtools view -bt ../test_data/Homo_sapiens_chr22_assembly19.fasta.fai -o addindel.tmp/22_33694303_33694304_0.5:INS:ATGGC.tmpbam.7c074b3c-5413-404b-82f6-6c98317e3be9.bam addindel.tmp/22_33694303_33694304_0.5:INS:ATGGC.tmpbam.7c074b3c-5413-404b-82f6-6c98317e3be9.bam.sam

Program: samtools (Tools for alignments in the SAM format)
Version: 0.1.18 (r982:295)

Usage:   samtools <command> [options]

Command: view        SAM<->BAM conversion
         sort        sort alignment file
         mpileup     multi-way pileup
         depth       compute the depth
         faidx       index/extract FASTA
         tview       text alignment viewer
         index       index alignment
         idxstats    BAM index stats (r595 or later)
         fixmate     fix mate information
         flagstat    simple stats
         calmd       recalculate MD/NM tags and '=' bases
         merge       merge sorted alignments
         rmdup       remove PCR duplicates
         reheader    replace BAM header
         cat         concatenate BAMs
         targetcut   cut fosmid regions (for fosmid pool only)
         phase       phase heterozygotes

INFO	2016-11-11 09:46:46.159175	22_33694303_33694304_0.5:INS:ATGGC	sorting, cmd: samtools sort -m 10000000000 -T addindel.tmp/22_33694303_33694304_0.5:INS:ATGGC.tmpbam.7c074b3c-5413-404b-82f6-6c98317e3be9.bam.sort.bam -o addindel.tmp/22_33694303_33694304_0.5:INS:ATGGC.tmpbam.7c074b3c-5413-404b-82f6-6c98317e3be9.bam.sort.bam addindel.tmp/22_33694303_33694304_0.5:INS:ATGGC.tmpbam.7c074b3c-5413-404b-82f6-6c98317e3be9.bam

Program: samtools (Tools for alignments in the SAM format)
Version: 0.1.18 (r982:295)

Usage:   samtools <command> [options]

Command: view        SAM<->BAM conversion
         sort        sort alignment file
         mpileup     multi-way pileup
         depth       compute the depth
         faidx       index/extract FASTA
         tview       text alignment viewer
         index       index alignment
         idxstats    BAM index stats (r595 or later)
         fixmate     fix mate information
         flagstat    simple stats
         calmd       recalculate MD/NM tags and '=' bases
         merge       merge sorted alignments
         rmdup       remove PCR duplicates
         reheader    replace BAM header
         cat         concatenate BAMs
         targetcut   cut fosmid regions (for fosmid pool only)
         phase       phase heterozygotes
************************************************************
encountered error in mutation spikein: 22_33694303_33694304_0.5:INS:ATGGC
Traceback (most recent call last):
  File "addindel.py", line 238, in makemut
    aligners.remap_bam(args.aligner, tmpoutbamname, args.refFasta, alignopts, mutid=mutid, paired=(not args.single), picardjar=args.picardjar)
  File "/home/junzli_lab/lilseo/strfinder/BAMSurgeon/bamsurgeon/aligners.py", line 59, in remap_bam
    remap_backtrack_bam(bamfn, threads, fastaref, mutid=mutid, paired=paired)
  File "/home/junzli_lab/lilseo/strfinder/BAMSurgeon/bamsurgeon/aligners.py", line 124, in remap_backtrack_bam
    os.rename(sortfn, bamfn)
OSError: [Errno 2] No such file or directory
************************************************************

**Comment by adamewing** [comment]
Hi again, looks to me like `bwa` is not installed. (I'm seeing "bwa: command not found" in your output). If you haven't already done so, please go through the 'External Prerequisites' section of the readme page and ensure that everything on there is installed.

**Comment by lilseo** [comment]
Hello again, yes sorry, something on our cluster changed and I forgot to put bwa pack into $PATH. I just amended that and am no longer getting the "bwa: command not found" lines.  However, I am still getting the same os.rename OSError as above..

Thank you again for all of your help. If it would be easier for you, should I email you the output I'm getting? Or continue posting it here?

**Comment by adamewing** [comment]
The final error message is the same but the rest of the message indicates we're making progress. The place where things start to fail now is: `[bwt_restore_bwt] fail to open file '../test_data/Homo_sapiens_chr22_assembly19.fasta.rbwt'. Abort!`

What command are you running and what folder are you in? Is ../test_data in your relative path?

You can continue posting here, it might be helpful to other users having similar problems.

**Comment by lilseo** [comment]
I'm running the following command from BAMSurgeon/bin/ : 
 python2.7 addindel.py -v ../test_data/test_indels.txt -f ../test_data/testregion_realign.bam -r ../test_data/Homo_sapiens_chr22_assembly19.fasta -o ../test_data/testregion_mut.bam -c ../test_data/test_cnvlist.txt.gz --seed 1234 --force

So ../test_data should be in my relative path...

**Comment by lilseo** [comment]
Update 2: I resolved all the issues arising from BWA and Samtools! I will follow up shortly with what I tweaked, in case others encounter similar issues.

Adam, one last question. At the end of my output for the test_indel data, I get the following: 
INFO	2016-11-15 12:53:04.452345	done making mutations, merging mutations into ../test_data/testregion_realign.bam --> ../test_data/testregion_mut.bam
loading donor reads into dictionary...
secondary reads count:0
supplementary reads count:0
loaded 650 reads, (0 excluded, 0 null or secondary or supplementary--> ignored)
replaced 650 reads (0 excluded )
kept 0 secondary reads.
kept 0 supplementary reads.

Could you briefly explain with the last two lines (0 secondary reads, 0 supplementary reads) mean? Thanks so much again for all of your help.

**Comment by adamewing** [comment]
Great!

The two lines you're asking about will generally be 0 unless you're running replacereads.py manually with either --keepsecondary or --keepsupplementary set. Secondary/supplementary reads are ways of expressing alternate alignments in BAM format.
