### ISSUE TITLE
Mutated reads not being added to bam? 

### ISSUE THREAD

**Issue by lilseo** [adamewing/bamsurgeon#81]
Hello again,

You helped me before to finally get addindel running, but after running my post-bamsurgeon BAM file through a program that detects expansive repeats, I began to question whether the BAM actually contained the mutated reads. I ran bamsurgeon as follows: 
python2.7 ./addindel.py -v ../test_data/shortRepeats.txt -f input.bam -r human_g1k_v37.fasta -o ../test_data/shortRepeats_mut.bam --seed 1234 --ignorepileup 

I thought it was odd that the secondary program was catching virtually none of the insertions that I spiked-in using bamsurgeon, so I ran samtools view on the shortRepeats_mut.bam output file. It looks like the mutated reads contained in the .log files are not present in the output BAM. For example, I have a log that contains a mutated read starting at chr 22 coordinate 18445701 with a "GC" repeat expansion inserted (bolded below): 
read ST-E00144:74:H2KFLCCXX:1:1113:24233:26800,18445701,S AGAGACAGGGTCTCACTATGTTGCCCAG**GCGCGCGCGCGCGCGCGCGCGCGCGCGCGCGCGCGC**AGTCACGAACTCCTACCTTCAAGCAATCTTCCTGCCTCCGCCTCCCAAAGTGCTGAGACTAGAGGGGAGAGCCGCCACACCTAGCC

All the other log files for this particular GC-insertion support that other reads were successfully mutated as well. However when I try to find the mutated read in the shortRepeats_mut.bam file (using samtools view), I only find the un-mutated sequence at this position: 
22      18445701        TAGAGACAGGGTCTCACTATGTTGCCCAGGC**AGTCACGAACTCCTACCTTCAAGCAATCTTCCTGCCTCAGCCTCCCAAAGTGCTGAGATTAGAGGTGTGAGCCACCACACCTAGCCAGCGAGAAACACTTCTATTCCAATCAATCATCT
Note: I inserted a ** where the GC expansion should have been spiked-in.

Maybe I am misunderstanding something about bamsurgeon's functionality. Could you help explain what is going on here?

**Comment by adamewing** [comment]
Hi, could you paste the contents of shortRepeats.txt (or at least a selection of mutations that didn't show up)?

**Comment by lilseo** [comment]
Sure thing, here is just a snippet of the shortRepeats.txt file, with the top line being the insertion I refer to above. 

22 18445730 18445764 1.0 INS CGCGCGCGCGCGCGCGCGCGCGCGCGCGCGCGCG
22 30982600 30982619 1.0 INS AATAAAATAAAATAAAATA
22 29954753 29954765 1.0 INS GCGCGCGCGCGC
22 30249604 30249714 1.0 INS TTGGTTGGTTGGTTGGTTGGTTGGTTGGTTGGTTGGTTGGTTGGTTGGTTGGTTGGTTGGTTGGTTGGTTGGTTGGTTGGTTGGTTGGTTGGTTGGTTGGTTGGTTGGTT

**Comment by adamewing** [comment]
Thanks, will see what happens with these on my end. Also, what happens if you omit --ignorepileup? Are you sure there is coverage over the spikein positions in your input.bam file?

**Comment by lilseo** [comment]
Hmm, not sure. I will try running this without --ignorepileup and see how it differs, because you are probably correct in guessing that there's inadequate coverage in those positions. Thank you!

**Comment by lilseo** [comment]
Hi again, just checking back in. I re-examined my results from running test_indel to see if I observe this same lack of mutated reads in the resulting bam-- and from what I can tell, I am seeing the same effect. Executing test_indel gives six sets of log files (one for each indel spiked in); one such set of log files is in testregion_mut.bam.22_33920490_33920491.log, for the reads with the insertion ATTTGCTTAGCTGAGGGCTTAGGCTTAGCATGCGTA. Below is a screenshot of a subset of the logs, with the intended insertion highlighted.
![screen shot 2016-12-02 at 7 29 53 pm](https://cloud.githubusercontent.com/assets/11219522/20854899/cdd21408-b8c5-11e6-9a95-1380d4c6b1e8.png)

However, when I check the resulting bam file for these mutated reads, I see that some of the mutated reads were successfully added but many were not:
![screen shot 2016-12-02 at 7 32 40 pm](https://cloud.githubusercontent.com/assets/11219522/20854935/2636ec72-b8c6-11e6-8573-332d92212c9f.png)

Is this the expected performance?

**Comment by adamewing** [comment]
Hi,

Are you specifying a VAF for your mutations of < 1.0? This could be done either in your variant file (4th column) or via -s. Post the command-line you're using if it's any different than before.

I'm able to get a full-depth spikein for the four mutations you pasted a couple comments ago into a WGS BAM (NA12878) (example below), using the following command:

`addindel.py -v variants.txt -f NA12878.chr22.fixed.sorted.bam -r Homo_sapiens_assembly19.fasta -o lilseo.muts.bam -p 4 --picardjar picard.jar --aligner mem`

![22_18445730_18445764](https://cloud.githubusercontent.com/assets/1037202/20951990/e95e9edc-bc74-11e6-8f2b-27c236831148.png)

**Comment by lilseo** [comment]
In my variant file I specify a VAF of 1.0 for all mutations. Maybe I should try using a different WGS bam from the one I'm using, as I see some especially uneven coverage?

**Comment by adamewing** [comment]
Closing, feel free to reopen if there are still unresolved issues.
