### ISSUE TITLE
Java memory limitations causing variant discrepancies

### ISSUE THREAD

**Issue by muppetjones** [adamewing/bamsurgeon#83]
When I'm running bamsurgeon, I keep getting the following error:

```
#
# There is insufficient memory for the Java Runtime Environment to continue.
# Native memory allocation (mmap) failed to map 329777152 bytes for committing reserved memory.
# Possible reasons:
#   The system is out of physical RAM or swap space
#   In 32 bit mode, the process size limit was hit
# Possible solutions:
#   Reduce memory load on the system
#   Increase physical memory or swap space
#   Check if swap backing store is full
#   Use 64 bit Java on a 64 bit OS
#   Decrease Java heap size (-Xmx/-Xms)
#   Decrease number of Java threads
#   Decrease Java thread stack sizes (-Xss)
#   Set larger code cache with -XX:ReservedCodeCacheSize=
# This output file may be truncated or incomplete.
#
#  Out of Memory Error (os_linux.cpp:2627), pid=38715, tid=0x00007f7c9b62c700
#
# JRE version:  (8.0_121-b13) (build )
# Java VM: Java HotSpot(TM) 64-Bit Server VM (25.121-b13 mixed mode linux-amd64 compressed oops)
# Core dump written. Default location: /data/core or core.38715
#
```

I believe this must be due to the picardtools call, and could be easily fixed by setting `_JAVA_OPTIONS` or `JAVA_TOOLS_OPTIONS`, but because this is hardcoded to 4g in the `bam2fastq.py` script, it becomes a huge issue.

I am also seeing discrepancies in which variants are actually being inserted. For example, I have two variants, neither of which is inserted according to the log files; however, one of the variants is clearly inserted into the data. Both had the following error in the logs

` bam readcount < fastq readcount, alignment sanity check failed!`

and did not have the `snv ...` line at the end of the variant-specific log file.

I _think_ this is most likely due to the java issue.

**Comment by adamewing** [comment]
Ah, yes that -Xmx4g heap size request on the picard call is unnecessary. Removed in this commit: https://github.com/adamewing/bamsurgeon/commit/213bd11de2249c8cf9a1170c9ea3d8e85ccbc0f2

Let me know whether that clears this up, although I suspect you might have trouble getting this to run with under 4g memory, if that's your situation.

**Comment by muppetjones** [comment]
Thanks for the quick update!

Actually, I need more. I set it to `-Xmx16g`, reran the setup call, and still getting this error:
```
# There is insufficient memory for the Java Runtime Environment to continue.
# Native memory allocation (mmap) failed to map 329777152 bytes for committing reserved memory.
# Possible reasons:
#   The system is out of physical RAM or swap space
#   In 32 bit mode, the process size limit was hit
# Possible solutions:
#   Reduce memory load on the system
#   Increase physical memory or swap space
#   Check if swap backing store is full
#   Use 64 bit Java on a 64 bit OS
#   Decrease Java heap size (-Xmx/-Xms)
#   Decrease number of Java threads
#   Decrease Java thread stack sizes (-Xss)
#   Set larger code cache with -XX:ReservedCodeCacheSize=
# This output file may be truncated or incomplete.
#
#  Out of Memory Error (os_linux.cpp:2627), pid=31653, tid=0x00007f6b5253c700
```

The boxes I'm currently using have 60GiB RAM, so I could up it more, but the amount of missing memory is exactly the same, regardless of the `xm` value.

It seems to have some correlation with VAF. I'm running two samples at VAF 5, 15, and 25 (each on a different box). In the current run (mx16g), only VAF 5 (123 SNPs) completed successfully. In the previous run (mx4g), VAF 5 and VAF 15 (143 SNPs) completed successfully.

**Comment by adamewing** [comment]
Hm, that isn't something I've encountered previously - what picard version are you using? Can you convert your starting BAM to fastq with more reasonable memory requirements?

**Comment by adamewing** [comment]
Closing, feel free to reopen if there are still unresolved issues.
