### ISSUE TITLE
Final truth set

### ISSUE THREAD

**Issue by mozack** [adamewing/bamsurgeon#84]
Hi,

There appear to be cases where Bamsurgeon does not "spike in" all variants in the input variant file due to low/high coverage or the presence of an existing variant.

Is there a way to know what was actually spiked in?  i.e. What should be used as the downstream truth set?

Thanks!

**Comment by adamewing** [comment]
You should use the script in scripts/makevcf.py to generate an SNV "truth" VCF, scripts/makevcf_indels.py for indels, and scripts/makevcf_sv.py for SVs. Each requires you to specify the log directory for a TEBreak run as input in addition to a reference genome for the indel and SV scripts. Let me know if this is qhat you are after.

**Comment by mozack** [comment]
Thanks - the scripts are working well.
