### ISSUE TITLE
addsnv.py only adding one SNV out of multiple target regions

### ISSUE THREAD

**Issue by Nmael** [adamewing/bamsurgeon#89]
Hello,

I am running into an issue where `addsnv.py` only adds one SNV out of the input BED file. Specifically, it only adds the SNV with the greatest position value.

I'm attempting to modify a BAM with single-end reads simulated with `wgsim`, and I'm using the `bwa mem` aligner with `bamsurgeon`. I've included the BAM and its reference genome with this issue (it's the first 1,000 bases in the E. coli genome; `sim_wt.sorted.bam` and `NC_008253_1K.fna`, respectively), along with an example BED file (`snp.bed`) and the resulting output (`output.bam`) and STDOUT (`bamsurgeon.log`). [These files are all available in this .zip](https://github.com/adamewing/bamsurgeon/files/931367/attachment.zip). Please let me know if there's any other info I can provide!

The command I am running is:
`bamsurgeon addsnv.py --single --picardjar "<path to picard.jar>" --aligner mem -v snp.bed -f sim_wt.sorted.bam -r NC_008253_1K.fna -o output.bam --mindepth 0 -p 8 2>&1 >bamsurgeon.log`

The output file (`output.bam`) only shows a single SNV (A->T at position 20) despite having two SNVs in the input BED.

Thank you!

**Comment by adamewing** [comment]
Hi,

If your read length is shorter than the distance between two mutations in your input file you'll want to specify -z $READLEN. Here's an IGV shot of the output BAM from the following command:

addsnv.py --single --picardjar picard.jar --aligner mem -v snp.bed -f sim_wt.sorted.bam -r NC_008253_1K.fna -o output_z100.bam -z 100

![igv_snapshot](https://cloud.githubusercontent.com/assets/1037202/25158154/84487d3c-24e9-11e7-9774-df2a4435a002.png)

--Adam

**Comment by Nmael** [comment]
Thank you, Adam! That was indeed the problem; after setting `-z`, I now see all of the SNVs specified in my BED file.

Thanks again!

Nate
