### ISSUE TITLE
No successful mutations, fail to locate the index and no output 

### ISSUE THREAD

**Issue by pinkysaid** [adamewing/bamsurgeon#91]
Hello,

**Trying to insert mutations to a BAM file (sorted and indexed). I believe BAMSurgeon is properly installed and addsnv.py is in the path, but I keep getting this feedback.**

**I moved all the required files to one directory, ensured all the required modules are loaded (except pysam)
then went ahead to use an input -varfile comprising 5 columns (three column format plus additional columns with the VAF and specific base), but I'd get the error "Index Error: list index out of range". To circumvent this, I opted to stick to the 3-column format but still got the feedback below;**_

addsnv.py  -v simulated.variants.minimal.csv -f SIM_sample1.sorted.bam -r 9465113.fa -o test

INFO    2017-04-21 16:43:53.923843      starting /apps/python/2.7.8/bin/addsnv.py called with args: /apps/python/2.7.8/bin/addsnv.py -v simulated.variants.minimal.csv -f SIM_sample1.sorted.bam -r 9465113.fa -o test

INFO 2017-04-21 16:43:53.938570      created directory: addsnv_logs_test
Debug, haploclusters:[[{'start': 367, 'end': 367, 'chrom': '9465113', 'altbase': None, 'vaf': None}], [{'start': 458, 'end': 458, 'chrom': '9465113', 'altbase': None, 'vaf': None}], [{'start': 645, 'end': 645, 'chrom': '9465113', 'altbase': None, 'vaf': None}]]
INFO    2017-04-21 16:43:54.148952      haplo_9465113_367_367   creating tmp bam:  addsnv.tmp/haplo_9465113_367_367.tmpbam.e1bdd1f9-6f60-4542-a2c4-febe4979823d.bam
INFO    2017-04-21 16:44:00.998876      haplo_9465113_367_367   len(readlist): 7
WARN    2017-04-21 16:44:00.999040      haplo_9465113_367_367   too few reads in region (7) skipping...
INFO    2017-04-21 16:44:01.014152      haplo_9465113_458_458   creating tmp bam:  addsnv.tmp/haplo_9465113_458_458.tmpbam.c943947b-1741-4e9a-8825-c27d95e99b8f.bam
INFO    2017-04-21 16:44:07.022266      haplo_9465113_458_458   len(readlist): 9
WARN    2017-04-21 16:44:07.022421      haplo_9465113_458_458   too few reads in region (9) skipping...
INFO    2017-04-21 16:44:07.036350      haplo_9465113_645_645   creating tmp bam:  addsnv.tmp/haplo_9465113_645_645.tmpbam.0b122bc8-c8f9-4465-8540-ab6c46fc585a.bam
INFO    2017-04-21 16:44:13.824753      haplo_9465113_645_645   len(readlist): 15
INFO    2017-04-21 16:44:13.824952      haplo_9465113_645_645   selected VAF: 0.5

INFO    2017-04-21 16:44:13.825151      haplo_9465113_645_645   picked: 7
INFO    2017-04-21 16:44:13.826490      haplo_9465113_645_645   wrote:  15 mutated: 7
INFO    2017-04-21 16:44:13.830525      haplo_9465113_645_645   mapping 1st end, cmd: bwa aln -q 5 -l 32 -k 3 -t 1 -o 1 -f addsnv.tmp/haplo_9465113_645_645.tmpbam.0b122bc8-c8f9-4465-8540-ab6c46fc585a.bam.1.sai -b1 9465113.fa addsnv.tmp/haplo_9465113_645_645.tmpbam.0b122bc8-c8f9-4465-8540-ab6c46fc585a.bam
[bwa_aln] 17bp reads: max_diff = 2
[bwa_aln] 38bp reads: max_diff = 3
[bwa_aln] 64bp reads: max_diff = 4
[bwa_aln] 93bp reads: max_diff = 5
[bwa_aln] 124bp reads: max_diff = 6
[bwa_aln] 157bp reads: max_diff = 7
[bwa_aln] 190bp reads: max_diff = 8
[bwa_aln] 225bp reads: max_diff = 9
[bwa_aln] fail to locate the index
INFO    2017-04-21 16:44:13.881293      haplo_9465113_645_645   mapping 2nd end, cmd: bwa aln -q 5 -l 32 -k 3 -t 1 -o 1 -f addsnv.tmp/haplo_9465113_645_645.tmpbam.0b122bc8-c8f9-4465-8540-ab6c46fc585a.bam.2.sai -b2 9465113.fa addsnv.tmp/haplo_9465113_645_645.tmpbam.0b122bc8-c8f9-4465-8540-ab6c46fc585a.bam
[bwa_aln] 17bp reads: max_diff = 2
[bwa_aln] 38bp reads: max_diff = 3
[bwa_aln] 64bp reads: max_diff = 4
[bwa_aln] 93bp reads: max_diff = 5
[bwa_aln] 124bp reads: max_diff = 6
[bwa_aln] 157bp reads: max_diff = 7
[bwa_aln] 190bp reads: max_diff = 8
[bwa_aln] 225bp reads: max_diff = 9
[bwa_aln] fail to locate the index
INFO    2017-04-21 16:44:13.905682      haplo_9465113_645_645   pairing ends, building .sam, cmd: bwa sampe -P -f addsnv.tmp/haplo_9465113_645_645.tmpbam.0b122bc8-c8f9-4465-8540-ab6c46fc585a.bam.sam 9465113.fa addsnv.tmp/haplo_9465113_645_645.tmpbam.0b122bc8-c8f9-4465-8540-ab6c46fc585a.bam.1.sai addsnv.tmp/haplo_9465113_645_645.tmpbam.0b122bc8-c8f9-4465-8540-ab6c46fc585a.bam.2.sai addsnv.tmp/haplo_9465113_645_645.tmpbam.0b122bc8-c8f9-4465-8540-ab6c46fc585a.bam addsnv.tmp/haplo_9465113_645_645.tmpbam.0b122bc8-c8f9-4465-8540-ab6c46fc585a.bam
[bwa_sai2sam_pe] fail to locate the index
INFO    2017-04-21 16:44:13.929432      haplo_9465113_645_645   sam --> bam, cmd: samtools view -bt 9465113.fa.fai -o addsnv.tmp/haplo_9465113_645_645.tmpbam.0b122bc8-c8f9-4465-8540-ab6c46fc585a.bam addsnv.tmp/haplo_9465113_645_645.tmpbam.0b122bc8-c8f9-4465-8540-ab6c46fc585a.bam.sam
INFO    2017-04-21 16:44:13.953193      haplo_9465113_645_645   sorting, cmd: samtools sort -m 10000000000 -T addsnv.tmp/haplo_9465113_645_645.tmpbam.0b122bc8-c8f9-4465-8540-ab6c46fc585a.bam.sort.bam -o addsnv.tmp/haplo_9465113_645_645.tmpbam.0b122bc8-c8f9-4465-8540-ab6c46fc585a.bam.sort.bam addsnv.tmp/haplo_9465113_645_645.tmpbam.0b122bc8-c8f9-4465-8540-ab6c46fc585a.bam
INFO    2017-04-21 16:44:13.980291      haplo_9465113_645_645   indexing, cmd: samtools index addsnv.tmp/haplo_9465113_645_645.tmpbam.0b122bc8-c8f9-4465-8540-ab6c46fc585a.bam
INFO    2017-04-21 16:44:14.010209      haplo_9465113_645_645   avgincover: 15.0 avgoutcover: 0.0
WARN    2017-04-21 16:44:14.011402      haplo_9465113_645_645   dropped for outcover/incover < 0.9
INFO    2017-04-21 16:44:14.012610      no succesful mutations

**Has anyone come across such an issue too? Kindly assist.

Thanks**

**Comment by adamewing** [comment]
Based on this: `[bwa_sai2sam_pe] fail to locate the index` my guess is you need to run `bwa index 9465113.fa` and `samtools faidx 9465113.fa` to create an index for your reference genome. Also you probably want -o to point to a file with a .bam extension so `-o test.bam`.

**Comment by pinkysaid** [comment]
Thank you @adamewing 

It has worked. Finally getting the test.bam output.

**Comment by pinkysaid** [comment]
**Hi there again.....@adamewing** 

**When I use an input -varfile comprising 5 columns (three column format plus additional columns with the VAF and specific base), I get the error below.**

 addsnv.py -v simulated.variants.csv -f SIM_sample1.sorted.bam -r 9465113.fa -o test2.bam
INFO    2017-04-24 09:32:04.693819      starting /apps/python/2.7.8/bin/addsnv.py called with args: /apps/python/2.7.8/bin/addsnv.py -v simulated.variants.csv -f SIM_sample1.sorted.bam -r 9465113.fa -o test2.bam

Traceback (most recent call last):
  File "/apps/python/2.7.8/bin/addsnv.py", line 4, in <module>
    __import__('pkg_resources').run_script('bamsurgeon==1.0', 'addsnv.py')
  File "/apps/python/2.7.8/lib/python2.7/site-packages/pkg_resources/__init__.py", line 742, in run_script
    self.require(requires)[0].run_script(script_name, ns)
  File "/apps/python/2.7.8/lib/python2.7/site-packages/pkg_resources/__init__.py", line 1674, in run_script
    exec(script_code, namespace, namespace)
  File "/apps/python/2.7.8/lib/python2.7/site-packages/bamsurgeon-1.0-py2.7.egg/EGG-INFO/scripts/addsnv.py", line 513, in <module>

  File "/apps/python/2.7.8/lib/python2.7/site-packages/bamsurgeon-1.0-py2.7.egg/EGG-INFO/scripts/addsnv.py", line 510, in run

  File "/apps/python/2.7.8/lib/python2.7/site-packages/bamsurgeon-1.0-py2.7.egg/EGG-INFO/scripts/addsnv.py", line 372, in main

IndexError: list index out of range
