### ISSUE TITLE
best contig too short to make mutation

### ISSUE THREAD

**Issue by parlar** [adamewing/bamsurgeon#92]
Hi,

We're not sure if this qualifies as a bug, but when we try to introduce a specific mutation (G12D in KRAS) in a bam file produced from a targeted panel, it fails with the explaination "best contig too short to make mutation". However, we don't really understand why. What contig is it that becomes too short? Is there anything that can be done to solve the problem?

Any suggestion is greatly appreciated.

//Pär and Anteneh, Umeå university hospital (Sweden)

**Comment by adamewing** [comment]
(solution if I remember correctly was to use addsnv instead of addsv)
