### ISSUE TITLE
Depth at site is greater than cutoff, aborting mutation.

### ISSUE THREAD

**Issue by pinkysaid** [adamewing/bamsurgeon#93]
**Hi,**

**I am trying to insert mutations to a BAM file (sorted and indexed). My BAMfile (previously simulated by ART Illumina) has a fold coverage of 2000. I believe BAMSurgeon is properly installed and addsnv.py is in the path, but I keep getting this feedback.**

WARN    2017-05-18 15:38:28.633359      9465113_1542_1542_0.731501572847_A      depth at site is greater than cutoff, aborting mutation.
INFO    2017-05-18 15:38:28.654219      haplo_9465113_1569_1569 creating tmp bam:  addsnv.tmp/haplo_9465113_1569_1569.tmpbam.98efa021-4583-4e3f-9b6a-9eb0a7635c19.bam

This keeps happening across all sites.

**Any help with this will be much appreciated....**

**Comment by adamewing** [comment]
Hi, have you tried setting --maxdepth higher? The default is 2000, so try something higher like 10000.

**Comment by pinkysaid** [comment]
Hi... Thank you. It worked! Currently still running so keeping my fingers crossed for the output.
