### ISSUE TITLE
How to check whether BAMSurgeon actually inserted the specified base at the requested frequency

### ISSUE THREAD

**Issue by pinkysaid** [adamewing/bamsurgeon#95]
Hi Adam,

I am curious on how to counter-check whether the resultant BAM file (after running addsnv.py) has the inserted variants at the specified frequencies. I tried using IGV and I got conflicting readings. 

Thanks.....

**Comment by adamewing** [comment]
Hi, can you give an example of what you mean by conflicting readings?

**Comment by biorelated** [comment]
Bam surgeon provides: 

> a directory of log files describing which bases were changed in which reads (one log per mutation) and the local assemblies for each region where a mutation was made

Walking through these log files might provide an assessment of which positions were actually spiked?

**Comment by pinkysaid** [comment]
@adamewing For example, we inserted a C on position 171 of a genome, when I use IGV to check the resultant BAM file at this specific position, the reference base T appears and not the variant base I suggested for BAMSurgeon. Just realized @biorelated has a good point. I have found the log files for my samples, and they ascertain successful mutations. Still curious though why IGV does not confirm this.

@biorelated I just viewed one of the log files for this position and it seems to be correct.

**Comment by aldosr** [comment]
Have the same issue. In particular, from the BAMsurgeon log file:

```
len(readlist): 18784
selected VAF: 1.000000
picked: 18784
wrote: 18785, mutated: 18784
```

But then, on IGV (and as variant calling output, using vardict) only 50% of the reads are mutated, as stated in #184 
@pinkysaid Did you understand why this happen?
