### ISSUE TITLE
Hello , what is the right refernce.fasta  for addsnv.py

### ISSUE THREAD

**Issue by kkshaxqd** [adamewing/bamsurgeon#96]
Dr. adam

I build some index by  bwa for the addsnv.py, but it doesn't work  .
the ucsc.hg19.fasta  ,the GRCh37.p13.genome.fa and so on ...
the error like these

sh ./test_snv.sh 20 2  /mnt/local-disk2/qszhang/tests/xhmmfoload/1000g-positive/GRCh37.p13.genome.fa
INFO    2017-07-21 10:34:53.007017      starting /mnt/local-disk2/qszhang/biosoft/mybin/bin/python27/bin/addsnv.py called with args: /mnt/local-disk2/qszhang/biosoft/mybin/bin/python27/bin/addsnv.py -v ../test_data/random_snvs.txt -f ../test_data/testregion_realign.bam -r /mnt/local-disk2/qszhang/tests/xhmmfoload/1000g-positive/GRCh37.p13.genome.fa -o ../test_data/testregion_mut.bam -n 20 -p 2 --ignoresnps --ignorepileup --seed 1234

[fai_load] build FASTA index.
Debug, haploclusters:[[{'start': 33670816, 'end': 33670817, 'chrom': '22', 'altbase': None, 'vaf': None}], [{'start': 33680552, 'end': 33680553, 'chrom': '22', 'altbase': None, 'vaf': None}], [{'start': 33702084, 'end': 33702085, 'chrom': '22', 'altbase': None, 'vaf': 0.2}], [{'start': 33714964, 'end': 33714965, 'chrom': '22', 'altbase': None, 'vaf': 0.5}], [{'start': 33762799, 'end': 33762800, 'chrom': '22', 'altbase': None, 'vaf': None}], [{'start': 33769483, 'end': 33769484, 'chrom': '22', 'altbase': None, 'vaf': 0.75}], [{'start': 33815273, 'end': 33815274, 'chrom': '22', 'altbase': None, 'vaf': None}], [{'start': 33908770, 'end': 33908771, 'chrom': '22', 'altbase': None, 'vaf': 0.15}], [{'start': 33926586, 'end': 33926587, 'chrom': '22', 'altbase': None, 'vaf': None}], [{'start': 33943910, 'end': 33943911, 'chrom': '22', 'altbase': None, 'vaf': None}], [{'start': 33944584, 'end': 33944585, 'chrom': '22', 'altbase': None, 'vaf': None}], [{'start': 33947472, 'end': 33947473, 'chrom': '22', 'altbase': None, 'vaf': None}], [{'start': 33958087, 'end': 33958088, 'chrom': '22', 'altbase': None, 'vaf': 0.01}], [{'start': 34022812, 'end': 34022813, 'chrom': '22', 'altbase': None, 'vaf': None}], [{'start': 34044951, 'end': 34044952, 'chrom': '22', 'altbase': None, 'vaf': None}], [{'start': 34141184, 'end': 34141185, 'chrom': '22', 'altbase': None, 'vaf': None}], [{'start': 34166720, 'end': 34166721, 'chrom': '22', 'altbase': None, 'vaf': 1.0}], [{'start': 34203415, 'end': 34203416, 'chrom': '22', 'altbase': None, 'vaf': None}], [{'start': 34261347, 'end': 34261348, 'chrom': '22', 'altbase': None, 'vaf': None}], [{'start': 34264774, 'end': 34264775, 'chrom': '22', 'altbase': None, 'vaf': 0.25}]]
************************************************************
ERROR   2017-07-21 10:35:17.557419      encountered error in mutation spikein: ['22_33670816_33670817_None_None']
************************************************************
ERROR   2017-07-21 10:35:17.557419      encountered error in mutation spikein: ['22_33680552_33680553_None_None']
Traceback (most recent call last):
Traceback (most recent call last):
  File "/mnt/local-disk2/qszhang/biosoft/mybin/bin/python27/lib/python2.7/site-packages/bamsurgeon-1.0-py2.7.egg/EGG-INFO/scripts/addsnv.py", line 126, in makemut

+++++++++++++
how about it ....

**Comment by MischaLundberg** [comment]
Hi,

the bam file used within the script is aligned to the reference supplied with bamsurgeon.
So either way you would have to realign it to your reference or use the supplied reference.

Nevertheless, to test the function of Bamsurgeon you can run the testscript with the supplied fasta file.
The command would be:
sh ./test_snv.sh 20 2 ../test_data/Homo_sapiens_chr22_assembly19.fasta

Hope i could help.

**Comment by kkshaxqd** [comment]
Oh!
That'ts right!
Thank you very much
I will try it again! ^_^

**Comment by kkshaxqd** [comment]
That's OK!!!
the BAM maybe need  the fit fasta which product it.
