### ISSUE TITLE
could not spikein mutations according to the mutation file

### ISSUE THREAD

**Issue by fkcoolman** [adamewing/bamsurgeon#99]
Hi, I have prepared a mutation file containing several snv locations that I want to spikein to my bam file to test our snv caller, after running bamsurgeon, I got fewer spikein spots compared with my mutation list, some of the spots could not spikein because low coverage of the targeted region which I understand, however there are a big amount of the spots which  I have over 1000X read depth still could not spikein, Bamsurgeon runs successfully without warning message to these spots. I tried different parameters and still could not solve this, then I decided to run bamsurgeon on one spot after another, which I could successfully add all the mutations to the bam file, however when the spots are closely distrubuted, like
Chr1 1 1 0.05 A
Chr1 2 2 0.05 C
Chr1 3 3 0.05 T
all the mutation spots appeared on the same read. I try to use --seed to add these spot to different read, but no matter how I changed the --seed option they still appeared on the same read. Can you guys help solve this problem?

Thanks,

Kai

**Comment by adamewing** [comment]
Hi Kai, apologies for the delayed reply. It's best to spike-in reads that are at least one library-width apart to avoid them having to share the same reads. Alternatively, you can run addsnv with -z set to some value corresponding to the read length (e.g. -z 100), which will result in mutations within 100bp of each other being spiked into the same reads (as if they were on the same haplotype). There isn't currently a way to spike in mutations directly next to one another and guarantee they won't share reads, but you could maybe accomplish this by doing independent addsnv runs and merging the resulting BAM files.

Best,
Adam

**Comment by adamewing** [comment]
Closing, feel free to reopen if there are still unresolved issues.
